### ISSUE TITLE
[Request] Integrate definitions into results

### ISSUE THREAD

**Issue by lcpz** [searx/searx#1027]
Currently, there are DDG definitions, but not enabled by default. Every time, the user should go into Preferences and enable them, which is uncomfortable.

Since Google is enabled by default, what about fetching eventual definition results too?

That is, if Google is enabled and returns a definition, fetch and show it.

Is this possible?

EDIT: StartPage does this. Maybe you can check how they do it, or fetch from them instead.

**Comment by dalf** [comment]
[Try google without javascript](http://www.wikihow.com/Disable-JavaScript) : there are far less information than the javascript version. 

Some informations are not easy to parse, or just impossible (links to google url without external meaning, I think about the maps for example when you search for "cinema new york"). May be it has changed since the last time I've checked.

**Comment by unixfox** [comment]
Implemented, at least for Google, but I don't know when and where.
