### ISSUE TITLE
"Search URL of the currently saved preferences" doesn't function, performs a search

### ISSUE THREAD

**Issue by ghost** [searx/searx#1056]
When I enter my preference URL (in https://searx.me/preferences) a search is performed instead. Applies to the default settings:

`
https://searx.me/?results_on_new_tab=False&language=all&locale=&disabled_plugins=DOAI_rewrite%2CVim-like_hotkeys%2COpen_result_links_on_new_browser_tabs%2CInfinite_scroll&image_proxy=False&autocomplete=&safesearch=0&theme=oscar&enabled_plugins=Self_Informations%2CTracker_URL_remover%2CHTTPS_rewrite%2CSearch_on_category_select&disabled_engines=kickass__files%2Cfree+software+directory__it%2Cvoat__social+media%2Cina__videos%2Creddit__social+media%2Cgoogle+play+apps__files%2Cccc-tv__videos%2Cgigablast__general%2Creddit__news%2Cfdroid__files%2Cnyaa__images%2Cduckduckgo__general%2Ckickass__videos%2Cgoogle+play+music__music%2Cyandex__general%2Creddit__general%2Cgeektimes__it%2Cnyaa__music%2Cdigbt__videos%2Cgoogle+play+movies__videos%2C1x__images%2Cseedpeer__music%2Copenrepos__files%2Cseedpeer__videos%2Creddit__images%2Cdigbt__files%2Cerowid__general%2Cfaroo__news%2Chabrahabr__it%2Carchive+is__general%2Cbitbucket__it%2Cfrinkiac__images%2Ctokyotoshokan__music%2Cfaroo__general%2Cetymonline__general%2Cnyaa__videos%2Cframalibre__it%2Cmymemory+translated__general%2Cixquick__general%2Clibrary+genesis__general%2Cqwant__general%2Cduckduckgo+images__images%2Cseedpeer__files%2Cnyaa__files%2Ctokyotoshokan__videos%2Cdigbt__music%2Ctokyotoshokan__files%2Cswisscows__images%2Cscanr+structures__science%2Csearchcode+code__it%2Cswisscows__general%2C1337x__videos%2Cgitlab__it%2Cstartpage__general%2Cddg+definitions__general%2Ckickass__music&enabled_engines=&method=POST&categories=general&q=%s
`

**Comment by kvch** [comment]
Are you sure you saved your preferences before saving the search URL?

**Comment by ghost** [comment]
@kvch Yes. 

Should the saved preferences be restored when pasting the URL to the browsers address bar? Why `&q=%s` is added to the end of the string?

**Comment by kvch** [comment]
Param `q` holds you search term and `%s` is a placeholder which is replaced by your term. So if you search for "cars", it will pass `{your-other-search-params}&q=cars` to searx.

**Comment by bendover22** [comment]
It's a long time since this "bug" (or ? known issue, maybe?) was filed.
If I go to https://searx.me (typed in Firefox address bar), go to Searx preferences page.
Make a couple changes - mainly, "results on new tab" 
then click SAVE at bottom of new page.

I copy the URL & parameters just created, at bottom of prefs page.
Paste the copied URL in Firefox's bookmark toolbar (to use repeatedly).  

The Searx URLs created this way always have "%s" at end of URL.
When I R-click the new customized searx bookmark in Firefox bookmark toolbar & select "open in new tab" (I don't think that's where the issue is), it doesn't just open a tab with the custom URL search parameters, it does a search w/ RESULTS from searching for: "%s".  

That's not so bad, but wasted time, bandwidth.  
If I leave "%s" in Searx's search box (on the page, not in browser toolbar), it actually searches for "%sfootball".
If I remove "%s" from Searx's search box & a search, any results clicked DON'T open in new tabs.

But the same "open in new tab" preference saved for say, Duck, Duck, Go's saved bookmark, DO open clicked search results links in a new tab.  Obviously, this can work - it does w/ Ixquick, DDG, etc.

If there's already a way around these couple of problems , please put something on the Searx help page & a link on the preferences page to those instructions:  how to save a custom bookmark (w/ pref= "open in new tab"), so it opens them in new tabs.  

Because going back to previous page, hundreds of times, instead of just clicking closed the most recently visited result page, if it's in a *new* tab - is quite annoying.

Several other search engines also allow generating & installing  plugins to the browser's Search Engine Manager, using customized search parameters.
That is far superior to saving a bookmark, that doesn't seem to work properly.

side Q: could you add, "open" in front of "results 'IN' new tabs"?  (shouldn't it be "in" a new tab)?

**Comment by somedevreally** [comment]
this issue still exists 😕
