### ISSUE TITLE
[Engine] add depsy to category science (and code?)

### ISSUE THREAD

**Issue by jibe-b** [searx/searx#1058]
Depsy is an index of contributions of developers to software development, making a profile per individual and revealing important contributions which usely stay unnoticed and not rewarded.

http://depsy.org/

self-assigned

**Comment by dalf** [comment]
IMO, it would make more sense to add this engine to the code category since it indexes pypi and CRAN projects and authors.
Actually the thing that would be awesome :
* implement the PyPI search
* for each packages display some additional links  to depsy and may be some other websites (security analysis of the package ?)

**Comment by jibe-b** [comment]
ok @dalf!
It will make sense in category science too, as it is also intended to highlight the work done by developers for science.

It's a bit more work but I like the idea of showing infoboxes for package.

**Comment by Pofilo** [comment]
@jibe-b you self assigned yourself, do you have some news ? :)

**Comment by jibe-b** [comment]
@Pofilo well I didn't do anything, hope to have time before September…

**Comment by Pofilo** [comment]
No problem, just to know :)
It was to update the project [https://github.com/asciimoo/searx/projects/3](https://github.com/asciimoo/searx/projects/3) to let people know someone was working on it !

**Comment by allendema** [comment]
Issue can be closed as the site is now not maintained.
