### ISSUE TITLE
Why Searx.me suddenly return germany results?

### ISSUE THREAD

**Issue by ihave0openprs** [searx/searx#1085]
When I search something, I mostly got English results. Recently, searx.me suddenly started to return German results. I'm not using germany IP and my browser language is not germany. So what the heck is going on?

And how can I prevent this? I just want English results, and I don't want to set language every time I search so some URL advice pls.

e.g. suggest me with URL, something like https://searx.me/?language=en&query=%s

**Comment by MarcAbonce** [comment]
It seems like Google is trying to guess the user's language based on their location (or, in this case, the server's location).

For now, the only workaround I've found is to always specify a country code different from the US in the language parameter. So, for English results, you can set the language parameter to `en-GB`, like https://searx.me/?language=en-GB&query=%s

Edit: Another workaround is to [try different searx instances](http://stats.searx.oe5tpo.com/) and pick one that returns Google results in English (or your preferred language) even with no language setting.

**Comment by irule2day** [comment]
Google uses IP address to identify your country location and since searx is just a proxy search engine, it will return results based on the location of the searx instance server. In this case searx.me is located in germany, so you will get german related results.

One workaround for US based results is to obviously find an instance with US operated server and last time I checked, for this exact purpose, there were 2.
https://search.jpope.org/ (which I use) and https://pigtown.news/searx

Searx.me is overloaded anyway and it's always best to use an instance which is geographically closes to you for fastest search return. Cheers.

**Comment by asciimoo** [comment]
I think this issue is fixed in 9ab8536479f30960e79ed165369e97c635ed1be7. Could you verify it?

**Comment by ghost** [comment]
I started receiving German results approximately two months ago. Both Searx and Firefox language is set to `en-us`. I don't live in Germany and don't have a German IP.
```
language 	en-US
locale 	en
```

**Comment by return42** [comment]
> I started receiving German results approximately two months ago

There had been a lot of refactoring at this time ...  e.g 772c048d d1eae9359f 7f9c503

I guess that with the refactoring, the experiences documented in this issue are no longer reproduce able.

I close this issue, If you see any further problems, please visit https://github.com/asciimoo/searx/issues/1236
