### ISSUE TITLE
A tool to find an instance of searx easily

### ISSUE THREAD

**Issue by mirabellette** [searx/searx#1113]
Hello everyone,

I am building a little interface in Javascript which will let the user the possibility to choose easily among a instance of searx randomly.

Is-il possible to upload a file in this github repository where I can find them all. Parsing the wiki list or searxstats is not very convenient.

I saw searxstats and it was very interesting. I also think to let the user choose only among currently running instance with the last upgrade version.

**Comment by kvch** [comment]
I am not a big fan of having the list of instances in the repo. This list tend to change a lot and some of it is not even up to date. Also, it has minimal connection to the source code.
Additionally, I would not want to add more overhead to adding a new instance by opening and merging PRs. Not only it is unnecessary, but it might lead to the false notion that those searx instances are somehow validated or trusted by the maintainers of searx. Which is not true, because there is no way we can guarantee anything regarding public instances (apart from instances run by us).

I am not sure you know about it, but there is an existing searx aggregator available: https://searxes.danwin1210.me/

As a sidenote, I don't see how parsing that wiki page is not convenient. It's true, it's not in JSON format. But it has a predictable and uniform layout which can be scraped easily.

**Comment by mirabellette** [comment]
Hello kvch,

Thank you for your answer, I understand it.

I check the website https://searxes.danwin1210.me/, it is very interesting but it not what I was thinking about.

I will parse the wiki page and develop the tool. In fact, I think my little tool could work with a lot of sources. I just have to create an adapter to searx instance. Do you know where can I find the code source behind http://stats.searx.oe5tpo.com/ because I would like to reused some of there features.

I will published a reply here when it will be available.

**Comment by kvch** [comment]
Thanks for your understanding.

Original version of http://stats.searx.oe5tpo.com/: https://github.com/pointhi/searx_stats
There is an updated version with similar functionality: https://github.com/dalf/searx-stats2

Looking forward to see your tool!

**Comment by prolibre** [comment]
hello @kvch : Do you know how the instances are removed ? I don't know how to delete an old instance ( https://www.heraut.eu/search/ ) ?

**Comment by kvch** [comment]
@prolibre From the wiki, you can delete anytime anything. I am not sure how to delete instance from searx-stats. I guess it has its own database, so only @pointhi can delete those instances.

**Comment by dalf** [comment]
If the wiki is not enough, I see two solutions to this : 
- Write a small tool where anyone with a github account can add/remove/update a link to searx instances. This tool would be able to ping/check each searx instance. It would provide an API to get the list of searx instances (alive). Each instance could use this API to randomly dispatch search requests.
- Write a small peer to peer network: searx instances sends messages to each other. It can be a simple broadcast to all know instances every day. The message would be the list of searx instances. To avoid too many messages, the message wouldn't be sent to instances which have been seen recently.

**Comment by return42** [comment]
> Is-il possible to upload a file in this github repository where I can find them all. Parsing the wiki list or searxstats is not very convenient.

The list at https://github.com/dalf/searx-instances is what you are looking for.
