### ISSUE TITLE
[feature] user prioritization of search engines

### ISSUE THREAD

**Issue by atomGit** [searx/searx#1120]
suggesting an option whereby the user can assign a priority to the search engines, such as...

startpage 1
google 2
yahoo 3
...

could be done by drag & drop to reorder the engines?

the results returned would then be ordered according to the user assigned priority

**Comment by kvch** [comment]
On client side it is not possible. 

In case of local/own instances, in `settings.yml` `weight` can be assigned to each engine. Each result has a score which is multiplied by the weight of the engine. The default weight is 1.0. If it is changed to a different value for engines, order of the results might change as you described. But it is not guaranteed that results from engines would be in this order, because if google is set to 2.0 and bing is set to 1.0, and a result from bing has a score of 3.0 and the result from google is 1.0, the result from google would be after the result from bing.

**Comment by return42** [comment]
See `weight` https://asciimoo.github.io/searx/admin/settings.html?highlight=weight

Please note, ATM there is a typo in the documentation; "weight" is correct (and a fix is on the way 4ad93eb6 )
