### ISSUE TITLE
Searching with the firefox search/url bar gives no results.

### ISSUE THREAD

**Issue by ghost** [searx/searx#1134]
When I add searx to firefox and search on the URL bar, it only gives results 10% of the time

Workaround:

1. Disable JS on searx

2. Search for something

3. add searx using the firefox search bar (NOT the URL bar)

4. re-enable JS

**Comment by asciimoo** [comment]
@As4fN1v what is your firefox version and which searx instance do you use?

**Comment by ghost** [comment]
@asciimoo I tried the stable version, beta, nightly. All of them have this issue. I use searx.me

**Comment by frihamn** [comment]
Works fine for me in Firefox 58 in both URL and separate search bar.

Which search plugin do you use? Here's a source for some plugins, one of which I use (believe it's the one "verified" to work since the others are all new): http://mycroftproject.com/search-engines.html?name=searx.me

If I remember correctly, it's also necessary to set `method` to `POST` in the searx general settings.

**Comment by ghost** [comment]
@apropostech Just added it to firefox from here: https://searx.me/about
