### ISSUE TITLE
Add Slovak language as search language

### ISSUE THREAD

**Issue by pitrson** [searx/searx#1170]
Hello,

I'm currently running my own instance of searx (searx - 0.13.1 ). It is possible to set interface language to Slovak, but I cannot set Slovak to search language. Is this possible to be added please ?

**Comment by MarcAbonce** [comment]
I also want to point out that, even if a language doesn't appear in the list, you can still get results in that language using the `:` prefix. For example, searching `:sk Jupiter` should still return results in Slovak. Of course, this isn't really nice, but it's a useful trick for less common languages.

**Comment by asciimoo** [comment]
@MarcAbonce What if we combine the two solutions and include all the languages which are supported in at least 10 engines **or** by both google, wp, bing?

**Comment by rKsanu2MMYvypWePtQWM** [comment]
Hello, what's the status of this issue?
I'd love to see more languages in the future!

**Comment by MarcAbonce** [comment]
I'm currently working on this.

**Comment by cloo** [comment]
I don't see the sense of having the threshold at all. If a search engine is incapable to deliver in that language, the search results from it are nil. If user tries using only engines without particular language support, he will naturally get no results and will have to refine the search. 
Refining search terms is a very natural and harmless everyday process :) Differently from the language code syntax, which is simple, but still, I found out about it only now, reading about this issue. Came because of Lithuanian here.

**Comment by rKsanu2MMYvypWePtQWM** [comment]
@cloo labas!
I was thinking about what you wrote, and while your solution would kinda work, there should be a "reversion" to a user-choosable language or a language priority list if, for example, Lithuanian is not available in some search engines.

**Comment by cloo** [comment]
Labas :)
Agree, automatic reversion, or even suggestion to do it manually would be "nice to have". 
But for now, using searx, I'm simply unable to search for content in my language at all, even many search engines provide such results. So to get those I just have to go back to google'n'ducks.

**Comment by rKsanu2MMYvypWePtQWM** [comment]
I just use :lt before every Lithuanian search. Works fine as a workaround.

**Comment by MarcAbonce** [comment]
Lithuanian is also included in the new drop-down list since it actually passes the threshold.
