### ISSUE TITLE
Engines cannot retrieve results: piratebay (request exception): PirateBay changed URL

### ISSUE THREAD

**Issue by yurivict** [searx/searx#1229]
When some text is entered, and I click on General and Files several times, it shows this error:
```
Error! Engines cannot retrieve results.
piratebay (request exception)
Please, try again later or find another searx instance.
```

Version 0.14.0 on FreeBSD.
Default config.

**Comment by Pofilo** [comment]
Actually, you don't even need to switch several times, going directly on Files shows the error (on [searx.me](https://searx.me/).

Request done:
[https://searx.me/?q=test&categories=files&language=en-US](https://searx.me/?q=test&categories=files&language=en-US)

And I get the error.

If you take a look at [piratebay.py](https://github.com/asciimoo/searx/blob/master/searx/engines/piratebay.py), the request is done on [https://thepiratebay.se/](https://thepiratebay.se/) and this site is actually not available.

There is a [https://piratebay.to/](https://piratebay.to/), I don't know if it is a scam, the new domain name or a backup one.

Anyway, researching on this url doesn't work so replacing the url on searx neither.

So the title of the issue is not good, this is a piratebay (engine) issue.

**Comment by Plomging** [comment]
in searx/settings.yml, piratebay entry, delete "url: https://pirateproxy.red/"
in searx/engines/piratebay.py replace 'https://thepiratebay.se/' by 'https://thepiratebay.org/'
And it works
