### ISSUE TITLE
Brave BAT

### ISSUE THREAD

**Issue by Drose221193** [searx/searx#1241]
Not sure if this has been mentioned before, but searx should become a verified publisher on brave browser so myself and others can donate our BAT

**Comment by asciimoo** [comment]
@Drose221193 how could searx become a verified publisher and what are the benefits?

**Comment by Drose221193** [comment]
@asciimoo Anyone that uses Brave's BAT system Puts money in an account and every month part of their funds go to the sites they visit the most. So anyone that uses the browser and visits searx will have part of their monthly funds donated directly to searx. Its generally just another way to generate revenue for searx. It might not be a lot, but I assume that every little bit helps. As far as becoming verified. I am pretty sure you just need to prove that you are a legitimate site at this link here.

https://brave.com/publishers/

**Comment by agnelvishal** [comment]
@Drose221193  https://searx.world is a verified Brave Publisher. I haven't received any BAT token though

**Comment by dalf** [comment]
FYI, https://searx.world adds Amazon affiliate links (look at the HTML source code).
I don't recommend this instance.

------
[EDIT] Just to be clear, the problem is that Amazon affiliate links are added without notice. And what about the Python source code ? what about the logs ? 

I've missed the CloudFlare SSL too.

**Comment by unixfox** [comment]
BAT is not trustworthy, Brave did some shady things like this one: https://davidgerard.co.uk/blockchain/2019/01/13/brave-web-browser-no-longer-claims-to-fundraise-on-behalf-of-others-so-thats-nice/

Now that searx.me is not a Searx instance anymore I think this issue should be closed because a brave user won't visit an about page everyday and thus searx.me will never be the most visited website of a brave user like Drose221193 explained here:

> @asciimoo Anyone that uses Brave's BAT system Puts money in an account and every month part of their funds go to the sites they visit the most. So anyone that uses the browser and visits searx will have part of their monthly funds donated directly to searx. Its generally just another way to generate revenue for searx.
