### ISSUE TITLE
Searxes hidden service adress wrong

### ISSUE THREAD

**Issue by TriMoon** [searx/searx#1243]
It should according to their normal site be: http://searxes.qzuep6lk6m4n24vzca65voarzvmwvpk2lew3akmxuzndpjw6hdyjx6ad.onion

**Comment by kvch** [comment]
Thanks for the report. :) Please, correct the wiki page.

**Comment by TriMoon** [comment]
PS: when you add the onion search plugin, it does not open a results page with the query you made.
It will open a blank search page of the searxes engine, maybe forgot to add a parameter?

**Comment by aurora-anon** [comment]
@kvch Is searx.i2p an official searx instance?

**Comment by Pofilo** [comment]
What do you mean by "official searx instance" ?

You can use every instances here [https://github.com/asciimoo/searx/wiki/Searx-instances](https://github.com/asciimoo/searx/wiki/Searx-instances) if you trust the owner.

Searx is not a corporation, so there is not really "official searx instance" but I know [https://searx.me/](https://searx.me/) is owned by @asciimoo and [https://searx.pofilo.fr/](https://searx.pofilo.fr/) by me and it is the same code.

So correct me if I'm wrong, but use whatever instance you want if you trust the owner, otherwise, use your own instance. And @aurora-potter, if you use your own instance, you can use master branch to have the translations you did without waiting a new version of searx.

But you should understand that searx is not owned by a corporation but only during the free-time of some devoted developers !
