### ISSUE TITLE
i can select Polish language interface

### ISSUE THREAD

**Issue by letarg0** [searx/searx#1254]
Why?
translated are exist
![ttt](https://user-images.githubusercontent.com/35114178/38132635-1cb14284-340c-11e8-9b4d-73470d62f771.jpg)

https://searx.abenthung.it/preferences
https://searx.good.one.pl/
https://searx.dk/preferences
https://www.search404.io/preferences
https://searx.ch/preferences
...

**Comment by aurora-anon** [comment]
@letarg0 As I see Polish is available for both interface and search language, and searx's interface is 100% translated to Polish.

If you mean non of the searx instances mentioned above support Polish as an interface language could be due to a few possibilities:
- They consciously removed Polish from the interface languages.
- They haven't updated to the latest version of searx, so they would receive language updates for Polish.
- It's caused by a misconfiguration; that's very unlikely.

Anyway, the only official domain for searx is <a href="https://searx.me/">searx.me</a> and it fully supports Polish language for both search and as an interface language.

If you don't wanna use the official searx website, you can find a searx instance that supports Polish from <a href="https://github.com/asciimoo/searx/wiki/Searx-instances">here</a>.

**Comment by aurora-anon** [comment]
@kvch Please check searx's Polish language support to see if the problem is coming from the source code.

Many sites have partial or no support for Polish language, despite having the same version number as for <a href="https://searx.me/>searx.me</a> itself.

**Comment by asciimoo** [comment]
This issue is recently fixed in  b8543bcf3a4cc176645473165fcc855ae3a8210c and we don't have a new release since that.
I maintain searx.me and it is updated to the current master, but I have to emphasize that it isn't an "official" instance, it is just a public instance like the others listed on https://github.com/asciimoo/searx/wiki/Searx-instances.

**Comment by asciimoo** [comment]
> If searx.me is not an official instance, so why it receives instant updates and is the only instance to have the footer 'Support the development and maintenance of searx'?

It receives instant updates, because I update it instantly =)

> is the only instance to have the footer 'Support the development and maintenance of searx'?

Why would this mean that searx.me is an official instance?

**Comment by aurora-potter** [comment]
> It receives instant updates, because I update it instantly =)
So it's owned by you, a developer of searx. So itls an official instance.
> Why would this mean that searx.me is an official instance?
Computerly logic.

- Are there any other semi-official searx instances?

**Comment by aurora-potter** [comment]
@asciimoo
> It receives instant updates, because I update it instantly =)
So it's owned by you, a developer of searx. So it's an official instance.
> Why would this mean that searx.me is an official instance?
It has to do with Logic.

- Are there any other semi-official searx instances?

**Comment by aurora-anon** [comment]
@asciimoo
It receives instant updates, so it's owned by you, a developer of searx, so it's an official instance.

- Are there any other semi-official searx instances?
