### ISSUE TITLE
Firefox Address Bar Search forwards to searx.me without searching

### ISSUE THREAD

**Issue by holymio** [searx/searx#1267]
Sometimes my search text is ignored and it just forwards to the serx.me homepage. Happens every day  once or twice but I can not reproduce it. Using Firefox 59.0.2 for Windows 10 and installed the searx.me search plugin from the about page.

**Comment by aurora-potter** [comment]
@holymio
- Update Firefox for Windows to the latest version.
# Remove the searx extension and manually add searx as a search engine
Read <a href="https://support.mozilla.org/en-US/kb/add-or-remove-search-engine-firefox">this</a> and <a href="https://www.maketecheasier.com/firefox-search-engines/">this</a> for more information.
# If you're using <a href="https://addons.mozilla.org/en-US/firefox/addon/procon-latte/">Procon Latte</a>, please fully whitelist the searx's domain name.
Please mention if the problem is solved.

**Comment by aurora-anon** [comment]
@holymio

- Update Firefox for Windows to the latest version.
- Remove the searx extension and manually add searx as a search engine.

Read <a href="https://www.maketecheasier.com/firefox-search-engines/">this</a> and <a href="https://support.mozilla.org/en-US/kb/add-or-remove-search-engine-firefox">this</a> for more information.

- If you're using <a href="https://addons.mozilla.org/en-US/firefox/addon/procon-latte/">Procon Latte</a>, please fully whitelist the searx's domain name.

Please mention if the problem is solved.

**Comment by aurora-anon** [comment]
@holymio I should also mention that the Searx's Firefox extension requires Javascript to be enabled. Check if it's coming from Javascript.

Anyway, I recommend you to  manually add searx as a search engine, as it doesn't require any extension.

**Comment by Pofilo** [comment]
@aurora-potter I also have the problem 4-5 times a week. My firefox is up-to-date and searx was added as a search engine (and I don't use Procon Latte).

This is not the source of the problem (even if I don't know where it comes from).

**Comment by holymio** [comment]
@aurora-potter can confirm what @Pofilo said. Freshly installed Firefox, went to searx.me. Clicked on the about page and clicked on install in "Install searx as a search engine on any version of Firefox! (javascript required)". Installation went fine. Made searx.me default in Firefox settings. Most of the times it works, but now and then you are just forwared to the searx.me page, where your entered search text is lost.

**Comment by asciimoo** [comment]
Searx has two search endpoints (`/` and `/search`) because chrome/chromium does not allow to send POST requests to the default search URL. Perhaps this is a similar issue. Try to add `https://yourinstance.com/search` manually instead of `https://yourinstance.com/` as default search engine. Does this solve the problem?

**Comment by Pofilo** [comment]
After a few days, it doesn't change anything. It still happens once a day at maximum (on 2 PCs - _Windows 10 - Firefox 59.0.2_).

**Comment by oplixir** [comment]
I've been having this issue as well, but it looks to be a regression in Firefox (https://bugzilla.mozilla.org/show_bug.cgi?id=1435615). The workaround of setting `browser.newtab.preload` to `true` works for me.

**Comment by ShellCode33** [comment]
All you have to do is to use GET method instead of POST (you can change that in the preferences of searx). I personally had to remove searx from Firefox's search engines and add it again, but it worked like a charm !

**Comment by catvec** [comment]
This extension breaks entirely when using Firefox containers.

**Comment by bjesus** [comment]
Any solution to this?

I'm seeing the same behivor with Firefox Container Tabs. I've set searx to automatically open in a specific container, but every single search I type to the address bar just brings me to a fresh searx homepage and I need to re-search it.

**Comment by ewdissi** [comment]
> 
> 
> Any solution to this?
> 
> I'm seeing the same behivor with Firefox Container Tabs. I've set searx to automatically open in a specific container, but every single search I type to the address bar just brings me to a fresh searx homepage and I need to re-search it.

I've the same problem :( tryed everything in this discussion without a solution

**Comment by n8v8R** [comment]
In comparison to other FF search engines there are some differences in implementation, perhaps being significant of why it does not work in containers (which has been driving me bonkers really).

|       code         | other search egine         | searx                       |
|----------------|----------------------------|-----------------------------|
| _loadPath:     | jar:[app]/omni.ja!/ddg.xml | [https]searx.me/searxme.xml |
| __searchForm": | null                       | https://searx.me            |
| rels:          | ["searchform"]             | []                          |

**Comment by ghost** [comment]
What fixed it for me was to delete `"method": "POST",` from `search.json.mozlz4` (located in the user profile folder).

Since then it is working as expected in containers :sweat_smile:

**Comment by aliceinwire** [comment]
not work on firefox for android 66.0.2

**Comment by aliceinwire** [comment]
@asciimoo firefox on android cannot edit endpoint

**Comment by asciimoo** [comment]
Using POST requests from the URL bar is kind of grey area in browsers. Chrom* doesn't support it at all (no idea why), perhaps this is the case with mobile browsers too. Try to add searx using GET requests by changing it in preferences or adding the url manually like https://searx.me/search?q=%s .

**Comment by aliceinwire** [comment]
@asciimoo changing the setting to GET and re-adding the site did the trick

**Comment by p-rintz** [comment]
I had the same problem with containers and the search not working through the toolbar.
Either I did the adding wrong or most suggestions didnt work for me.
What did work was adding a custom search engine as mentioned by @asciimoo with the help of: https://ready.to/search/en/#

> Using POST requests from the URL bar is kind of grey area in browsers. Chrom* doesn't support it at all (no idea why), perhaps this is the case with mobile browsers too. Try to add searx using GET requests by changing it in preferences or adding the url manually like https://searx.me/search?q=%s .

**Comment by Tealk** [comment]
I have the same problem, I can add the search but the input is not transferred.
Firefox does not offer the possibility to edit the URL by hand.
Newest Firefox 72.0.2
Windows 10 1909

**Comment by Tealk** [comment]
I use Temporary Containeres and this seems to be a problem with submitting the search, strangely enough only on searx, other search engines don't have any problems.

If I enter the domain from the searx instance at "Advanced -> Ignoring requests to", the default container will open and the search works.

**Comment by return42** [comment]
@Tealk can you test this behaviour on https://darmarit.cloud/searx/ and report your experience / Thanks!  .. https://darmarit.cloud/searx/ runs current master without changed any default.

**Comment by Tealk** [comment]
@return42 i have already tried it on a separate instance running on the master branch.

**Comment by aayio** [comment]
> What did work was adding a custom search engine as mentioned by @asciimoo with the help of: https://ready.to/search/en/#

This worked for me. [Here is my ready.to config](http://ready.to/search/en/?sna=PrivateNet%20Searx&prf=https%3A%2F%2Fsearx.privatenet.cf%2F%3Fq%3D&in=utf&ou=ono&mod=pn). I am using Temporary Containers but I have my searx domain under a 'Trusted' Multi-Account Container so my search settings are saved.

Now I have the desired behaviour of a new toolbar search (in a temporary container or otherwise) successfully executing a searx search.

Didn't need to switch to GET, tweak Temporary Containers settings, or do any other of the workarounds mentioned above.

So I guess there's some quirk about Firefox's in-built way of adding custom search engines that messes with tabs being re-opened in the specified container (and thus losing the search query).

**Comment by etherb0x** [comment]
@mauvity This just started happening to me earlier today. I also use multi-account containers and have since created a persistent "Trusted" container for search.privacytools.io, but the issue persists. Moreover, clicking the "OpenSearch plug-in PrivateNet Searx" link on that page doesn't prompt anything, even with all scripts enabled. Any tips on getting a Ready2Search plugin added to Firefox?

**Comment by csolisr** [comment]
I'm naving a similar issue specifically with Firefox for Android, when selecting it as the default search site and selecting text to "Search on Searx". The tab directs me to the landing page, losing the searched text, instead of performing the search proper. Searching from the address bar gives no issues, and the autocompletion works as well. Searching directly from the landing page works as well but, as I said, the selected text is lost and needs to be manually copied over to the toolbar.

**Comment by asciimoo** [comment]
@csolisr this sounds quite similar to what chrome does. It doesn't allow to perform POST requests from the url bar. Could you try to set `GET` method in preferences then remove/add searx as a default search engine to validate my theory?

**Comment by msafadieh** [comment]
I think this was resolved with #2130. Firefox containers don't support `POST` and FF does not attach the cookies when requesting `/opensearch.xml`. If anything, this is a bug on Mozilla's end.

**Comment by unixfox** [comment]
Is this issue still reproducible with the latest version?

**Comment by unixfox** [comment]
I'm closing this issue because according to @msafadieh it seems to be solved. If someone still experiences the issue feel free to write a comment here.
