### ISSUE TITLE
URL problem with http://stats.searx.oe5tpo.com/

### ISSUE THREAD

**Issue by prolibre** [searx/searx#1274]
It has been at least 2 months since I changed the url of my searx service because of too many robots (most often Russian).

My URL still appears on http://stats.searx.oe5tpo.com/

Could you delete **https://www.heraut.eu/search/** (in "public searx Instances" : stats.searx.oe5tpo.com) please. I still have robot requests on this address.

**Comment by Pofilo** [comment]
I don't know who is the owner of [http://stats.searx.oe5tpo.com/](http://stats.searx.oe5tpo.com/) nor how/how often the list is updated.
I think the list came from [https://github.com/asciimoo/searx/wiki/Searx-instances](https://github.com/asciimoo/searx/wiki/Searx-instances) but has never been updated since (or long time ago).

It looks like stats come from [https://github.com/dalf/searx-stats2](https://github.com/dalf/searx-stats2) and your instance appears in [https://github.com/dalf/searx-stats2/blob/master/instances.json](https://github.com/dalf/searx-stats2/blob/master/instances.json).

Maybe the owner of  [http://stats.searx.oe5tpo.com/](http://stats.searx.oe5tpo.com/) is @dalf, maybe not ! We should wait for his answer and see if I'm totally wrong or partially right ^^

**Comment by pointhi** [comment]
well, that's my site :)

Repo can be found here: https://github.com/pointhi/searx_stats

I did not update the list quite some time and left old instances intentionally in there (probably they reappear, and to count the complete number of instances made). I will remove it later today, like you requested.

**Comment by prolibre** [comment]
merci / thanks @pointhi

**Comment by dalf** [comment]
https://github.com/dalf/searx-stats2 is not deployed because it is in an unstable state. 

There is https://stats.searx.xyz/ too but I don't know where the source is.

Side note : I was thinking about a peer to peer protocol embedded into searx to share the instance list, see https://github.com/asciimoo/searx/issues/1113#issuecomment-352703816
