### ISSUE TITLE
limiting number of results in API call

### ISSUE THREAD

**Issue by Outstep** [searx/searx#1276]
Hello,

I have been experimenting with SearX API calls and have a question.

In a simple (example) API call I can easily do:

curl "http://localhost:8888/?q=solar%20panels&categories=general&format=json&lang=en&pageno=1"| python -m json.tool

for which the basic parameters are:

q=solar%20panels
categories=general
format=json
lang=en
pageno=1

which yields some reasonable results but it the "pageno" counterpart that I am wondering about.

I did not see a parameter to limit the number of results per page.

Is there some way to establish this via the API?

Thanks

**Comment by Outstep** [comment]
A follow on is that I have been looking at the SearX API information at:

https://asciimoo.github.io/searx/dev/search_api.html

**Comment by dalf** [comment]
Look at [fltron](https://github.com/asciimoo/filtron) : 
https://github.com/asciimoo/searx/issues/543#issuecomment-225305326

Step by step installation process written in German (not tested, maybe outdated) : 
https://scroom.de/eine-eigene-searx-instanz-unter-ubuntu-16-04-aufsetzen/

**Comment by Outstep** [comment]
Thanks, but that did not really answer the question.

I know that it can be adjusted in the configs, but was mainly wondering if
it can be also controlled within the API call, for example with a
"&rows=10" parameter addition to go with the "&pageno=1"

Or, perhaps something like ""&start=0&rows=10" for example in which you
tell it a starting number and then how many rows to take from that point.

Thanks

On Sat, Apr 21, 2018 at 1:49 PM, Alexandre Flament <notifications@github.com

**Comment by asciimoo** [comment]
@lonnieOST, the number of results depends on the services you use. E.g. wikipedia returns 1 result but google images 50 on a single search. Because the various result numbers the only way to achieve the mentioned functionality is storing a "session data" about your previous searches. Searx doesn't persist data on server side, so if you really need this feature, you have to develop this as a small layer between searx and your application.
