### ISSUE TITLE
google (unexpected crash: CAPTCHA required) 

### ISSUE THREAD

**Issue by gohanko** [searx/searx#1282]
Error! Engines cannot retrieve results.
google (unexpected crash: CAPTCHA required)
Please, try again later or find another searx instance.

This was the error that was returned when searching.

**Comment by Pofilo** [comment]
Duplicate, see:
https://github.com/asciimoo/searx/issues/1118
https://github.com/asciimoo/searx/issues/729
https://github.com/asciimoo/searx/issues/1089

You can close this one to avoid too much issues of the same issue.
And you should try the search function of Github to avoid duplicates !

Nevertheless, if reading one of the above issues give you an idea on how to fix the problem, you are welcome :)
I hope we'll find a solution ! I will make some researches this week-end (long one in France !).

**Comment by gohanko** [comment]
Thanks guys. I didnt know how to switch instance I thought it was all in one domain. I will close it

**Comment by gohanko** [comment]
@Pofilo why did you say its long?

**Comment by Pofilo** [comment]
Nah, you can install Searx wherever you want :)
You can find a list of instances here: [https://github.com/asciimoo/searx/wiki/Searx-instances](https://github.com/asciimoo/searx/wiki/Searx-instances).

_Long_ because tuesday is a public day, so a lot of people are taking their monday too ^^

@cosimone64 
> This seems therefore to be an issue specific to searx.me.

This is not true, some instances are working well, some others are not. You can read the issues I was talking before.

**Comment by gohanko** [comment]
Damn thats nice.
