### ISSUE TITLE
Advanced syntax for engines

### ISSUE THREAD

**Issue by dimqua** [searx/searx#1359]
It seems that so-called "advanced syntax" is not supported by searX even if you use the search engine that supports it by itself. Like [StartPage](https://www.startpage.com/eng/power-search-techniques.html), [Google](https://support.google.com/websearch/answer/2466433) and [Yandex](https://yandex.com/support/search/how-to-search/search-operators.html).

**Comment by asciimoo** [comment]
Searx forwards the search query to the remote engines, so if a remote engine like google supports advanced syntax, then searx supports it, too. Searx also has an own advanced syntax, where you can specify engines/categories/language: https://asciimoo.github.io/searx/user/search_syntax.html

**Comment by dimqua** [comment]
> if a remote engine like google supports advanced syntax, then searx supports it

@asciimoo then it doesn't work for me as excepted:

https://searx.me/?q=!sp+!go+tennis+AND+(football+OR+baseball)

In this example, the words **OR** and **AND** treated by searx as part of search query. Even if results are correct, searx should not highlight advanced syntax words in them.

**Comment by Songbird0** [comment]
Hi!
I reopen this issue because I'm encountering the same problem. [This syntax](https://searx.feneas.org/search?q=yh%20%3Fddg%20wikipedia&language=en&time_range=None&safesearch=0&categories=general) doesn't add more categories/engines to the query.

I want to add DuckDuckGo and Yahoo! to the following query: `?dgg ?yh wikipedia`

And... nothing happens. Do you have any idea?

cc @asciimoo @dimqua
