### ISSUE TITLE
Implement Perfect Forward Secrecy for search queries

### ISSUE THREAD

**Issue by ajvsol** [searx/searx#1391]
Another metasearch engine called [Search Encrypt](https://www.searchencrypt.com) claims to use Perfect Forward Secrecy to protect search query privacy:

>  What encryption methods does Search Encrypt use?
> All requests to Search Encrypt are done over SSL. We utilize the latest encryption technologies, including a feature known as Perfect Forward Secrecy which goes a step further than traditional SSL by using a unique public key for each individual session. This means that each user receives a unique public key which improves security considerably. We also encrypt the local queries using a client side encryption utilizing a short lived key which helps to protect browser history.

> After you’ve finished your searching, the encryption key for your search term expires so it is essentially gone forever.

If I understand this correctly then if someone were to unknowingly use a malicious Searx instance that logs requests to later sell to a 3rd party, if this were implemented they would no longer be able to decrypt these requests at a later date.

**Comment by dalf** [comment]
What Search Encrypt is describing is the connection between the browser and Search Encrypt servers.

[EDIT] Forward Secrecy add an additional layer of protection on HTTPS : if someone records the encrypted packets between your browser and Search Encrypt, cracking one connection doesn't help to crack the other connections. Forward secrecy doesn't prevent Search Encrypt to log all requests.

To compare, let's see the usual Searx setup :

```
Browser ---[ HTTPS ] --->{ Reverse Proxy ---> Searx }---[ HTTPS ] ---> duckduckgo / google / etc...
```
Reverse Proxy can be Apache, Nginx, haproxy, nghttp2, etc...

The forward secrecy configuration is up to administrator of the Searx instance (the reverse proxy configuration).

You can see the Qualys SSL Lab score for each Searx instance here : https://stats.searx.xyz/

Example with searx.xyz :
https://www.ssllabs.com/ssltest/analyze.html?d=searx.xyz
There is Forward Secrecy for all ciphers (In Cipher Suites section, there is "FS" for each cipher).
Of course doing so means searx.xyz is not available to old browsers.

About www.searchencrypt.com : 
https://www.ssllabs.com/ssltest/analyze.html?d=www.searchencrypt.com

Some cipher doesn't support Forward Secrecy.
Basically if you use a mordern Firefox / Chrome / Safari you will use Forward Secrecy, but you are not sure with old browser.

So either : 
* you are sure to use Forward Secrecy, if it is not possible you won't be able to access the web site (searx.xyz, searx.me, and some other Searx instances)
* you are most probably using Forward Secrecy if you are using a modern browser ( www.searchencrypt.com, google.com)

Another point is the encrypted search queries of SearchEncrypt : 
the search queries are encrypted using AES and a random key (see https://www.searchencrypt.com/js/search ) 
The AES parameters are stored in two differents cookies (EncKey and EncToken).
So the request is in clear on the wire as any other search engine ( eyedropper can't them since there is HTTPS ).

So why encrypting the search queries ?
* no browser history if the cookies are changed : require some tests, I don't know when the keys change, the cookies doesn't seems to expire.
* Search Encrypt server logs won't contains the query : most on the time logs contains the URL not the cookies. Not really helpful since Search Encrypt has the query anyway.

Searx solves this in different way : it uses the POST HTTP method. 
The URL remains the same, but the query is sent using the HTTP body of the request.

There is glitch about Searx : despite using the POST HTTP method, the HTML title contains the search query, that's mean the browser will contains the different search queries.
See https://github.com/asciimoo/searx/issues/1011 (issue solved with the simple theme).

Some other technical notes about SearchEncrypt :
* web server host by Amazon, running using Microsoft-IIS.
* HTTPS certificate issued by Amazon.
* The EncKey / EncToken cookies can be used as a user identifier (once again it depends when there are changed).

Moreover see the privacy notice of SearchEncrypt, section "What information we collect and how we collect it." : 
https://www.searchencrypt.com/legal/privacy

About Searx, if you are worried about Forward Secrecy from Searx to the different engines, see https://github.com/asciimoo/searx/pull/931 for some technical details.

To sum up it's about who you trust, what is the threat model / what are you afraid of ?

Side note : I don't know how SearchEncrypt provides results ? does it use another search engine ?

**Comment by ajvsol** [comment]
@dalf ah I see, thanks for your very comprehensive explanation! My takeaway is that SearchEncrypt is just using marketing jargon when in reality not all of their ciphers do have FS whereas Searx in contrast has FS for all of theirs.  

SE is a metasearch engine so it uses Google etc like Searx. 

The threat model I have is to limit the amount of information both the metasearch engine and the search engines themselves have about me. By using a metasearch engine anonymity can be gained compared to using the search engine directly, but then the metasearch engine has full info about the query.

I was mainly hoping for a some sort of E2E encryption for queries, so that the metasearch engine relays the queries and gets results but is at no point aware of what the query was.

**Comment by asciimoo** [comment]
> I was mainly hoping for a some sort of E2E encryption for queries, so that the metasearch engine relays the queries and gets results but is at no point aware of what the query was.

The point of searx is that it knows the search query and handles the interaction with search engines. 
Query encryption and forward secrecy isn't really an issue in case of searx, because it is a free software and anybody can use or host a trusted instance.
