### ISSUE TITLE
Add a new search engine

### ISSUE THREAD

**Issue by 2939293859** [searx/searx#1402]
How to add a new search engine?Are there any relevant documents?Thank you for developing and opening such an excellent program.

**Comment by WisdomCode** [comment]
I am no developer of this app, however, I meddled with this stuff and I've written a search engine into my config, so here comes an attempt to explain:

All the modification is done in the settings.yml, maybe known from the setup. Further down in this file, all the search engines are listed. You may extrapolate any information I may miss taking these as example values. Also, all of this takes image searches out of account, they are all made with custom engines, briefly mentioned below.

To add a new search engine, **Start a new line with a -** . 
**Every further value is added in this syntax: value type : value**
Now a list of value types:
**name**: Some name for your search engine, like reddit, google, wikipedia
**engine**: this is normally xpath, however, there are further options, I assume you choose xpath here
**paging**: In doubt, leave false, allows to search also page 2 etc. For this to work, the value {pageno} has to be given for the search_url (see below)
**search_url**: The url of the search, you have to firgure out how the url looks like if you search something. The part of the url that contains the search query has to be substituted with {query}, if you can search over multiple pages, the pagenumber has to be replaced with {pageno}
**url_xpath**: This is necessary if the engine is xpath. You leave here the xpath that will return all search result links (urls). To see what an xpath is/how it works, see https://www.w3schools.com/xml/xpath_intro.asp.
**title_xpath**: This is necessary if the engine is xpath. The same as url_xpath, however, instead of the result links, this returns the titles of the results.
**content_xpath**: The same as the above two, however, it returns the content (the short preview text most search engines provide).
**categories**: This presents in what categories you search. This may be general, files, music, news, videos etc.; you may add multiple, comma seperated ones to add to multiple searches. 
**timeout**: The maximum amount of time the search may take, otherwise this engine is ignored. You have to time how long the site takes to load and take this length here. Giving too much time may slow down the entire search. 
**shortcut**: A shortcut for your search engine, wikipedia may be wiki etc.

This is not entirely exhausted, there is also a kind of javascript engine that is used in some occasions, and you may even write a completely own python script for extracting the information instead of the xpath.
If you write such a script, just call your engine like your script (without the py). Such engines are found in the engines folder, you may work out how exactly they work there (and add it here if you want). However, most of the time, xpath will deliver everything of use from the html file.

**Comment by unixfox** [comment]
Answered here: https://github.com/searx/searx/issues/2171
