### ISSUE TITLE
Jive Search

### ISSUE THREAD

**Issue by dimqua** [searx/searx#1434]
Would be nice to add new search engine called [Jive Search](https://jivesearch.com/).

**Comment by ghost** [comment]
It's undocumented but our API will be faster than scraping: https://jivesearch.com/?q=bob+marley&o=json. The API will always have a generous free tier, btw.

**Comment by jfowl** [comment]
JSON API:
```
    search_url :`https://jivesearch.com/?q={query}&o=json&p={pageno}`
    paging: True
    results_query : documents
    url_query : id
    title_query : title
    content_query : description
```
@brentadamson Is this also a meta-search engine? I saw that you have yandex listed as a search provider.. I don't know how useful it would be to use jivesearch as a source then, because searx can also talk to yandex directly.

**Comment by ghost** [comment]
For right now it is. Eventually we'll have our own index but for right now we use Yandex.

**Comment by dimqua** [comment]
> searx can also talk to yandex directly.

The yandex engine do not work: #938.

**Comment by unixfox** [comment]
The website https://jivesearch.com doesn't respond anymore and the project seems inactive: https://github.com/jivesearch/jivesearch/issues/122.

I'm closing this issue due to our limited amount of active developers but feel free to reopen this issue if you implemented an engine for jive search or that the website is back online.
