### ISSUE TITLE
anyonething.de uses Cloudflare

### ISSUE THREAD

**Issue by emanruse** [searx/searx#1440]
anyonething.de advertised on the List of public Searx instances as GDPR compliant uses Cloudflare, not Let's Encrypt, and by being behind CF proxies essentially violates the whole idea of privacy. Therefore it should be removed from the list.

**Comment by oskapt** [comment]
Cloudflare is the largest MitM proxy on the planet, and despite them saying that they don't look in the stream while they re-encrypt it, there's no proof that this is true. If they have unencrypted access to massive amounts of data as it traverses the Internet, there is _no_ chance that state actors aren't foaming at the mouth to get access to that data. 

Anything that uses Cloudflare should be banned, blacklisted, and boycotted.

**Comment by dimqua** [comment]
I've edited the wiki accordingly, thanks for raising this issue.

**Comment by Pofilo** [comment]
Thanks @dimqua.

**Comment by ghost** [comment]
anyonething.de is no longer a searx instance.  It is now a pastebin, apparently, and it still proxies through CloudFlare.  I have moved it to the bottom of the **Offline** section.  Since people find it useful to list offline instances, I think it's also useful to list the date things are noticed as being offline, so I added that for anyonething.de.

The original record simply wrote "(Cloudflare)".  I find this insufficient, as searx becomes more and more popular, lots of low-tech users will not know what that means.  So I changed it to: "(Warning: uses CloudFlare)" so that it's at least clear that it's an anti-feature.  It should probably go further and link over to an article elaborating on the problem with CF - but I didn't bother since it's offline.
