### ISSUE TITLE
Image search shows no images

### ISSUE THREAD

**Issue by c0d3z3r0** [searx/searx#1490]
![screenshot_2019-01-20_10-27-29](https://user-images.githubusercontent.com/6205797/51437408-3f110000-1c9e-11e9-882a-871b4e1ce1d1.png)

Searx version 0.15.0

**Comment by virtadpt** [comment]
I'm seeing something similar, only with PDFs.  I don't know if it's how I've got things set up (Searx as the front-end for a YaCy instance in intranet mode (which is working as expected when I interact with YaCy directly)), I've been trying to isolate the problem for the last couple of days.  Happens when I run the latest checkout (HEAD), tag 0.15.0, and tag 0.14.0.

**Comment by unixfox** [comment]
Instance issue. Please move to https://github.com/searx/searx/discussions/categories/public-searx-instances-report-a-bug if you still experience an issue with this instance.
