### ISSUE TITLE
Best option to track users?

### ISSUE THREAD

**Issue by masterzebra** [searx/searx#1492]
Hi im running a public instance with nginx

Whats is the best option to know how many people use the instance?

What option respect best the users privacity?

Thanks

**Comment by jfowl** [comment]
Nginx does create some  logs on its own with the default settings. If you search for nginx log analizers you might find one.

**Comment by masterzebra** [comment]
Hi @jfowl, any suggestion? I have never done before, and i just want to know how many people use my instance? Thx :)

**Comment by jfowl** [comment]
No, sorry. Maybe google for "nginx log extract number of unique ips" or something along that line.

**Comment by xinomilo** [comment]
you could use https://github.com/matomo-org/matomo-log-analytics for importing raw web server logs to matomo. requires a matomo instance also (mysql/php). if you do go with matomo, make sure to turn on anonymization settings, for better user privacy.
generally speaking, i wouldn't use a public instance that logs queries/users.
just my 2c :)

**Comment by masterzebra** [comment]
Hi @xinomilo, thank u soo much for ur help
Im going to try it

Im thinking that i use Filtron and maybe there are any command to do this inside Filtron

**Comment by marathone** [comment]
Isn't the point of users wanting to use a searx instance, the fact that
no tracking is done? In fact my instance of searx states explicit that
tracking  isn't done.

**Comment by masterzebra** [comment]
Hi @marathone, maybe i explain me wrong, im not native english speaker

I dont want track users or any info, i just want know how many people use my instance, without any user information

**Comment by ghost** [comment]
The only way to track users would be to enable logging in uwsgi or on your web server. If you have filtron then uwsgi won't give you much data but it'll give you the number of hits making it to searx. If you look at your web server's logs then it'll give you all hits including bots, spiders, scripts which could be useful for blocking abuse but none of this can be done without enabling logs. the /stats page built into searx gives you an idea that your searx instance is actually being used (if the numbers change) but it doesn't necessarily keep a tally of total hits or unique visitors (you would have to track IPs for unique visitors).

If you want to look at nginx logs or your webserver logs goaccess works ok. At the very least to give you an idea of whats hitting your web server so that you can adjust filtron, etc., with the intention of improving the quality of your service. I wouldn't recommend leaving logs on for long though (merely for troubleshooting) and then flushing them as soon as you're done.

**Comment by unixfox** [comment]
Hello you may consider fathom: https://usefathom.com/
It doesn't store any personal information so you can still view how many people are using your instance without collecting specific personal information and because of that your instance will still be GDPR compliant without doing nothing more than installing the software.

You will need to modify the source code of searx or modifying the html on the fly with for example the [filter plugin](https://caddyserver.com/docs/http.filter) of caddy.
