### ISSUE TITLE
Image engine cannot retrieve results for Google and Bing

### ISSUE THREAD

**Issue by wonnetz** [searx/searx#1496]
Searching for images with the Google and Bing image search engine results in this error.

Engines cannot retrieve results:
google images (unexpected crash: line 41: htmlParseEntityRef: expecting ';'), bing images (unexpected crash: expected string or buffer), 500px (unexpected crash: 'photos')

**Comment by Ardakilic** [comment]
I've the same issue, current git master:

> google images (unexpected crash: line 1079: htmlParseEntityRef: expecting ';' (line 1079))

Sometimes I also get this:

> google images (unexpected crash: line 30: Tag footer invalid (line 30))

And after all, I can't see any results from Google images.

**Comment by kvch** [comment]
500px engine was removed from searx a few months ago: https://github.com/asciimoo/searx/issues/1338#issuecomment-414126635
Their API is no longer accessible: https://support.500px.com/hc/en-us/articles/360002435653-API-

I was not able to reproduce the issues you have seen with Bing images and Google images. In case of Google I get a different exception. Could you please share an example search query which lead to this issue? Also, what's the version of the instance you are using?

**Comment by Ardakilic** [comment]
@kvch 

For example. Search for _tremolo_ , and click images. I see this issue, but this is in every search result for me. I'm using the latest git master as of now, on my self-hosted server.

**Comment by wonnetz** [comment]
@kvch 
I switched to a different instance which is on version 0.15.0 and Bing Images is working, but Google Images is not working.

This is the new error I am getting: 
![screenshot from](https://user-images.githubusercontent.com/18079493/51789393-6bbd8f80-2156-11e9-80e9-df75c4ec2e8b.png)

**Comment by ghost** [comment]
I'm using the instance bin.disroot.org and I'm getting this notice:

`Engines cannot retrieve results:
google images (unexpected crash: No JSON object could be decoded), bing images (unexpected crash: expected string or buffer), 500px (unexpected crash: 'photos') `

**Comment by its3ch0** [comment]
> I'm using the instance bin.disroot.org and I'm getting this notice:
> 
> `Engines cannot retrieve results: google images (unexpected crash: No JSON object could be decoded), bing images (unexpected crash: expected string or buffer), 500px (unexpected crash: 'photos') `

On another instance I get this:

`Error! Engines cannot retrieve results:

google images (unexpected crash: line 921: Tag nav invalid (line 921))`

**Comment by xinomilo** [comment]
i'm having similar issues in image search (google images only), since 0.15.0 upgrade. changed themes/languages, no difference.  (instance: search.stinpriza.org )
error message in each image search (line number is different in each refresh/search, but always same error message) : 
`google images (unexpected crash: line 476: htmlParseEntityRef: expecting ';' (line 476)) `

uwsgi log:

> ERROR:searx.search:engine google images : exception : line 476: htmlParseEntityRef: expecting ';' (line 476)
> Traceback (most recent call last):
>   File "/path/to/searx/search.py", line 104, in search_one_request_safe
>     search_results = search_one_request(engine, query, request_params)
>   File "/path/to/searx/search.py", line 87, in search_one_request
>     return engine.response(response)
>   File "/path/to/searx/engines/google_images.py", line 68, in response
>     dom = html.fromstring(resp.text)
>   File "/path/to/searx-ve/local/lib/python2.7/site-packages/lxml/html/__init__.py", line 876, in fromstring
>     doc = document_fromstring(html, parser=parser, base_url=base_url, **kw)
>   File "/path/to/searx-ve/local/lib/python2.7/site-packages/lxml/html/__init__.py", line 762, in document_fromstring
>     value = etree.fromstring(html, parser, **kw)
>   File "src/lxml/etree.pyx", line 3213, in lxml.etree.fromstring
>   File "src/lxml/parser.pxi", line 1877, in lxml.etree._parseMemoryDocument
>   File "src/lxml/parser.pxi", line 1758, in lxml.etree._parseDoc
>   File "src/lxml/parser.pxi", line 1068, in lxml.etree._BaseParser._parseUnicodeDoc
>   File "src/lxml/parser.pxi", line 601, in lxml.etree._ParserContext._handleParseResultDoc
>   File "src/lxml/parser.pxi", line 711, in lxml.etree._handleParseResult
>   File "src/lxml/parser.pxi", line 649, in lxml.etree._raiseParseError
> XMLSyntaxError: line 476: htmlParseEntityRef: expecting ';' (line 476)
> 

another error, not so frequent (line number is also sometimes different): 
`google images (unexpected crash: line 26: Tag footer invalid (line 26)) `

uwsgi log : 

> ERROR:searx.search:engine google images : exception : line 26: Tag footer invalid (line 26)
> Traceback (most recent call last):
>   File "/path/to/searx/search.py", line 104, in search_one_request_safe
>     search_results = search_one_request(engine, query, request_params)
>   File "/path/to/searx/search.py", line 87, in search_one_request
>     return engine.response(response)
>   File "/path/to/searx/engines/google_images.py", line 68, in response
>     dom = html.fromstring(resp.text)
>   File "/path/to/searx-ve/local/lib/python2.7/site-packages/lxml/html/__init__.py", line 876, in fromstring
>     doc = document_fromstring(html, parser=parser, base_url=base_url, **kw)
>   File "/path/to/searx-ve/local/lib/python2.7/site-packages/lxml/html/__init__.py", line 762, in document_fromstring
>     value = etree.fromstring(html, parser, **kw)
>   File "src/lxml/etree.pyx", line 3213, in lxml.etree.fromstring
>   File "src/lxml/parser.pxi", line 1877, in lxml.etree._parseMemoryDocument
>   File "src/lxml/parser.pxi", line 1758, in lxml.etree._parseDoc
>   File "src/lxml/parser.pxi", line 1068, in lxml.etree._BaseParser._parseUnicodeDoc
>   File "src/lxml/parser.pxi", line 601, in lxml.etree._ParserContext._handleParseResultDoc
>   File "src/lxml/parser.pxi", line 711, in lxml.etree._handleParseResult
>   File "src/lxml/parser.pxi", line 649, in lxml.etree._raiseParseError
> XMLSyntaxError: line 26: Tag footer invalid (line 26)
> 
>

**Comment by cubiq** [comment]
has this been acknowledged?
I'm having the same issues since 0.15.0
I get various error messages like:

```Engines cannot retrieve results:
google images (unexpected crash: line 51: Tag wbr invalid (line 51))
```

```Engines cannot retrieve results:
google images (unexpected crash: line 39: htmlParseEntityRef: expecting ';' (line 39))
```

```Engines cannot retrieve results:
google images (unexpected crash: line 32: Tag footer invalid (line 32))
```

**Comment by ghost** [comment]
I'm getting the same messages on my instance using Qwant image and Google image search, works fine using Unsplash so it seems to be something specific with those engines.

**Comment by nfk** [comment]
Hi,

On spot project (fork of searx) we are impacted by that issue about google image engine. After some investigations it is related by how google builds the page. First it returns a minimal information, then with async js request it fills the page with the whole information. With python request we get an http 200 with the minimal html page. If we want to fix that we have to delegate the load of the page in an headless browser so it requires to rework the engine to use request or selenium webdriver following the engine requirement.

However I have a partial [fix](https://gitlab.e.foundation/e/cloud/my-spot/commit/5904dcb1c455005128410f762002453ef7e5785f) in progress which fetches the thumbnail, the title and the link of the image page, partial fix because I am not able to get the link of the image and I need to perform some tests.

**Comment by Yetangitu** [comment]
The culprit here is not `ijn` but `asearch` as well as the fact that Google does not return pure JSON as expected by the current iteration of this engine but JSON embedded in some HTML. I submitted a PR to fix these issues, these changes make Google Image search work for me: #1566 

I just noticed there is another PR to fix the google_images engine, IMnsHO that PR leads to worse results as it does not use the JSON data returned by Google.

**Comment by return42** [comment]
I can verify, that the google_images.py [xpath query](https://github.com/asciimoo/searx/blob/6a3ef5561ba48e287f0b9c03a0b6d2f13b703077/searx/engines/google_images.py#L69) no longer works.

**Comment by unixfox** [comment]
I confirm too that Google images is no longer working on Searx.

**Comment by return42** [comment]
> I confirm too that Google images is no longer working on Searx.

That's what I mean ;)

**Comment by return42** [comment]
FYI: #1985 is a revise of the google engines, the PR is also merged into the [searx-next branch](https://github.com/return42/searx/tree/searx-next)

- [searx-next instance](https://darmarit.org/searx)
- [searx-next docs](https://return42.github.io/searx/)
- [searx-next merged PRs](https://github.com/return42/searx/projects/1)

**Comment by unixfox** [comment]
@asciimoo For Google images engine, I can't reproduce the issue since the commit https://github.com/asciimoo/searx/commit/9f5cd28dba3c923ade7e482615611ac055c2918a and for Bing images engine I can't reproduce the bug anymore.

I tested that on a local Searx instance.

I think this issue can be safely closed.

**Comment by cloo** [comment]
I'm having this issue in 1.0.0, served through yunohost. 
![211114-132142](https://user-images.githubusercontent.com/651760/141679115-63838790-50c1-4a25-ba5b-be15036faa0e.png)
@mikeri need to be reopened, or is this a different bug?
