### ISSUE TITLE
when I click from searx result list which marked google, does this click actually from google or just from searx instance self?

### ISSUE THREAD

**Issue by ghost** [searx/searx#1509]

**Comment by juanfra684** [comment]
If you're asking what the web owner see as your origin, search "what is my referer" in searx and click in "www.whatismyreferer.com". That web will show you what is your browser sending to the web owner when using searx.

Otherwise, if you want to know if google knows that you're searching something or using results from google, then no, they don't know.

**Comment by dalf** [comment]
Thank you @juanfra684
