### ISSUE TITLE
As of today, absolutely no instances search videos

### ISSUE THREAD

**Issue by PFCS1976** [searx/searx#1529]
This has happened many times in recent weeks - all or most video searches are blocked on every single searx instance.

**Comment by aleex5** [comment]
there are some search engines that no longer work correctly, just as there are some search engines that do not work with certain languages, they should improve that

**Comment by ghost** [comment]
Searx.me's video search seems to be working fine which would likely mean that the Searx video search is working fine. 

If individual instances of Searx decide to turn off video searching then it's not really for Searx to fix? 

I can see why an instance would potentially give preference to text searches over video or image searches. Getting a Google captcha on your text searches could impact a lot more users if the reason is that someone is hammering away at the image search or video search. Not all engines are friendly to Searx.

**Comment by aleex5** [comment]
of all the search options that are in "searx", those of videos are the worst, the results are very bad

**Comment by ghost** [comment]
@aleex5 If you have issues with the quality of search results it's not exactly the same thing that the OP is mentioning. I would suggest creating your own issues with specific details so that others can try to reproduce it. 

For your language issue, what languages are you using? What search engines are having problems? Is it all of them? Only a few? Does it work with any of them (even just 1)? Which one? Is it specific to those running 0.14.0 or only those running 0.15.0?

For your Searx video results being the worst it doesn't give us much to go on. Could you pick a topic, try a search on searx (give us the engines and instance you're using), give us another website where it works (youtube?), what results are you expecting to get and what results are you actually getting?

**Comment by ghost** [comment]
@PFCS1976 do you have specifics we can try to test with? What are some of the instances you're using, what engines are enabled under preferences for video search? Can you pick a topic that has the issue and share it so we can test? When you say blocked do you get a blocked message (what's the specific message) or is it just that they aren't enabled by default under the preferences tab?

**Comment by aleex5** [comment]
@MAL-1 
I use the Spanish language, I use the searx.site page, although I have tried the other pages, mostly with version 0.15.0 and I have all had the same result.

I only use 4 searx search options, they are general, images, news, videos
and I realize that when looking for news and videos they give quite mediocre results
in news 99% of the time it does not give me results of what I'm looking for
in videos the problem is the search engines, they are quite bad, just like the news
In addition, the search engines of Google, YouTube do not work

**Comment by dalf** [comment]
On searx.site instance, I get results from dailymotion, vimeo (I don't count the torrent results).
The PR #1544 fixes the YouTube engine.

**Comment by unixfox** [comment]
@dalf this issue can be closed now that #1544 has been merged.
