### ISSUE TITLE
Respect privacy using google captcha?

### ISSUE THREAD

**Issue by kamov** [searx/searx#1570]
I just try today your search engine, but it not worked.

Appear error:

> Error! Engines cannot retrieve results.
> 
> google (unexpected crash: CAPTCHA required)
> 
> Please, try again later or find another searx instance.

However, you are using google captcha? How you can promise privacy by using google captcha?

**Comment by dalf** [comment]
Searx doesn't resolve google captcha and that's the problem.

More detail :
```
👤 [ your browser ] ---> [ searx ] ---> [ google server ]
```

google never sees your browser (nor your IP address, nor your cookies).

From google point of view it's easy to guess that the HTTPS requests made by Searx doesn't come from a real browser. That's why Google starts to ask to resolve Captcha, and since Searx doesn't resolve Captcha it confirms even more to Google that Searx is not an human.

You can check by yourself the code : 
https://github.com/asciimoo/searx/blob/master/searx/engines/google.py

Note : when you use a existing Searx instance you trust the administrator of that instance.

See #729
