### ISSUE TITLE
Embedded video and embedded maps don't work

### ISSUE THREAD

**Issue by ghost** [searx/searx#1572]
If I go to search.privacytools.io and use either the map search with photon or openstreetmap the show map button doesn't show the map. If I do this on searx.me or searx.info it works as expected.

The same issue for video searches and the show video button using Youtube, Vimeo and DailyMotion, the built in player doesn't load anything on search.privacytools.io but it works fine on searx.me or searx.info.

Any idea what the requirements are to get it working on the instance? Is there anything in the HTTP header that prevents the embedding?

**Comment by dalf** [comment]
It's a problem of search.privacytools.io , you can contact them here : https://www.privacytools.io/contact/

Technically, the cause is this HTTP header (configured by search.privacytools.io ): 
```
content-security-policy: default-src 'self'; base-uri 'self'; script-src 'self' 'unsafe-inline' 'sha256-2XPtiIriLCRC9BnusBjoTHsfh5zn7F+h7Cr17XwSN50=' 'sha256-44qpLIQFGWIyr5WMMdidaxGZNjAeoKaDAKDPBQdLM4Y=' https://stats.privacytools.io; img-src https://*.privacytools.io data:; frame-ancestors 'self'; object-src 'none';
```

External resources can't be loaded, so no map tiles, no videos.

----

According to https://search.privacytools.io/about  : 
> Searx is a metasearch engine, aggregating the results of other search engines while not storing information about its users. 

As it is written in Searx source code.
At the bottom of the front page, the link "Privacy policy" goes to a 404 page.

However, this instance uses [Matomo, formely piwik](https://matomo.org) with click tracking, so I don't recommend this instance.

Technical details, source code of the front page : 

```html
   <script type="text/javascript">
      var _paq = window._paq || [];
      /* tracker methods like "setCustomDimension" should be called before "trackPageView" */
      _paq.push(['trackPageView']);
      _paq.push(['enableLinkTracking']);
      (function() {
        var u="https://stats.privacytools.io/";
        _paq.push(['setTrackerUrl', u+'matomo.php']);
        _paq.push(['setSiteId', '2']);
        var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
        g.type='text/javascript'; g.async=true; g.defer=true; g.src=u+'matomo.js'; s.parentNode.insertBefore(g,s);
      })();
    </script>
    <noscript><p><img src="https://stats.privacytools.io/matomo.php?idsite=2&amp;rec=1" style="border:0;" alt="" /></p></noscript>
```

According to https://developer.matomo.org/api-reference/tracking-javascript : 
> enableLinkTracking( enable ) - Install link tracking on all applicable link elements. Set the enable parameter to true to use pseudo click-handler (treat middle click and open contextmenu as left click). A right click (or any click that opens the context menu) on a link will be tracked as clicked even if "Open in new tab" is not selected. If "false" (default), nothing will be tracked on open context menu or middle click.

It seems Motomo has been updated but not the sha1 in the content-security-policy HTTP header, so the browser block the loading of  script (or image if javascript is disabled).
