### ISSUE TITLE
[Bug/Issue] Unable to Retrieve Results

### ISSUE THREAD

**Issue by asddsaz** [searx/searx#1586]
**Issue/Bug**: Service is DOWN
**Proof**:
Here is me looking up a popular phrase, "is this site down":
https://archive.fo/vJW9d
https://web.archive.org/web/20190509184840/https://searx.me/?q=is%20this%20site%20down&categories=general&language=en-US

It appears to work only on certain instances: have the same problem across other instances:
Like privacytools.io seems to work:
http://archive.is/wr7Cs
https://web.archive.org/web/20190509185141/https://search.privacytools.io/?q=is%20this%20site%20down&categories=general&language=en-US

But other instances have the same issue:
http://archive.is/lIMra
https://web.archive.org/web/20190509185207/https://searchx.mobi/?q=Is%20site%20down&categories=general&language=en-US

It also has varying degrees of problems like if I look up Wikipedia:
http://archive.is/nN6sy
https://web.archive.org/web/20190509185423/https://searx.me/?q=wikipedia&categories=general&language=en-US

**Error Message**:

> Error! Engines cannot retrieve results.
> google (unexpected crash: CAPTCHA required)
> Please, try again later or find another searx instance.

__________

Want to support this issue? Post a [bounty on it](https://www.bountysource.com/issues/73938183-bug-issue-unable-to-retrieve-results)! We accept bounties via [BountySource](https://www.wikipedia.org/wiki/Bountysource).

**Comment by ghost** [comment]
This is **not** an issue specific to this keyword, but rather to how many searches are being done on public instances. Public instances will inevitably get more traffic and higher chance of getting a captcha as a result.

**Comment by pwn0r** [comment]
just my two eurocents :) 
searx.me became completely unusable here like a month ago, at the very least. All google results require captcha which is obviously does not work. 

As for others linked there like search.privatytools.io, by default they only use DDG it seems. 
And when you manually enable google it gets the same error. 

In my opinion using google thru public instances of searx is no longer possible. Pretty much screwed here I guess :)

**Comment by unixfox** [comment]
@pwn0r Not if you try very hard to combat against bots.
I had this captcha issue with Google on my instance: https://searx.be
But I found some ways to block most of the bots and now it's working fine by having Google by default, my instance is pretty much never blocked by Google.

**Comment by ghost** [comment]
I'm not able to search ANYTHING with searx.me after I selected my preferences. Every search gives me search error. I disabled everything that had showed captcha error and I selected all tabs right from general to videos. I'm glad to provide further details about my preferences if you want
![Screenshot from 2019-05-18 21-35-27](https://user-images.githubusercontent.com/45126275/57972360-d705c880-79b6-11e9-8a86-7c5ebfc63a12.png)

**Comment by atomGit** [comment]
i'm seeing the same thing on all of the pub instance i've tested - if i enable only Startpage or only Quant, for example, no results are returned even for generic searches like 'cat'

DDG returns results

i don't know if this is due to blacklisted IPs or what, but it makes many of the pub instances useless unfortunately

**Comment by return42** [comment]
About your CAPTCHA errors: This is 99% due to the fact that bots overwhelm your instance with requests and these requests in form and frequency lead to your instance being blocked by Google.  If you place your instance public to the internet you should really consider to install a filtron reverse proxy and for privacy a result proxy is mandatory.

Please use our new installation instruction, which also install a bot blocker (filtron).

Closed by PR #1803 / see docs at: https://asciimoo.github.io/searx/admin/installation.html
