### ISSUE TITLE
Question about tracking/profiling on private instances

### ISSUE THREAD

**Issue by dm17** [searx/searx#1592]
Of course the private instance of searx will not track or profile, but won't the various search engines it is polling from start profiling that private searx instance? Thoughts on this aspect of running a private instance? The more people who use it, the more obfuscated each person using it is, right? If one person uses a searx instance, then it kind of functions as a proxy... How do you think about the way search engines will profile private searx instances?

**Comment by unixfox** [comment]
I'm pretty sure they won't profile based on only the IP (that's pretty much only what search engines receive from the search instance) because that's not accurate enough.
Most of the search engines profile based on a cookie because cookies are associated to a browser and doesn't change in case of an IP change (very frequent on home internet connection with dynamic IP).
They won't introduce a new profiling mechanism just because only 0.0001% of their users are searching trough a proxy (like Searx).

**Comment by kvch** [comment]
There is a post on private instances in the blog of searx: https://asciimoo.github.io/searx/user/own-instance.html
