### ISSUE TITLE
Search's are failing often with no results

### ISSUE THREAD

**Issue by Ryonez** [searx/searx#1607]
Lately I've been required to search for something more that once, with results first returning:
> Sorry! we didn't find any results. Please use another query or search in more categories.

![image](https://user-images.githubusercontent.com/16157130/58432690-c5839580-8107-11e9-88a8-f7d477c32542.png)

After telling it to search again (Sometimes taking several attempts), it'll finally work:

![image](https://user-images.githubusercontent.com/16157130/58432732-fb287e80-8107-11e9-9617-015745f734de.png)

From what I can gather so far is that searx is trying to respond to the user, before it even gets search results. I'd much rather wait an extra second or two, if it means I'll actually get results.

This is happening often enough it's majorly impacting usability.

Using [Wonderfall/docker-searx](https://github.com/Wonderfall/docker-searx), issue started appearing the last couple of weeks.

**Comment by unixfox** [comment]
Is Google enabled in your preferences? If not can you post a screenshot of your preferences of the global category?

**Comment by Ryonez** [comment]
Yup, google is enabled.

**Comment by unixfox** [comment]
Your issue might be related to that issue: #1596.
If you are familiar with git you could try my pull request here: https://github.com/asciimoo/searx/pull/1597

**Comment by Ryonez** [comment]
Related possibly, but not the only issue. As you can see in the first screenshot, it's not just google.

Also using a docker image. I can't just switch the code in it easily.

**Comment by silvernode** [comment]
> Related possibly, but not the only issue. As you can see in the first screenshot, it's not just google.
> 
> Also using a docker image. I can't just switch the code in it easily.

I had the same thing happen with Google enabled. It would prevent all results from appearing. Once I disabled Google in the web engine and Google Images in the image engine, things started working again. 

Here is my Saved preferences URL that you can add to your preferences (make sure to change the domain):

<details>
<summary>Details</summary>

https://sitename.tld/?preferences=eJx1VU2P2zgM_TX1xcii3R725MOiRbEFFpiime5VoCXa5loWXUlOxv31pTL-kJv0EAemSL7HJ5L2GCYbg2KnHF5VhLr6BDZgYZiUx8D2gr4Kmk7dVP8Rr4UF107QYoXu9O1cWNZg00thKEBt0ajRTi25UP1Hw8lSj6rj2OMc3vz54WlEl7IKpLLk-g239nwN6BN-8vvsGnIUUQXt2do18m-tMQT18emzJLl6cShoEC5q9PwyL8Rhiqx5GC1GrFrm1mIRoMGA4HVXvS1ihwNWHDT4At2R8xltowSd_QCR2CUyzx50L9y-ff1XYAcWQcT6z_Pzl_NKQ97Pt_SpHg0RW_azCmhRx10YdIKBoepJ9yB1qIYsJoTGI5aBm3gFj6UhL2EpgaIopxeGqFRgTWDLAQ2BGMmBUhcyyCmBR2Po3mlyYbQQOkmUZEqer4KUYp5LGMeMxMfJiMSqRYcekuTvXrI4N0MO2FIrNUGIecDKQi40-Rhq65jFNMYzmR3wNeWGsKmyg2RchymQVur2J0czOIMvj8B3S4vYRxowLDq-4q0ZrtSTgQh5BOg28PQ7BnwhzOkZ0vEHO8wzBEQzojTLhjPw_8LjEcpW-R50d6GbzyLmqh3KvCQt96wNeOZNe0u1Bz-X6TxQyB211qd4ybBS39IFy6PbynKto6ZYTzIHcVGz8TK_BPqutx6Q2g0Y54GdjP7BDca-HMh79kvyyP3MkUPHPbidQwdSVXqsHKz0jM8YNB4GSLXj4jHMg0ysCBE9uGBlMs2jIldZWbaMx5GzsViEXynsd3Vs4_XtF-abyLJtnC9D9JOOk099JDsVnU6rw-CFwEXw8dAUPxwMh966Ugha9uT9OL--H6LTrWo2WKbHokaWIRvz9-__ejmMdrRQP76ItcptVm-ybFt0XXBGGiX9Wr5ntp_lJL5fRYDcMEN37JyQ9BnTss-MxrSlwdu3Ii3r7agYMHZsqi9P5-di2ccyvNV6fFv-pxBn-XRZbilpdDkZ8P1PBD-pVw==&q=%s

</details>

EDIT: I should probably clarify why I decided to share the URL. I have a few other engines turned off that slow down the load times considerably and aren't really needed. Startpage uses Google so that is enabled to still get results from there btw.

**Comment by unixfox** [comment]
The PR to fix Google images is merged but my PR is waiting to be merged. When it will be merged you should both test the latest version of searx with this Docker image : https://hub.docker.com/r/woahbase/alpine-searx or use an updated searx instance like mine : https://searx.be.
Because I'm pretty sure this issue is a duplicate of mine : #1596

**Comment by Ryonez** [comment]
What's your affiliation to woahbase? And why are you recommending a change of the docker image I use?

**Comment by Ryonez** [comment]
I did enable duckduckgo and startpage, and I am starting to get results now. Seems bing can be slow at times but I'm at least getting results now.

**Comment by unixfox** [comment]
> And why are you recommending a change of the docker image I use?

It's written in the README:
>Auto updated according to their Github master.

It is likely that if my PR gets merged searx maintainers won't bump right away the version number 
so by using the `woahbase` you will get the updated code of searx with my PR in the Docker image to test if you still have the issue that you stated.

> I did enable duckduckgo and startpage, and I am starting to get results now. Seems bing can be slow at times but I'm at least getting results now.

Like I said in my previous comment I'm very confident that your bug is a duplicate of #1596 if you don't have any issue with other search engines.

**Comment by Ryonez** [comment]
Okay, looked it all over and switched over to that image, no issues found in the change.

**Comment by unixfox** [comment]
@Ryonez @silvernode my PR has been merged can you both test the Docker image that I sent? 
If you don't find any issue can you please close this Github issue @Ryonez?

**Comment by Ryonez** [comment]
I'll close this for now as it does seemed to have resolved the issue, and as a bonus google images seem to work again. Thank you for the patch.

**Comment by xXBeekeyXx** [comment]
Sorry to revive this Issue, but I still get this Error from time to time. I am using an instance of version 0.18.0, and I actually have google disabled in the preferences. Do you have a feeling of what the issue might be?

**Comment by silvernode** [comment]
Try a different instance of the same version and see if it happens again.

**Comment by unixfox** [comment]
> Sorry to revive this Issue, but I still get this Error from time to time. I am using an instance of version 0.18.0, and I actually have google disabled in the preferences. Do you have a feeling of what the issue might be?

It's a known issue and this issue is now tracked at https://github.com/searx/searx/issues/2053.

We have some plans for displaying what's going on behind the "no results".

Meanwhile use another instance that return some results or host Searx yourself.
