### ISSUE TITLE
a large scatter of search results

### ISSUE THREAD

**Issue by kompowiec** [searx/searx#1619]
depending on the server where the instance is running, search results is often very different. will be censorship as like baidu where attempting to search for even not necessarily censored keywords in these search engines will yield few or no results:
https://i.imgur.com/nPrnLkL.png
https://i.imgur.com/dqx7QrC.png

will using ActivyPub be a good idea to solve this?

for example, I tested PeerTube where running any instance always returned the same results.

**Comment by unixfox** [comment]
It is not censorship because the results are different from one instance to another because of the language and the engine(s) set by default. For example on your screenshot by default searx.be is displaying results for the language `Français (Belgique)` (in english: `French (Belgium)` whereas with searx.me it's in `English (United States)`. You can change that behavior by clicking on the dropdown on the right top corner or changing permanently [in the preferences settings](https://searx.be/preferences):
![](https://i.imgur.com/zxAMe4P.png)
Moreover, searx.me is quite broken due this issue: https://github.com/asciimoo/searx/issues/729

If my reply resolves your issue, please close this Github issue.

**Comment by kompowiec** [comment]
ouch right, my mistake. Thanks! Results are identical.

closed
