### ISSUE TITLE
Deploying to Heroku

### ISSUE THREAD

**Issue by lyndalopez544** [searx/searx#1631]
Add a 'deploy to Heroku' button for one-click hosting of an instance on the Heroku platform.

**Comment by unixfox** [comment]
I'm pretty sure Searx is not allowed on Heroku due to these two rules:
> Use the Service to operate an "open proxy" or any other form of Internet proxy service that is capable of forwarding requests to any End User or third party-supplied Internet host;
Use the Service to access a third party web property for the purposes of web scraping, web crawling, web monitoring, or other similar activity through a web client that does not take commercially reasonable efforts to:
    identify itself via a unique User Agent string describing the purpose of the web client; and
    obey the robots exclusion standard (also known as the robots.txt standard), including the crawl-delay directive;

-https://www.heroku.com/policy/aup

**Comment by dalf** [comment]
Seems clear.
