### ISSUE TITLE
Oscar as default template

### ISSUE THREAD

**Issue by Cqoicebordel** [searx/searx#171]
This one is for a discussion :  
I feel that the Oscar template is way better than the two others. Maybe not graphically, but at least by the UX, and by the tools provided.

So my question : Shouldn't it be the default template for a new searx user ?

**Comment by dimqua** [comment]
It may be better to improve the two others instead. For instance, courgette theme does not support DDG definitions.

**Comment by asciimoo** [comment]
@Cqoicebordel currently it shouldn't, mainly because it doesn't fully functional without javascript. With javascript it's way more usable than the current default theme, but using noscript you can't even select categories.

@dimqua yap, both other themes requires improvements/fixes..

I'll finish soon with the static content refactor and then all the 3rd party client side libs will be available for all themes

**Comment by pointhi** [comment]
@asciimoo the truth with js-compalibity is: you can select categories, but it isn't visualised in the theme without js yet. Probably I can add a little css-hack to fix that.

**Comment by Cqoicebordel** [comment]
@asciimoo It could also be useful to do a JS-free template, to allow those without JS activated to use a nice version of searx.
But graceful degradation should indeed be implemented. If @pointhi, you know how to do it, it would be perfect :)

**Comment by asciimoo** [comment]
@pointhi it would be great
javascript independence is always a good goal especially in the case of searx.

@Cqoicebordel agree!

**Comment by asciimoo** [comment]
Okay, experimentally the default theme changed to oscar.
@pointhi what do you think about removing the javascript warning? And maybe a less harsh logo?

**Comment by pointhi** [comment]
I think removing the javascript-warning except in the preferences wouldn't be a problem. Also, the warning should appear if the screensize is to small, because the menue on top doesn't work wihout it.

Because of the logo, I'm not sure. I think the magnifying glass in the logo should remain. What's your idea for a logo? The same as in the other themes, or somthing new?

In the next time, I would add a feature to change the look of the oscar-theme, using a few themes found on http://bootswatch.com/. Probably we could make searx more colourful with it :).

**Comment by asciimoo** [comment]
i don't know, a lighter gray color?
Some minor issues:
- The category selection is buggy in console based browsers (tested with links2 and w3m)
- Long suggestion overflows the suggestion box

**Comment by pointhi** [comment]
Due to refactoring I think we should also improve the oscar template. I'm not a designer, but I know some basic stuff. But color choosing, main graphic elements are not my strong side so I hope we can produce something greate together (I would implement the client side after doing the planing)

On of the parts are the used colors. Probably we could choose some main colors which we can use for all things regarding to searx (something like a Corporate Design)

**My first ideas for the used colors scheme (please add your ideas)**

---

![searx_colors](https://cloud.githubusercontent.com/assets/1652144/10608395/20c8527c-773f-11e5-826f-a7d0e4788305.png)
http://paletton.com/#uid=73L1W0kgOos5bCdaKtrnljkumek

---

![searx_colors2](https://cloud.githubusercontent.com/assets/1652144/10608639/351d1068-7740-11e5-9308-f4e3ac47a92f.png)
http://paletton.com/#uid=73R210kg7os6AsCb9qqm6mqrDkz

---

![searx_colors3](https://cloud.githubusercontent.com/assets/1652144/10608947/ab184d36-7741-11e5-8400-28a0d4f2e6ad.png)
http://paletton.com/#uid=73R1M0kleqtbzEKgVuIpcmGtdhZ

---

(it's only my first idea, but probably using a admin-interface-like style would look good: http://wrapbootstrap.com/preview/WB0696K5S (but heavily modified to display search results))

I started brainstroming on my wiki, what has to be changed in the new version:

https://github.com/pointhi/searx/wiki/oscar-template-v2-ideas

**Comment by Cqoicebordel** [comment]
I like the third color palette.
But I think the big issue here is that none of us are designer.
We can improve things, but I think a really good theme should be designed from the ground up, with UX and mobile in mind.
A call for a open source designer to give us some help should maybe be posted.

**Comment by pointhi** [comment]
yes, I can write frontend templates, but not design them proper (I'm always using some other websites/templates to get an idea how things can be aranged, colored,...).

I don't know if it is good or bad, but I think a tilebased template could be a modern looking and helpful design. I could write tiles for different applications, which are fully scalabel (from phone to big desktop) and visual seperated. Important informations, like widgets, wikipedia results and helpful infoboxes are colorised, normal results more discreetly designed.
But the design should also be able to work with more complex datamodels in the future (#449), so it has to be designed carefully to provide results in a homogenous way.

**Comment by Cqoicebordel** [comment]
Yep.
And beyond that, the most important part is UX. And that is really really hard for a dev to do it right.

**Comment by asciimoo** [comment]
another nice color scheme: http://flatuicolors.com/

**Comment by dalf** [comment]
https://github.com/asciimoo/searx/blob/master/searx/settings.yml#L18
can be closed ?

**Comment by asciimoo** [comment]
done ^^^^
