### ISSUE TITLE
what to do with a warning when run searx for the first time

### ISSUE THREAD

**Issue by ghost** [searx/searx#1742]
Hello,

I am totally new to searx, and how it works.

The link is my question about searx on arcolinux forum.
https://arcolinuxforum.com/viewtopic.php?f=35&t=1679

thanks in advance.

Edit : i copy past the post from the forum.

**Comment by ghost** [comment]
Yesterday i heard from searx, and decided to install searx and see how it works. 

I got this far, with a  warning.
I edited the yml with my **personal public ip** and a **key**  was given in the default settings.yml. (should i change the key?).

This is the source of the yml.
`https://github.com/asciimoo/searx`
I installed searx with yay. And used the github folder to run.

`$ ./manage.sh update_packages`
Because, i could not find it on my system after install of searx. There where no errors doing this.


I enabled more network interfaces. _I think that it takes over other engines. To prevent from tracking. (?)_


>  uncomment below section only if you have more than one network interface
> which can be the source of outgoing search requests
>     source_ips:
>         - 1.1.1.1
>         - 1.1.1.2

> Port : 8888

Running:
`$ python searx/webapp.py`
Gives this output at the end.

   

> searx/webapp.py:975: DeprecationWarning: 'werkzeug.contrib.fixers.ProxyFix' has moved to 'werkzeug.middleware.proxy_fix.ProxyFix'. This import is deprecated as of version 0.15 and will be removed in 1.0.
>   app.wsgi_app = ReverseProxyPathFix(ProxyFix(application.wsgi_app))
>  * Serving Flask app "webapp" (lazy loading)
>  * Environment: production
>    WARNING: Do not use the development server in a production environment.
>    Use a production WSGI server instead.
>  * Debug mode: off
> INFO:werkzeug: * Running on http://127.0.0.1:8888/ (Press CTRL+C to quit)
> WARNING:searx:Unable to fetch guest client_id from SoundCloud, check parser!


Is the service running in this state?
 _* I can only install the -git version. Otherwise i got a dep error._
 :?: thanks in advance

**Comment by return42** [comment]
> I installed searx with yay. And used the github folder to run.

Use one of the installation methods described here https://asciimoo.github.io/searx/dev/install/installation.html .. most prefer the docker way.

> $ python searx/webapp.py
> Is the service running in this state?

With you started the application for development purpose, listening only for local requests on 127.0.0.1 and stops when you close the terminal.  A "service" is running even if you are logged out.  Don't take me wrong, if it is hard for you to see the difference (e.g. the "127.0.0.1"), it will much harder for you to set up a real service  .. that's why most prefer the docker way from the installation instruction / personally never used this way.  I prefer a manual setup (described here [searx@handsOn](https://return42.github.io/handsOn/searx.html) / but this won't help you!).  

**Anyway feel welcome here .. may there is a much more easier solution for you:**

Normally you will install your own searx instance, you will have a 24/7 server it runs on. So if you just  want using searx, use one listed here https://github.com/asciimoo/searx/wiki/Searx-instances .. or take https://searx.me/ ... or use my instance https://darmarit.cloud/searx/ 

Using other instance is the concept of searx, not every user really need to setup its own instance. BTW:  single used instance does not obscure and therefore does not stop tracking. You need many user on your searx node to obscure .. and that's why users are also welcome to our instances (!) 

Hope that's helps to clarify a bit / if this answered your Question, please do not forgett to close this issue / thanks!

**Comment by ghost** [comment]
Hello Searx team,



Thanks for the reply. I will have look into your tips and see, what could be a good solution for me.





Greetings, Eric B



---- Op vr, 06 dec 2019 17:09:49 +0100 Markus Heiser <notifications@github.com> schreef ----


I installed searx with yay. And used the github folder to run.


Use one of the installation methods described here https://asciimoo.github.io/searx/dev/install/installation.html .. most prefer the docker way.

$ python searx/webapp.py
 Is the service running in this state?

With you started the application for development purpose, listening only for local requests on 127.0.0.1 and stops when you close the terminal.  A "service" is running even if you are logged out.  Don't take me wrong, if it is hard for you to see the difference (e.g. the "127.0.0.1"), it will much harder for you to set up a real service  .. that's why most prefer the docker way from the installation instruction / personally never used this way.  I prefer a manual setup (described here https://return42.github.io/handsOn/searx.html / but this won't help you!).

Anyway feel welcome here .. may there is a much more easier solution for you:

Normally you will install your own searx instance, you will have a 24/7 server it runs on. So if you just  want using searx, use one listed here https://github.com/asciimoo/searx/wiki/Searx-instances .. or take https://searx.me/ ... or use my instance https://darmarit.cloud/searx/

Using other instance is the concept of searx, not every user really need to setup its own instance. BTW:  single used instance does not obscure and therefore does not stop tracking. You need many user on your searx node to obscure .. and that's why users are also welcome to our instances (!)

Hope that's helps to clarify a bit / if this answered your Question, please do not forgett to close this issue / thanks!

**Comment by return42** [comment]
Then, please close this issue / thanks!
