### ISSUE TITLE
Where can I find the caddy config example? How to transform the nginx config to caddyfile?

### ISSUE THREAD

**Issue by neatgz** [searx/searx#1764]
I followed the Step by step installation guide on 
https://asciimoo.github.io/searx/dev/install/installation.html
and can not find the config example for Caddy.
I do not want to using reverse proxy , because the guide say (Please, note that reverse proxy advised to be used in case of single-user or low-traffic instances.)
Could anyone help me transform the nginx config example to caddyfile, thanks
```
server {
    listen 80;
    server_name searx.example.com;
    root /usr/local/searx;
    location / {
            include uwsgi_params;
            uwsgi_pass unix:/run/uwsgi/app/searx/socket;
    }
}
```
The part that I do not know how to write is:
```
    location / {
            include uwsgi_params;
            uwsgi_pass unix:/run/uwsgi/app/searx/socket;
    }
```
thanks a lot

**Comment by unixfox** [comment]
I'm using the [`proxy`](https://caddyserver.com/docs/proxy) module of Caddy for Searx and it works fine. I don't see any slowdown.
Moreover, my Searx instance is public and used by around 100 visitors per day.

If you really want to use WSGI, you are in bad luck because Caddy doesn't support it and there is an open issue about that here: https://github.com/caddyserver/caddy/issues/176
But mholt is asking the community to develop a WSGI implementation for Caddy V2: https://github.com/caddyserver/caddy/issues/176#issuecomment-540848862 so there is still hope for the future.

In the end just stick to reverse proxy Searx on Caddy and it will work fine.
If my reply resolved your issue, please close it :smiley:.

**Comment by neatgz** [comment]
thanks a lot
