### ISSUE TITLE
Official Public Searx Instance (https://searx.me/) Constantly Unworkable

### ISSUE THREAD

**Issue by ghost** [searx/searx#1809]
![Failed query](https://user-images.githubusercontent.com/59848432/72293822-33a3ab00-364c-11ea-8682-38d56ae05464.png)
Every 3 weeks I find that the https://searx.me/ instance does not run and fails to give any results.  It was working and fixed about a week ago and worked fine for all of 3 days after the Flickr commit.  It is now back to the status quo of not working.

While I favor the optionality to run your own self-hosted instance the range of privacy is reduced because of how few people actually utilize those searches (the overall entropy is much lower).  I want to use a public, popular, common instance and I find that searx.me should be this optimal one (I believe asciimoo is the one that hosts this one also - correct me if I'm wrong).

More often than not it fails to generate any result when I type any string into searx.me.  If I continue to click search or try to be more generalist with my search query it usually (if anything) yields a Wikidata/Wikipedia.org link as shown in this attached screenshot.  Most of the time if I persist I can manage to get a Bing.com result if I'm lucky and usually it will only generate one page.  Google usually doesn't work except in those short periods like last week when it magically resurrects itself.

I am often forced to use the Belgium instance that is maintained by one of the top contributors here who seems to have cured these woes but unfortunately has French as the default language (I am persistently switching it to English - en to get the results I need).

Could you please fix searx.me so that it works as seamlessly as https://searx.be/ and without any of these cache problems?  I saw this commentator from RestorePrivacy write something similarly as me that Searx simply isn't working and honestly if searx.be starts to give me trouble I'll need to start considering using SwissCows as my daily driver.

I know it's not an isolated instance of me struggling to tame searx.me.  I've tried with VPN/without, from Mobile phone network, JavaScript enabled/disabled, from other people's PC's, work network, at home, etc.  I would figure you would want some popular instance for people to gravitate to that is officially sanctioned by the "Creator."

Every 3-4 weeks I'm breathing a sigh of relief and switching searx.me to be my default search and like clockwork it starts to simply NOT WORK and I'm forced to change it to searx.be within less than a weeks time.

Also: I don't know what kind of public information is available on https://searx.me/ with regards to tracking, I know that the creator of https://searx.be/ does do some tracking/logging "Uses Fathom Analytics for user tracking and analytics"
Edit:  I saw the latest commit from that owner that they removed Fathom Analytics and no longer track the user.  This is a huge benefit! Thank you unixfox!

Any idea who owns/maintains it and what kind of tracking and logging is done?

Thankfully yours,
an idealist who likes the engine and believes this is the best search

**Comment by asciimoo** [comment]
Searx.me isn't an official public searx instance.
It has infrastructure issues nowadays, sorry for the inconvenience. I should stop the instance while these issues are unresolved.

I can recommend https://searx.laquadrature.net/ and https://search.disroot.org/ , but the best is if you host it for yourself.

> Any idea who owns/maintains it and what kind of tracking and logging is done?

I'm maintaining it, no logging/tracking.

**Comment by ghost** [comment]
Thank you asciimoo!  Thanks for all your work as well and for this.  I look forward to an instance you maintain in the future (I know there are bigger priorities!).

**Comment by asciimoo** [comment]
> Thank you asciimoo! Thanks for all your work as well and for this. I look forward to an instance you maintain in the future (I know there are bigger priorities!).

I'm happy to maintain an instance but currently I don't have the infrastructure needed to provide a smooth service. A big traffic searx instance requires bunch of ips and a privacy respecting hosting service. Let me know if you know such a hosting provider

**Comment by unixfox** [comment]
> unfortunately has French as the default language (I am persistently switching it to English - en to get the results I need).

I actually considered in the past to set English as default language because it seems that there are more English speakers using it than real Belgians. But meanwhile you can set "English" as a default language in the preferences or use the `Search URL` given by the preferences page if you don't want to use the cookies.

> Could you please fix searx.me so that it works as seamlessly as https://searx.be/ and without any of these cache problems? 

Won't happen any time soon because searx.be is actually using a *better* anti bot protection (please see https://github.com/asciimoo/searx/issues/729#issuecomment-511997511 to know why) than searx.me, that's why you have working Google results by **default** on searx.be. I try also my very best to keep the instance running as smooth as possible because I'm using it myself every day.

> Also: I don't know what kind of public information is available on https://searx.me/ with regards to tracking, I know that the creator of https://searx.be/ does do some tracking/logging "Uses Fathom Analytics for user tracking and analytics"

This was never meant to track every single movements of the visitors of my instance. Just a way for me to be happy to know that hundreds visitors actually like my hard work done on my Searx instance. It also helped me in the past to analyze bots behavior while building my anti bot solution. I removed any tracking on the website because I stopped caring about statistics, in the end I saw that quite of lot of people like to use my instance and that's all what matters.

PS: I'm really sorry for being a bit off-topic.
