### ISSUE TITLE
Any way to require all search terms to be present?

### ISSUE THREAD

**Issue by geckolinux** [searx/searx#1817]
Hi there, I know that this behavior isn't really SearX's fault, but rather an annoying/infuriating tendency of *all* the search engines recently to simply ignore certain search terms. But is there any way that this could be worked around in SearX? Maybe internally forcing it to "put" "quotes" "around" "every" "term"?
Thanks!

**Comment by return42** [comment]
>  tendency of all the search engines recently to simply ignore certain search terms

is it so? .. can you give me an example / thanks.

**Comment by geckolinux** [comment]
Sure,
https://searx.info/?q=qyt+abr

**Comment by return42** [comment]
Maybe I misunderstood you, but you said:

> tendency of **all** the search engines recently to simply ignore certain search terms

Searx only reflect what it gets from "all" search engine, so my question was about e.g. google, where did google ignore your search terms?

**Comment by geckolinux** [comment]
@return42 Ah, sorry. This for example:
https://www.google.com/search?q=qyt+abr

But it's practically on every search that Google second-guesses me and either ignores or changes many of the terms.

**Comment by ghost** [comment]
I played with it, downloaded the addon:
https://addons.mozilla.org/en-US/firefox/addon/add-custom-search-engine/?src=search 
and I added my search engine:
Search URL: https://nibblehole.com/search?q=%s
and works great for me

**Comment by return42** [comment]
@geckolinux first I want to say, that it is hard to compare, since we all live in our own google bubble :-o

My experience is, that using quotation mark (`"foo" "bar"` versus `foo bar`)  gives less, but more precise results. I observe this for google.  On the opposite there is  bing, they ignore the quotation mark of single words.  

If I use searx (meta search engine)  the quotation marks are passed through to the origin search engines and the result list sums up / reflects what  origin search engines do.

For me it is the best behaviour and I have no idea what we can imprve here. if you think we can improve this in any way, please post your possible solution .. otherwise I ask you to close the issue / Thanks!
