### ISSUE TITLE
Make the Flagship Instance a Meta-Searx Redirector or i.e Redirect to a Meta-Searx

### ISSUE THREAD

**Issue by MilkManzJourDaddy** [searx/searx#1853]
I have been telling people, end-users too, about Searx, and gave them the neocities link.  But, ***OF COURSE***, the first thing they do is hit Google®️ and come up with the Searx.me instance which is having issues due to infrastructure" or bandwidth or something.  And now I look dumb to thse **uninformed** people, for trying to de-Google®️.  Mostlikely the Wikipedia page for the project has Searx.me .

So, can we instead of, or in addition to the snippet about hosting your own (which no end user will do) have a redirection, even within a frame, to a Meta-Searx?  

Thanks.  🍻

**Comment by Pofilo** [comment]
I just think people can read by themselves. Searx.me is just an instance like every others.

An amazing job have been made to give people a list of instances available here: https://searx.space/

Searx is not Google, Searx is a metasearch engine that everybody is able to host.

**Comment by MilkManzJourDaddy** [comment]
Do you work for Google®️?  ***Seriously***?!?!  I mean, way to drive away all the end-users and people who try to get end-users to de-Google®️ by using a **PUBLIC INSTANCE** hosted by those willing to **HOST A PUBLIC INSTANCE for thos unable to do so for themselves**; full stop.  No!  When people search for Searx, the first thing they find is Searx.me, and if that can no longer host a public instance, fine; but it should show a more end-user friendly way for them to find a **Publicly Hosted Instance**; full stop.  You host all the private instances you want, and keep them private and don't stand in the way of de-Google®️-ing; or host a public instance and offer it up for the entire re-direct traffic from Searx.me ; full-stop!

**Comment by MilkManzJourDaddy** [comment]
Are all your grandparents able to host an instance?  All your aunts & uncles or other distant relatives?  What about others in your life IRL?  You cannot possibly tell me, **honestly**, that you do not know anyone at all who is technically inept to self-host, or who lacks the resources.  And some might worry about the logging anyway, i.e. in #1839 .  No, it's the year 2020, but MANY still cannot self-host.

**Comment by return42** [comment]
Sorry, I do not understand what's the problem. May related to my bad english, may you are a bit excited ... @Pofilo linked to   https://searx.space/ .. what is wrong with?

**Comment by MilkManzJourDaddy** [comment]
If you neither of you comprehend English, how can any of the **b**illions of English speakers on the planet, myself included; possibly explain the **actual issue** to you, any more than I already have?

**Comment by return42** [comment]
If you don't want a solution, call me an idiot.

**Comment by dalf** [comment]
> Do you work for Google®️? Seriously?!?!

@MilkManzJourDaddy Nope, but the answer is in the question. Please calm down.

As I understand your request:
* remove the searx.me references (from the wikipedia pages, wikidata page, here, may be elsewhere).
* redirect searx.me to something useful:
   * If I take short cut: redirect to searx.space.
   * If I don't take short cut ( _"have a redirection ... to a Meta-Searx"_ ) : make a HTTP redirect to one of the meta searx list in the about page of searx.space ( Neocities or Searxes ), so the user just a have search input, click search and that's it. I'm afraid that it won't work as expect because there are different instances with different flavors, and if a user don't understand that searx is made of many different instances, the user experience will be disappointing.

Related to https://github.com/dalf/searx-stats2/issues/9 to remove the trust issue.

If I take a step back to your requests, you are asking to provide a trustful, reliable and no brainer meta search engine (so same properties for all the searx instances). I think we all wish that, we try to go in that direction, but nope we don't work for Google, and we don't have the same ressources.

**Comment by MilkManzJourDaddy** [comment]
~~No, the miscomprehension of the issue was condensed down to copy&pasting a link which is irrelevant; thereby insulting **ME**, as if I'm unaware of searx.space .  I know of that and it's not the issue.  If you do not understand, ask.~~

I see a rational answer while I was typing…

Here are the links for: 

https://searx.neocities.org/   

and

http://searxes.nmqnkngye4ct7bgss4bmv5ca3wpa55yugvxen5kz2bbq67lwy6ps54yd.onion/?st=d&ul=en  

The clearweb link for the Searxes page  https://danwin1210.me/ redirects to https://codeberg.org/crimeflare/cloudflare-tor/src/branch/master/README.md  just to further confuse any **End-User**, it seems.

So, make https://searx.me/  redirect to something like https://searx.neocities.org/   possibly with a HTTP 302, even in a frame.  You do know what a `frame` is, right?  

Either that or make your grandmothet hand code `gopher://` and tell the world to switch.  At least then we will know for certain you are trying to kill the project snd we will not bother tryibg to gey people yo use Searx **Public Instances**.

**Comment by MilkManzJourDaddy** [comment]
~~ https://danwin1210.me/ ~~ → https://searxes.danwin1210.me/

**Comment by dalf** [comment]
I'm not sure to understand _redirect to something_ ? https://searx.neocities.org/ or  https://danwin1210.me/  ? Both ?

@MilkManzJourDaddy As I understand, you are a developer, so let's image that searx.me redirect to searx.space, and we change the front page of searx.space.

Can you make a PR to https://github.com/dalf/searx-stats2 ?
The html page is here : https://github.com/dalf/searx-stats2/blob/master/html/index.html
Or at least make a gist what searx.me should be ?
Thank you.

**Comment by Pofilo** [comment]
@MilkManzJourDaddy okay, you need to relax, there is no problem, no troubles, only solutions.

When I said:

> Searx is not Google, Searx is a metasearch engine that everybody is able to host.

I meant that Searx is not a single instance as Google is. There is (for the end-user) one instance of Google, but hundreds of instances of Searx, hosted by hundreds of people.

Searx.me is down (maybe it will be back one day, maybe not). However, and this is understandable by everybody, you can use an other instance of Searx instead.

So if someone is going to https://searx.me right now, he will be redirected to https://asciimoo.github.io/searx/user/public_instances.html then to https://searx.space/ then he can pick the instance he wants.
This may not be ideal, but Searx is not a company, every instance can be down someday. So if you used to use an instance, you may be force to change at some point because your instance is not available anymore.

There is still references to the old list of instances hosted on Github. Even the main page of a searx instance has a link to https://github.com/asciimoo/searx/wiki/Searx-instances.
This is something we still need to improve, PR are open, everybody can help us for that.

> ~~ https://danwin1210.me/ ~~ → https://searxes.danwin1210.me/

What the point of this comment ?

**Comment by MilkManzJourDaddy** [comment]
Look, I gave someone, an **End-User** the EXACT, correctly spelled link: https://searx.neocities.org/  and told them to use that, but end users have minds of their own.  No they used a search-engine, you know which one, and went to searx.me , ending the UX flow-chart until I took the time to go **in person** and save it in their browser.  

But this is the on-boarding process made harder by link rot. 

If you expect **End-Users** to jump through a bunch of links, then you haven't done much UX work.  The person who made the thumbs-up reaction gets it, but maybe they speak English and are hoping to actually see Searx be a thing.   

I full well know there can be a many of Searx instances.  You write English well enough but claim to not understand it, odd.  Tfw not sure if being trolled… 

Anyway, I have my own work to do rather than **try** and get you to understand End-User UX / on-boarding by making searx.me show end-users https://searx.neocities.org  or following your PRs/MRs welcome taunt.  I've given enough time in this issue. 

Sad, yet another project I hoped to see flourish…

**Comment by MilkManzJourDaddy** [comment]
@unixfox :  Your turn!  

`Beam me up Scotty…  There's no intelligent life on this planet.`

**Comment by scotty-entreprise** [comment]
I'm afraid I can't do that @MilkManzJourDaddy

**Comment by dalf** [comment]
anyway, searx.me still need to be updated.

**Comment by Pofilo** [comment]
@dalf do you know if only @asciimoo have access to it ? 

I'll make a PR this week-end to update every links to the list of instances to https://searx.space.
By the way, who is the official maintener of https://searx.space ? (only you @dalf ?) I'll see if I can also host this same list.

**Comment by return42** [comment]
I send a mail to Adam .. to fix the link to searx-stats2

I guess this was the issue here, just a dead link ..  pew definitely, the world needs more smoke ..

**Comment by dalf** [comment]
FYI, I don't have have access to searx.me, only searx.space.
See https://github.com/dalf/searx-stats2/issues/24

**Comment by MilkManzJourDaddy** [comment]
Either I need to relenquish my MENSA Card for not stating "tl;dr dumbed down issue = broke link" or someone needs to pick up a Dunce Card for being the typical "condescending" (from down in the quagmire) territorial dev' who can't even comprehend basic issues.  Or maybe the real issue for such micromanager is circumstances beyond their control. 

But do all the S.E.O. you want.  For some time to come, Centralized search-engines will return Searx.me when queried for "Searx".  **If you have no ability to update Searx.me , you have no business deliberately sabotaging and crapping on this issue.**  But go ahead and instead of sending **End Users** to a Meta-Search as I wisely suggest, send them through your maze of broken links or directly to your donation links and see if it all doesn't wind up as things are with XMPP.  

Such a pity when these projects lose direction, and spine. 

But you've got your sci'fi' parody little Mel Brooks/Rick *Moronass* (spelling? ) to keep you entertained in the other repo', so *buh bye*.

**Comment by return42** [comment]
Please change your drugs ..

**Comment by MilkManzJourDaddy** [comment]
Kindly put down your Fidget-Spinner long enough to change your nappies/diaper so we don't have to bear the stench.

**Comment by return42** [comment]
Okay, last try. Forget everything that was said. Please put yourself in our position, we spend our free time to advance a project of which we have no economic use. 

We do this for many different reasons, me and many others do it because we enjoy in working with people on projects like this. But the fun is lost when people come by to bitch at us just because we made a mistake, because someone made a mistake, because something was not understood . . .

You are invited to participate in this project, but please understand that we are a community of diverse people with diverse skills.

**Comment by MilkManzJourDaddy** [comment]
I'm going to try one more time, also.  But first I must complement what you did in fact do, because of my prodding.  

But unfortunately this is yet another case of a dev' in control of a repo' closing an issue without actually takung the time to understad the issue, assuming it's just some confused garden-variety end-user who wandered in.  
And yet we should consider the end-user or even technically adept person who just wants to have a quick look before dedicating infrastructure, or making changes, or choosing someone else's Searx instance.  To that I suggested putting the neocities Searxes in a `frame` or a URI to that Meta Searx instance. 

It seems the simplest solution for someone who might latch on to the heading: "I just want to try it, **NOW!**", which you could arbitrarily put in a `frame` or `table`.  You could also put a URI to the [https://searx.space](https://searx.space) page of instances, anchored to the "Meta-searx instances" `<h3>`, but I didn't notice a named anchor for that.  Also, many people won't have a clue about Tor or any Onion URL, and could just be further confounded.  You have to understand the on-boarding process and trying to help people get off Google®.  **For example**, GPG has been a thing for quite some time but is not in common use; **however**, [autocrypt.org](https://autocrypt.org) aspires to change that.  So you might make a bit of HTML to aspire to help people de-Google®, unless you don't want that.  I suggest a good sized `frame` for [https://searx.neocities.org/](https://searx.neocities.org/), or a link, offloading onto their site, or redirecting to an **End-User's page**, on searx.space if that's what you want.  Because it's worth repeating, 
# I gave a non-Tor user the **EXACT LINK** for the neocites Meta Searx instance, but they used Google® and went to searx.me before you updated. 

And even after you updated searx.me , **they are an END USER who will NOT KNOW WHAT to do with the INTERMEDIATE/ADVANCED USER/Dev' content, and therefore need DIRECT HTML content showing them to the neocities Meta Searx instance.** 

Fwiw, I had **no such difficulty in communicating with or dealing with @ascimoo .** 

`¯_(ツ)_/¯` 🤷
