### ISSUE TITLE
Swisscows search engine

### ISSUE THREAD

**Issue by kseistrup** [searx/searx#1859]
It would be nice if SearX could include the non-tracking search engine _Swisscows_: https://swisscows.ch/

In the now closed #347 from 2015 it was it was said that

> I have added it to the wiki: https://github.com/asciimoo/searx/wiki/possible-search-engines. Probably I'm implementing it soon, because the search-quality is very good.

and the name is still mentioned in https://github.com/asciimoo/searx/blob/master/searx/data/engines_languages.json#L24331

However, I no longer see the engine in `settings.yml`, nor do I find the engine in `searx/engines/`. 

Has Swisscows been abandoned?

**Comment by dalf** [comment]
It has been removed from searx because swisscow has changed it's front-end: on each request to Swisscow, the html page gives a code (```App.initialize("eyJUaWxlcyI6W3s...```) to some obfuscated Javascript. This javascript then makes a request with another code probably computed from the ```eyJUaWxlcyI6W3s...```.

To use swisscow it requires to understand the javascript, then make similar requests. IHMO, I'm afraid that doing so means that's probably swisscow will change it code few months / weeks later. Then we have to deoffuscate the code again even if the code uses something as simple as ROT13.

**Comment by kseistrup** [comment]
Oh, I see. It makes sense that it has been removed, then. Thanks!
