### ISSUE TITLE
bing_video don't kike "older" FF versions

### ISSUE THREAD

**Issue by return42** [searx/searx#1882]
Bing video seems not to work with "older" FFox version, there is a interim fix https://github.com/asciimoo/searx/pull/1866/commits/ad7a6e6e1022 but this might need some more work in the near future .. about FFox versions see #933

**Comment by unixfox** [comment]
Maybe @dalf could bring the [httpx_firefox branch](https://github.com/dalf/searx/tree/httpx_firefox) into master?

**Comment by MarcAbonce** [comment]
If you run `./manage.sh update_useragents` right now it already updates `useragents.json` to use Firefox versions older than 70 which is better than hardcoding the user agent, in my opinion.

But yeah, ideally I guess it would be better to automatically run that script somewhere instead of waiting for things to break before we remember to update our user agents. But for now, we can just manually run it once every couple of months or so. Browsers release new versions very often this days...

**Comment by return42** [comment]
> But yeah, ideally I guess it would be better to automatically run that script somewhere instead of waiting for things to break before we remember to update our user agents

If have such a task on my (long) todo list  .. in PR  #1803 I added a Makefile target [project](https://github.com/return42/searx/blob/filtron/Makefile#L28) to re-build generic files of the searx project.
