### ISSUE TITLE
Improve code review processes for searx collaborators

### ISSUE THREAD

**Issue by HLFH** [searx/searx#2025]
Hi @asciimoo @return42 @dalf @kvch,

Source: https://github.com/asciimoo/searx/pull/1954

> I'm getting more and more frustrated. I invested months of work to improve searx substantially (see searx-next merged PRs). But my PRs are ignored, which entails considerable maintenance costs: Instead of reviewing PRs, changes are shot in, which additionally increase the organizational overhead. Something is going wrong if we are three developers here and generate an organizational effort.

<img width="934" alt="Screenshot 2020-06-25 at 09 40 01" src="https://user-images.githubusercontent.com/2359059/85686484-e8e09180-b6c7-11ea-8a5e-5cd0c1a140c3.png">

<img width="964" alt="Screenshot 2020-06-25 at 09 40 07" src="https://user-images.githubusercontent.com/2359059/85686501-ed0caf00-b6c7-11ea-83ba-bb2672a29f70.png">

<img width="1259" alt="Screenshot 2020-06-25 at 09 41 45" src="https://user-images.githubusercontent.com/2359059/85686704-1af1f380-b6c8-11ea-9d97-1fd7a1728d32.png">

I see we have [many great contributors](https://github.com/asciimoo/searx/graphs/contributors) for the searx project.

Is there some way of improving the code review processes for searx collaborators?

**Comment by dalf** [comment]
I'm going to try to answer, this is only my view point.

I feel like the boogeyman of the pull requests.

The original spirit of searx: keep the code simple, KISS principal, keep the number of dependencies low.
The purpose is to allow anyone to look at the code and figure out where the things are, how they are linked together.

My way, but this is only my opinion:
* one PR should focus on one subject, and contains some comments about the changes (in the PR comments, in the code, wherever it makes sense).
* try to get a clean git log for the master branch.
* try to keep a working master branch.

Of course everything it is matter of trade off, and we all come with a different backgrounds, and different spirits.

It is really difficult to achieve these goals on big pull request: it often ends up with a huge list of comments and reviews. I repeat this is only my view point.

And https://github.com/asciimoo/searx/pull/1954 doesn't fit into that category, it is an small pull request.

The main point is elsewhere and I don't know how to say it: I'm sure this is not your intention, but I'm not comfortable with your tone, @return42. For example, when you write in PR https://github.com/asciimoo/searx/pull/1985 :

> Thanks for the info .. I won't revert b44d0d9 & 433c639 / we really have other problems.

It closes the discussion with a very strange feeling on my side, and I felt like an idiot without an answer to my question "Does it solve an issue with the Google engines ?".

And at the same time, your contributions are really valuable.

**Comment by return42** [comment]
I think it is a bit OT, but I would like to explain myself, since I have probably left a wrong impression ..

> I feel like the boogeyman of the pull requests.

Unfortunately, you're the only one doing reviews regularly, same with @unixfox who answers questions and provides valuable information at hand on a regularly basis .. I wish the world has more of contributors like you!

I learned and learn much from all your contributions, remarks  .. more than I can process and implement. Contributors like you are the reason why I prefer to work in Open-Source projects; _learn from other and give something back_. On the other hand, I have been programming for over 30 years, which means that I have built up my own experience and my own beliefs I stand for until I am instructed otherwise.

> The main point is elsewhere and I don't know how to say it: I'm sure this is not your intention, but I'm not comfortable with your tone, @return42. For example,

No, it is not my intention .. but you are right, there are many examples, I know .. shame on me .. I'm sorry that I react grumpy so often.  But I also often get the feeling I waste my time .. I pick up you mentioned as an example to explain myself:

> Thanks for the info .. I won't revert b44d0d9 & 433c639 / we really have other problems.

My experience is that changes such as code quality (pep8 vs pylint) and the Py3 changeover take years. This can only be achieved (especially in open source projects) by continually changing the code that is being patched (bugfixed) anyway in line with the long-distance goals. This ensures that the code has been tested sufficiently even after the changeover. You do this until the "old" has grown out of the sources and in  5 or 10 years you will reache your long distance target.

I wanted to achieve both (py3 & pylint) when revising the google engines. I know that these long-distance goals are violate KISS and are in contrast to small patches, which I normally prefer like you.

> It closes the discussion with a very strange feeling on my side, and I felt like an idiot without an answer to my question "Does it solve an issue with the Google engines ?".

I apologize that I ended the discussion impatiently, I should have explained my position better (see above).

Yes I am often impatiently and want to get things done. You are very perfectionistic, such as in the discussion when you brought git-bisect into play. It is very difficult for me to see on the one hand how much work lies ahead of us and on the other hand to fulfil your perfectionism (which I really appreciate). Unfortunately in such situations, I often react grumpily. Please don't take it personally.

> but I'm not comfortable with your tone, 

Right, I have to improve my tone .. I will do my best, but please forgive the old man if he falls back into old patterns.

**Comment by asciimoo** [comment]
I already started to answer this topic in #1954 , let me continue here.
@return42 I can understand your frustrations and as I said I'm open to any kind of suggestion to improve searx and the development.

Just to clarify things a bit: nowadays I have far less free time to maintain searx than It would be required to keep things going smoothly and to avoid situations like this - fortunately we have awesome maintainers like @dalf who can compensate. =]
As @dalf said, in the first few years searx was a quite small hobby project with quite a few rules and we worked on it for fun, however it seems now these are not necessarily enough to manage the project successfully. We have more than 100 contributors, >700 merged PRs (+ >50 open), 2K issues and tons of users all with different needs. Moreover I have far less than 30 years of dev experience, it's my first big free software project and I'm learning how to handle it properly while the maintenance of searx is still done in my free time since 2013 (which means a lot of engine fixes.. =) ).

I'm happy to add more maintainers to searx or change the workflow or the tooling or nearly anything around the project (except being privacy respective) to support the maintainers/contributors/users, so please suggest constructive solutions instead of being grumpy.
I think, if we had a better issue prioritization process and a better contribution guide, it could improve a lot on the speed and quality of reviewing. For example now if I see multiple PRs from a contributor I do the reviews chronologically which wasn't the best choice in this specific case, because the first PR of @return42 contained more than 7K line changes.

@return42 you can also fine-tune your workflow to reduce your frustration by making much smaller and a bit more descriptive PRs - and only one (or just a few) at time. This makes the reviewing much easier and doesn't require hours of continuous review. Also, it can reduce the conflicts caused by other contributions.

It's so good to see that this project has so many enthusiastic contributors who really care about the future of searx, but please always do it in a supporting and constructive manner.
**There is no problem with criticism if you also suggest a better solution**. Being sarcastic or offensive rarely solves a problem in this field. =)

**Comment by return42** [comment]
>  Being sarcastic or offensive rarely solves a problem in this field

Since I have not received any feedback over a long time, frustration has built up on my side and I have gone wrong in the tone. I apologize for that, I was impatient and selfish. If it is OK for you, please forget my wording and let's look forward ..

I guess we are all more or less in the same situation; we all fight for the best solutions from our point of view and we agree on the goal of finding the best solutions. However, the time that is available to us is limited by our reality of life.  The challenge is to find the best compromise between the own possibilities and the goals, this compromise is individual for each of us and changes over the time.  All that said, it isn't really a breaking news, it is what managing Open-Source projects characterizes ..

> There is no problem with criticism if you also suggest a better solution.

.. I guess there is not "the one solution" but we can improve things here and there.  I think the best starting point for me is to improve my tone and to be more patient.  What else can we improve? I list things that I can think of spontaneously (changes and additions are welcome) ..

We have a quality gate consist of a CI test and a review process for PRs.  @asciimoo, you are the owner I do not want to dictate you anything, but I think it will help if you are more a part of this quality gate and your changes are reviewed and discussed like others.

If time is your problem, think about delegation .. if we know what your targets are, we can help .. which brings me to the next topic:

Compared to other contributors, I'm very new to searx so I may missed some background, but for me it is not clear what our long-distance targets are (if we have such).

I see https://github.com/asciimoo/searx/projects/5 but for me it is not clear what the classification is to become a part of the list. It would be helpful if we have some notes about the targets of a v1 .. when do we have the point "v1" reached? .. what are the criteria?

I think, even if our time is limited, we need some leading words about long-distance targets.

So far I had my own strategy,

- I started with the build process (Makefile) and added boilerplate code which was needed for compling docs and deploy on github.
- I added targets to symplify developer's daily tasks.
- After, I focused on the installation process, because I have seen many issues around this task.
- Then I revised major engines like google.
- And when thinking about plugins, I want that plugins no longer be a part of the searx core.
- I also think that clients should be pure REST & JSON clients which do not need a part of the searx core (wouldn't it be reduce complexity and improve performance if we get rid of all that jinja templating?).
- I also have the long-distance goals to improve code quality (continuous switch from pep8 to pylint) and
- move the code from typical py2 implementation with py3 extension to a typical py3 implementation with some sorts of downstream compatibility.
- And I want to replace licences terms with SPDX-Tags
- and .. and .. and  :)

Could we define some kind of _"continually work on long-distance targets"_ ... to explain what I mean:

> My experience is that changes such as code quality (pep8 vs pylint) and the Py3 changeover take years. This can only be achieved (especially in open source projects) by continually changing the code that is being patched (bugfixed) anyway in line with the long-distance goals. This ensures that the code has been tested sufficiently even after the changeover. You do this until the "old" has grown out of the sources and in 5 or 10 years you will reache your long distance target.
> I know that these long-distance goals are violate KISS and are in contrast to small patches, which I normally prefer like you.

But these are only my 5cent .. what do you think?

**Comment by HLFH** [comment]
@asciimoo Thanks a lot for your helpful reply. I agree on having the quality gate for everyone including you, and you can add me as collaborator, so I can help at least on reviewing PRs. Many thanks :)

**Comment by asciimoo** [comment]
> We have a quality gate consist of a CI test and a review process for PRs. @asciimoo, you are the owner I do not want to dictate you anything, but I think it will help if you are more a part of this quality gate and your changes are reviewed and discussed like others.

Sure, I'm happy to create PRs and follow the the usual contribution process, I just felt that it would make more work for the maintainers - and pushing directly to the master was how I did it from the beginning =]. So if the other maintainers (@dalf , @kvch) agree on this, I'm gonna contribute this way.

> If time is your problem, think about delegation ..

What should I delegate? Maintainers have permission to do mostly anything I can do except to push directly to the master which isn't the best thing for me neither as it turns out.. =)

>  It would be helpful if we have some notes about the targets of a v1 .. when do we have the point "v1" reached? .. what are the criteria?

There isn't any hard constraint, if you feel something would make 1.0 better and it is necessary to be in 1.0, feel free to put it to the project board or open a discussion about it.


> @asciimoo Thanks a lot for your helpful reply. I agree on having the quality gate for everyone including you, and you can add me as collaborator. Many thanks :)

Thanks a lot @HLFH both for your previous contributions, for creating this issue to clarify things and for offering help to maintain the project. I'm adding you to the maintainers ASAP.

>  so I can help at least on reviewing PRs.

Reviewing doesn't require any special permissions, just merging does AFAIK.

**Comment by kvch** [comment]
Personally, I have tried to review a few PR now and then if I had the time and energy. I know we are all engineers who prefer coding and creating something new, instead of double-checking of others' work. Thus, I tried to prioritize it when I could. However, in a few PRs, I found it hard to contribute anything for different reasons. Sometimes PRs lack context, so I am not sure about what the intention of the author or what is the priority. Other times the changeset was either too big or undocumented.

I suggest we adopt changes to help reviewers or incentivise the process.

1. Add a PR template with a few helpful questions to lead writing the description of a PR:
   - Why does your PR do?
   - Why is this change important/useful?
   - How to test locally the changes?
2. One PR should only contain one feature or fix one thing.
3. Maximize the size of a PR. If a changeset is too big, we can still submit PRs to feature branches and when the feature is complete, we can merge it to master.

Besides the suggestions above, we could create a reviewer rotation. For example, for a week I would review all PRs, the next week @return42 then @HLFH, etc. We could come up with the rotation every month and maintainers could volunteer for each week. Of course, it does not mean that if you are not on the rotation, you are not allowed to review. :D We could come up with the exact process together if we decide we need a rotation.

>> We have a quality gate consist of a CI test and a review process for PRs. @asciimoo, you are the owner I do not want to dictate you anything, but I think it will help if you are more a part of this quality gate and your changes are reviewed and discussed like others.
>
>Sure, I'm happy to create PRs and follow the the usual contribution process, I just felt that it would make more work for the maintainers - and pushing directly to the master was how I did it from the beginning =]. So if the other maintainers (@dalf , @kvch) agree on this, I'm gonna contribute this way.

I don't mind if @asciimoo pushes to master directly. Since the beginning of the project, he pushed to master directly. Also, I haven't seen anything he contributed which does not meet the standards of searx. If the build on master breaks, after his pushes he fixes it right away. But TBH I haven't seen such a problem before. So I do not see how the quality of searx is degraded by the fact that the author of the project is pushing to master directly.

>Thanks a lot @HLFH both for your previous contributions, for creating this issue to clarify things and for offering help to maintain the project. I'm adding you to the maintainers ASAP.
>
>>so I can help at least on reviewing PRs.
>
>Reviewing doesn't require any special permissions, just merging does AFAIK.

AFAIK if someone is not a maintainer, their approval is not enough to merge a PR on Github.

**Comment by return42** [comment]
> So I do not see how the quality of searx is degraded by the fact that the author of the project is pushing to master directly.

Sorry if I was misleading .. its not about code quality, its more about finding best solution in the team and sharing knowledge in the discussion.

**Comment by kvch** [comment]
> > So I do not see how the quality of searx is degraded by the fact that the author of the project is pushing to master directly.
> 
> Sorry if I was misleading .. its not about code quality, its more about finding best solution in the team and sharing knowledge in the discussion.

I see what you mean. I've checked the closed PRs in searx, and I believe @asciimoo had opened a PR when it was necessary to gather our feedback or share knowledge. I don't think it is required for him to open a separate PR for every small bugfix. For significant architectural changes either in searx or the documentation, I am OK with him opening a PR. But in the past, he did so. Furthermore, I don't think if anything he commits is untouchable. :D You can still comment on a commit and start a discussion there, or open an issue/pull request. To me, @asciimoo seemed like a reasonable person, who is open to suggestions about his work. :)

Regarding the knowledge-sharing aspect, you are right. We should all have a bit more empathy toward one another. We should consider that others might not have the same context and perspective on the problem or feature we are working on, so we should all strive to be a bit more verbose in both our commit messages and PR descriptions. Hence, I would instead go for him writing more verbose commit messages.

**Comment by HLFH** [comment]
Thanks to the team and `searx` community, and the whole discussion we had, as well as the [PR template & contribution guidelines](https://github.com/asciimoo/searx/pull/2038), I can thank everyone and say:

**That was tough**
![](https://i.imgur.com/rDFmzhO.gif)

....


....

**but we did it!**
 ![](https://media.giphy.com/media/QWwEdgDbYjFbfOMJ3z/giphy.gif)
