### ISSUE TITLE
Im trying to host my own instance but i get this error

### ISSUE THREAD

**Issue by cassanof** [searx/searx#2040]
Engines cannot retrieve results:

google (unexpected crash CAPTCHA required)

how can i fix this?
googling this issue i can only find people that are not hosting their instance but using other instances.

**Comment by dalf** [comment]
See https://github.com/asciimoo/searx/issues/729

**Comment by cassanof** [comment]
yeah, i saw that, so whats the solution? i am not hosting the instance on my pc but on a dedicated server.

**Comment by dalf** [comment]
Google has put your dedicated server IPs on a bot list.
The only solution is to change your provider (or use different IP addresses using proxies).
If the instance is public be sure to use [filtron](https://github.com/asciimoo/filtron/) or ( [antibot-proxy](https://github.com/unixfox/antibot-proxy) )

**Comment by return42** [comment]
To setup a fully equipped instance (incl. morty & filtron) for public usage, I recommend to read our new [installation description](https://asciimoo.github.io/searx/admin/installation.html). An searx instance always needs maintenance, especially the bot blocker need some care.

**Comment by unixfox** [comment]
Unfortunately there is no magic solution for this problem.

If you are running a public instance of Searx, you may use filtron or antibot-proxy like dalf said but it's not certain that it will fully solve this problem.
But if it's a private instance then try host it on a provider that has a good reputation because your IP may be in an IP block that is often blacklisted by Google.

**Comment by silvernode** [comment]
@elleven11 I just have my instance use Startpage instead of Google since startpage queries Google anyway. This is has been a pretty good workaround for me and has lasted over a year now. I hope that a note is placed in the searx preferences in future releases that warns users about the captcha issue and disclaims that using Google has the risk of not working properly.

**Comment by cassanof** [comment]
i just wanted to note that with 0.17 the captcha problem disappeared. P.S. the private engines feature is amazing, keep up the good work.
you should open a donation crypto wallet or something, i think alot of people want to donate to the project, including me.

**Comment by asciimoo** [comment]
@elleven11 thanks for your feedback and also for your kind words. We accept donations using opencollective: https://opencollective.com/searx .
