### ISSUE TITLE
Release v0.17.0

### ISSUE THREAD

**Issue by asciimoo** [searx/searx#2047]
I'd like to release a new version in the following days. Are there any open PR/issue that should be part of this new release?

Also, note that we're going to drop py2 support with this release.

**Comment by return42** [comment]
May be the revise of the google engine? https://github.com/asciimoo/searx/pull/1985

**Comment by asciimoo** [comment]
Good idea, google engine fixes should be the part of the release, but #1985 is still very messy and addresses quite a few different topics, so I'm not sure if I can review it in the next couple of days.

**Comment by return42** [comment]
> is still very messy and addresses quite a few different topics

yes, we discussed this / sorry ..  beyond the noise from my site, its a review of all google engines .. there are also fixes to the fetched languages, since the fetch from google was also broken, not only the search.  The patches are not straight forward since I also tried to harmonize the implementation of the different google engines .. and when all was finished, the google-news HTML has changed 24ed1227e5 :-o

Today I started a new (paid) project / sorry that I have no time ATM to rebase and sort the patches new.

**Comment by asciimoo** [comment]
> Today I started a new (paid) project / sorry that I have no time ATM to rebase and sort the patches new.

No worries, I'm trying to find a quick solution to fix the engines and when we will have enough time we can refine #1985 .

**Comment by hubertbanas** [comment]
Can we please have it pushed to https://pypi.org/project/searx as well?

**Comment by asciimoo** [comment]
Yup, going to do it tonight.

**Comment by asciimoo** [comment]
Done: https://pypi.org/project/searx/0.17.0/

**Comment by return42** [comment]
What are the use cases for the pypi packages .. I mean, [searx addresses a moving target (parsing changed result lists from origin search engines) "breaking bugs" could pop up every day and has to be fixed ASAP.](https://github.com/asciimoo/searx/issues/1792#issuecomment-570203111)
