### ISSUE TITLE
Sometimes Searx returns no results

### ISSUE THREAD

**Issue by resynth1943** [searx/searx#2053]
![image](https://user-images.githubusercontent.com/49915996/87059189-ea01da80-c200-11ea-893e-1174fa2fea98.png)

If you're a user of Searx, you've most likely seen the above error message numerous times.

However, this has raised my curiosity: if this appears, prompting a search again *will* bring results. I'm not sure how exactly Searx's results crawling algorithm works, but perhaps it would be viable to implement some sort of retry system?

Thanks,
Resynth

**Comment by unixfox** [comment]
I can't get the hands of the similar issue to this one but I think someone in the past asked to display the error instead of returning "no results" just like it was the case 1 year ago.

A retry mechanism won't help because most of the time the engine is just blocking all the requests so no matter what searx will just get a "block page".

If the second search give a result then it's probably a parsing issue.

**Comment by Kellegram** [comment]
Hmmm, I get this error regularly sadly, sometimes every other search. I thought it was Google blocking, but I tried just using one(different) engine, tried a few, no change. It randomly starts happening often.

**Comment by resynth1943** [comment]
That's weird...

**Comment by MarcAbonce** [comment]
I think it can be because the engines may respond slightly after the [2 second timeout that searx has set by default](https://github.com/asciimoo/searx/blob/master/searx/settings.yml#L43) has passed. So, when you repeat the search right afterwards, searx requests the same query to the engines which would then respond faster since the results are now cached for a while. But I haven't tested this yet, so it's pure conjecture.

**Comment by ghost** [comment]
This is constant, especially lately. It can take 5+ attempts to get a result, and the next search the same. Google is disabled.

**Comment by qbitroot** [comment]
Maybe default timeout should be increased :thinking:

**Comment by ghost** [comment]
No, it makes no difference.

**Comment by andrew6838** [comment]
google and major engines doesn't allow third party to use their results without permit, right?
and have limitation a day?
so where can get the search results ?

**Comment by unixfox** [comment]
> google and major engines doesn't allow third party to use their results without permit, right?

They only allow that through their paid API services.

> and have limitation a day?

There is no limitation but according to their terms of service it's prohibited to automate the searches on their platform. If they detect that behavior then they block you from their platform.

> so where can get the search results ?

For google you have to make it so Google doesn't think that you are doing automated searches. It's tricky for a public searx instance but not if you are running your own private searx instance because you will be the only one doing some requests and this won't trigger their detection system.

**Comment by andrew6838** [comment]
> > google and major engines doesn't allow third party to use their results without permit, right?
> 
> They only allow that through their paid API services.
> 
> > and have limitation a day?
> 
> There is no limitation but according to their terms of service it's prohibited to automate the searches on their platform. If they detect that behavior then they block you from their platform.
> 
> > so where can get the search results ?
> 
> For google you have to make it so Google doesn't think that you are doing automated searches. It's tricky for a public searx instance but not if you are running your own private searx instance because you will be the only one doing some requests and this won't trigger their detection system.

what about bing and other majoy engines?  those are like that?

**Comment by andrew6838** [comment]
how meta search engines work?  like www.metacrawler.com
they paid for their API service?  heard that google not allow to mix  other search results by google terms, is it?

**Comment by dalf** [comment]
About metacrawler: if I search for ```ifconfig.me``` or ```ifconfig.co```, I can see Microsoft IP addresses, so I guess this website is using the Bing API.

**Comment by andrew6838** [comment]
> About metacrawler: if I search for `ifconfig.me` or `ifconfig.co`, I can see Microsoft IP addresses, so I guess this website is using the Bing API.

they get results from google, bing , etc.

**Comment by unixfox** [comment]
> > About metacrawler: if I search for `ifconfig.me` or `ifconfig.co`, I can see Microsoft IP addresses, so I guess this website is using the Bing API.
> 
> they get results from google, bing , etc.

Where do you see that they get results from google or other engines? I only see "Some results by Microsoft" at the bottom of the page which indicate that it's probably pretty much only Bing results.

**Comment by tootbrute** [comment]
> ![image](https://user-images.githubusercontent.com/49915996/87059189-ea01da80-c200-11ea-893e-1174fa2fea98.png)
> 
> If you're a user of Searx, you've most likely seen the above error message numerous times.
> 
> However, this has raised my curiosity: if this appears, prompting a search again _will_ bring results. I'm not sure how exactly Searx's results crawling algorithm works, but perhaps it would be viable to implement some sort of retry system?
> 
> Thanks,
> Resynth

I always get this 'error' on my first search on my self-hosted searx everytime. i think this is super common.

**Comment by unixfox** [comment]
> > ![image](https://user-images.githubusercontent.com/49915996/87059189-ea01da80-c200-11ea-893e-1174fa2fea98.png)
> > If you're a user of Searx, you've most likely seen the above error message numerous times.
> > However, this has raised my curiosity: if this appears, prompting a search again _will_ bring results. I'm not sure how exactly Searx's results crawling algorithm works, but perhaps it would be viable to implement some sort of retry system?
> > Thanks,
> > Resynth
> 
> I always get this 'error' on my first search on my self-hosted searx everytime. i think this is super common.

If you are self-hosting the instance then you can take a look at the logs and find the related error then try to fix it because "no results" is commonly produced by an error in an engine.

**Comment by tootbrute** [comment]
> If you are self-hosting the instance then you can take a look at the logs and find the related error then try to fix it because "no results" is commonly produced by an error in an engine.

hmm
in this log: /var/log/nginx/searx.arkadi.one-error.log (but seems unrelated to search)
`
2020/10/06 14:30:07 [error] 23517#23517: *76461 open() "/usr/share/nginx/html/ynhtheme/custom_overlay.css" failed (2: No such file or directory), client: 210.59.52.254, server: searx.arkadi.one, request: "GET /ynhtheme/custom/_overlay.css HTTP/2.0", host: "searx.arkadi.one"`

in this log: /var/log/uwsgi/app/searx.log

`WARNING:searx.search:engine timeout: wikidata
WARNING:searx.search:engine timeout: wikipedia
WARNING:searx.search:engine timeout: bing
WARNING:searx.search:engine timeout: google
[pid: 1078|app: 0|req: 330/1589] 210.59.52.254 () {54 vars in 1011 bytes} [Tue Oct  6 14:28:53 2020] POST / => generated 12169 bytes in 3475 msecs (HTTP/2.0 200) 3 headers in 117 bytes (1 switches on core 0)
ERROR:searx.search:engine wikipedia : HTTP requests timeout(search duration : 7.09570908546 s, timeout: 3.0 s) : Timeout
ERROR:searx.search:engine bing : HTTP requests timeout(search duration : 7.25860095024 s, timeout: 3.0 s) : Timeout
ERROR:searx.search:engine google : HTTP requests timeout(search duration : 7.28545808792 s, timeout: 3.0 s) : Timeout
ERROR:searx.search:engine wikidata : HTTP requests timeout(search duration : 8.10509490967 s, timeout: 3.0 s) : Timeout
WARNING:searx.search:engine timeout: wikidata
WARNING:searx.search:engine timeout: bing
WARNING:searx.search:engine timeout: wikipedia
WARNING:searx.search:engine timeout: google
[pid: 1079|app: 0|req: 476/1590] 210.59.52.254 () {54 vars in 1011 bytes} [Tue Oct  6 14:29:01 2020] POST / => generated 12169 bytes in 46187 msecs (HTTP/2.0 200) 3 headers in 118 bytes (2 switches on core 0)
ERROR:searx.search:engine google : requests exception(search duration : 46.2925140858 s, timeout: 3.0 s) : HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: /search?q=searx+log+files&start=0&gws_rd=cr&gbv=1&lr=lang_en-GB&hl=en-GB&ei=x (Caused by SSLError(SSLError("bad handshake: SysCallError(-1, 'Unexpected EOF')",),))
Traceback (most recent call last):
  File "/opt/yunohost/searx/searx/search.py", line 160, in search_one_http_request_safe
    search_results = search_one_http_request(engine, query, request_params)
  File "/opt/yunohost/searx/searx/search.py", line 93, in search_one_http_request
    response = send_http_request(engine, request_params)
  File "/opt/yunohost/searx/searx/search.py", line 77, in send_http_request
    return req(request_params['url'], **request_args)
  File "/opt/yunohost/searx/searx/poolrequests.py", line 133, in get
    return request('get', url, **kwargs)
  File "/opt/yunohost/searx/searx/poolrequests.py", line 109, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/opt/yunohost/searx/local/lib/python2.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/yunohost/searx/local/lib/python2.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/opt/yunohost/searx/local/lib/python2.7/site-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
SSLError: HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: /search?q=searx+log+files&start=0&gws_rd=cr&gbv=1&lr=lang_en-GB&hl=en-GB&ei=x (Caused by SSLError(SSLError("bad handshake: SysCallError(-1, 'Unexpected EOF')",),))
ERROR:searx.search:engine bing : HTTP requests timeout(search duration : 46.5615541935 s, timeout: 3.0 s) : Timeout
ERROR:searx.search:engine wikidata : HTTP requests timeout(search duration : 47.4611840248 s, timeout: 3.0 s) : Timeout
ERROR:searx.search:engine wikipedia : HTTP requests timeout(search duration : 47.6614940166 s, timeout: 3.0 s) : Timeout
[pid: 1079|app: 0|req: 477/1591] 210.59.52.254 () {54 vars in 1011 bytes} [Tue Oct  6 14:30:04 2020] POST / => generated 22633 bytes in 2574 msecs (HTTP/2.0 200) 3 headers in 309 bytes (1 switches on core 0)
[pid: 1079|app: 0|req: 478/1592] 210.59.52.254 () {54 vars in 1013 bytes} [Tue Oct  6 14:33:26 2020] POST / => generated 22902 bytes in 1346 msecs (HTTP/2.0 200) 3 headers in 304 bytes (1 switches on core 0)
[pid: 1078|app: 0|req: 331/1593] 210.59.52.254 () {48 vars in 877 bytes} [Tue Oct  6 14:38:42 2020] GET / => generated 9704 bytes in 27 msecs (HTTP/2.0 200) 3 headers in 114 bytes (1 switches on core 0)
[pid: 1078|app: 0|req: 332/1594] 210.59.52.254 () {48 vars in 986 bytes} [Tue Oct  6 14:38:43 2020] GET /static/fonts/glyphicons-halflings-regular.woff => generated 23320 bytes in 4 msecs via sendfile() (HTTP/2.0 200) 9 headers in 330 bytes (0 switches on core 0)
Tue Oct  6 14:38:43 2020 - SIGPIPE: writing to a closed pipe/socket/fd (probably the client disconnected) on request /static/themes/oscar/img/favicon.png (ip 210.59.52.254) !!!
Tue Oct  6 14:38:43 2020 - uwsgi_response_write_headers_do(): Broken pipe [core/writer.c line 248] during GET /static/themes/oscar/img/favicon.png (210.59.52.254)
IOError: write error
[pid: 1078|app: 0|req: 333/1595] 210.59.52.254 () {46 vars in 852 bytes} [Tue Oct  6 14:38:43 2020] GET /static/themes/oscar/img/favicon.png => generated 0 bytes in 5 msecs (HTTP/2.0 200) 9 headers in 0 bytes (0 switches on core 0)
[pid: 1078|app: 0|req: 334/1596] 210.59.52.254 () {54 vars in 1011 bytes} [Tue Oct  6 14:38:47 2020] POST / => generated 22587 bytes in 2416 msecs (HTTP/2.0 200) 3 headers in 308 bytes (1 switches on core 0)
[pid: 1078|app: 0|req: 335/1597] 210.59.52.254 () {48 vars in 877 bytes} [Tue Oct  6 14:38:57 2020] GET / => generated 9704 bytes in 15 msecs (HTTP/2.0 200) 3 headers in 114 bytes (1 switches on core 0)
[pid: 1078|app: 0|req: 336/1598] 210.59.52.254 () {54 vars in 1011 bytes} [Tue Oct  6 14:39:05 2020] POST / => generated 21373 bytes in 1487 msecs (HTTP/2.0 200) 3 headers in 306 bytes (1 switches on core 0)
`
some timeout stuff in there i guess... any suggestions to make it work better?

**Comment by seniorm0ment** [comment]
I've been getting this very often recently these past 2 weeks, tried across like 4 different instances. Two of these instances used to work perfectly fine almost regularly. (Searx.be searx.monicz.pl) and the other two I just added.

Sometimes they work if you just keep hitting enter on the results, and other times they just refuse to provide any results.

**Comment by unixfox** [comment]
@grravity When an engine (for example Google) stop working for a few times then Searx disable it temporally which cause this "no results" bug.

As a searx.be maintainer, I'm actively trying to fix this issue.

-------------------------

Maybe @dalf we could for example print a message stating that x engines are banned for x amount of time. This would be a better explanation to the user than just "no results".

**Comment by dalf** [comment]
<details><summary>Technical note</summary>
<p>

https://github.com/searx/searx/blob/484dc99580a4cfdbba022209cbe896cd69b3e8b2/searx/search/processors/online.py#L44-L47

Before return 
```python
result_container.add_unresponsive_engine(self.engine_name, 'Engine suspended')
```

Actually it would be better to record why the engine has been suspended.

Also the suspend time should be shared between the workers using `searx.shared`, so when an engine is suspended, it is suspended.

</p>
</details>

**Comment by seniorm0ment** [comment]
@unixfox ah okay, yeah that sucks. Is there a reason why it doesn't just keep retrying?

**Comment by unixfox** [comment]
> @unixfox ah okay, yeah that sucks. Is there a reason why it doesn't just keep retrying?

There is a retry system in place but if the system doesn't get a proper response (not a block) from Google under 10 seconds then it stops trying and serve no results.

Don't worry I'm well aware of the situation, I've some plans for fixing this issue, but it takes time.

**Comment by dzimbeck** [comment]
This is easy to reproduce, just disable yahoo, bing, duckduckgo and then enable something like Yandex and Startpage. It will fail almost 100% of the time which means this tool doesn't even work. What is worse is that there is only a few crawlers left in the world (such as bing and google) and most other searches (like duckduckgo) use bing or google. Gigablast for example is one of the last independent non big tech crawlers but try adding it and it always fails. If these issues aren't fixed then searx is literally pointless. By the way, searching a 2nd time does not bring results if you do the above. It will ALWAYS fail this way. I think it doesn't even pull from a majority of the sites it claims it can pull from.

**Comment by tootbrute** [comment]
> This is easy to reproduce, just disable yahoo, bing, duckduckgo and then enable something like Yandex and Startpage. It will fail almost 100% of the time which means this tool doesn't even work. What is worse is that there is only a few crawlers left in the world (such as bing and google) and most other searches (like duckduckgo) use bing or google. Gigablast for example is one of the last independent non big tech crawlers but try adding it and it always fails. If these issues aren't fixed then searx is literally pointless. By the way, searching a 2nd time does not bring results if you do the above. It will ALWAYS fail this way. I think it doesn't even pull from a majority of the sites it claims it can pull from.

Yes! So true. This is why I wish yacy integrated more easily with Searx

**Comment by unixfox** [comment]
> This is easy to reproduce, just disable yahoo, bing, duckduckgo and then enable something like Yandex and Startpage. It will fail almost 100% of the time which means this tool doesn't even work. What is worse is that there is only a few crawlers left in the world (such as bing and google) and most other searches (like duckduckgo) use bing or google. Gigablast for example is one of the last independent non big tech crawlers but try adding it and it always fails. If these issues aren't fixed then searx is literally pointless. By the way, searching a 2nd time does not bring results if you do the above. It will ALWAYS fail this way. I think it doesn't even pull from a majority of the sites it claims it can pull from.

Yandex got removed so that's normal that it doesn't work anymore.

Searx is maintained by volunteers, we work on our free time we can't fix every existing instance. We are just two active developers, it's just humanly not possible to work on everything.

You are free to fix the issue about gigablast yourself then create a pull request on the repository. We will then take a look and merge it.

**Comment by dzimbeck** [comment]
I totally understand what it's like to develop alone. Still though, my point is the world desperately needs decentralized search. More critically uncensored search. All the engines this supports are actually Bing and Google by proxy. This is because none of the other engines you list have their own crawlers. Duckduckgo is bing/google. Yahoo is bing/google. Yandex is not because it's a russian engine. Some of the other things on the list like Gigablast do actually crawl on their own. Also as tootbrute mentioned Yacy. However Yacy if I recall is only downloadable. So independent crawlers are really critical to build support for. The entire freedom of the internet and freedom of speech is at stake. I could commit to help however unfortunately I'm stuck coding other projects.

**Comment by RennisDitchie** [comment]
I am also running into this issue as well as I am receiving the "Sorry! we didn't find any results. Please use another query or search in more categories." error.

I run Searx on an Nginx server on a Debian 10 VPS on Digital Ocean as a reference, and used the self-installation scripts to deploy it a few months ago.

So far, I have disabled any Google entries from the /etc/searx/settings.yml configuration file by using "disabled: True" under each Google based entry present since the Google Captcha issue was causing the search engine to just not work at all.

Thank you for the explanations above in this issue as to the overarching issue present. I am a big fan of some of the comments above because like others here, I think Searx and what it stands for to fight against growing internet censorship and forced ad-tracking, and think it is an awesome project overall. Good to see I'm not the only one who's a fan of this kind of thing.

For the time being, I wiped the logs from '/var/log/uwsgi' directory to see if I get a fresh set of logs that would populate later today sometime (unless I'm mistaken though, please let me know if I should have kept the log file present :/, might have been a mistake on my part as I assumed logs would be written again later today).

Just wanted to comment here to give an example of this issue from an Nginx user's perspective.

**Comment by SlidingHorn** [comment]
I'm getting this a lot on my personal instance where I'm the only person using it, so I have no idea how other instances that actually have users manage to work in any meaningful way. What do they do differently?

```
ERROR:searx.search.processor.online:engine google : Too many requests
Traceback (most recent call last):
  File "/usr/local/searx/searx-src/searx/search/processors/online.py", line 139, in search
    search_results = self._search_basic(query, params)
  File "/usr/local/searx/searx-src/searx/search/processors/online.py", line 119, in _search_basic
    response = self._send_http_request(params)
  File "/usr/local/searx/searx-src/searx/search/processors/online.py", line 91, in _send_http_request
    response = req(params['url'], **request_args)
  File "/usr/local/searx/searx-src/searx/network/__init__.py", line 126, in get 
    return request('get', url, **kwargs)
  File "/usr/local/searx/searx-src/searx/network/__init__.py", line 119, in request
    raise_for_httperror(response)
  File "/usr/local/searx/searx-src/searx/network/raise_for_httperror.py", line 65, in raise_for_httperror
    raise SearxEngineTooManyRequestsException()
searx.exceptions.SearxEngineTooManyRequestsException: Too many request, suspended_time=3600
```

I'd *like* to keep google results if at all possible, but if I'm going to get put on time out for an hour every time I do a few consecutive searches, that's going to be a problem.

**Comment by unixfox** [comment]
> I'm getting this a lot on my personal instance where I'm the only person using it, so I have no idea how other instances that actually have users manage to work in any meaningful way. What do they do differently?
> 
> ```
> ERROR:searx.search.processor.online:engine google : Too many requests
> Traceback (most recent call last):
>   File "/usr/local/searx/searx-src/searx/search/processors/online.py", line 139, in search
>     search_results = self._search_basic(query, params)
>   File "/usr/local/searx/searx-src/searx/search/processors/online.py", line 119, in _search_basic
>     response = self._send_http_request(params)
>   File "/usr/local/searx/searx-src/searx/search/processors/online.py", line 91, in _send_http_request
>     response = req(params['url'], **request_args)
>   File "/usr/local/searx/searx-src/searx/network/__init__.py", line 126, in get 
>     return request('get', url, **kwargs)
>   File "/usr/local/searx/searx-src/searx/network/__init__.py", line 119, in request
>     raise_for_httperror(response)
>   File "/usr/local/searx/searx-src/searx/network/raise_for_httperror.py", line 65, in raise_for_httperror
>     raise SearxEngineTooManyRequestsException()
> searx.exceptions.SearxEngineTooManyRequestsException: Too many request, suspended_time=3600
> ```
> 
> I'd *like* to keep google results if at all possible, but if I'm going to get put on time out for an hour every time I do a few consecutive searches, that's going to be a problem.

We can't do anything about this. Please refer to https://github.com/searx/searx/issues/729

----------

Closing as we now displaying what kind of engine failed to work.

**Comment by seniorm0ment** [comment]
just curiously, unless I fail to understand still, why is searx still not displaying the results from the other engines?
sometimes it says an engine errored, other times it states no results were found however if you refresh a few times it finds it. it seems like sometimes if an engine breaks, then it kills all results instead of showing results for engines that did work and just not the ones from the engine that broke?

**Comment by FrancescoSaverioZuppichini** [comment]
same here with google, anyone knows if there is a fix?
