### ISSUE TITLE
How to change ip?

### ISSUE THREAD

**Issue by ah1102** [searx/searx#2093]
I have installed Searx on a remote Debian machine. How can I access SearX from my local computer? I didn't find this in the documentation. On the Internet, most people install Searx on Ubuntu and on their local machine.

**Comment by return42** [comment]
> How can I access SearX from my local computer?

I have a doubt I understand your question .. just type the remote URL in your browser's URL bar?

**Comment by ah1102** [comment]
If I enter `127.0.0.0:8888` on my local machine, a blank page opens as there is no Searx on the local machine.
For example, my remote computer has a public address of `1.1.1.1` and a virtual address of `2.2.2.2`. If I try to replace these two addresses in /usr/local/searx/searx-src/searx/settings.yml, then searx is still not accessible from the local machine.

```
server:
    port : 8888
    bind_address : "127.0.0.1" # address to listen on
    secret_key : "ultrasecretkey" # change this!
    base_url : False # Set custom base_url. Possible values: False or "https://$
    image_proxy : False # Proxying image results through searx
    http_protocol_version : "1.0"  # 1.0 and 1.1 are supported
```

**Comment by return42** [comment]
familiarize with the basics, the architecture is shown here https://asciimoo.github.io/searx/admin/architecture.html .. / sorry that I cant help.

**Comment by unixfox** [comment]
This issue is not related with Searx but just a misunderstanding about networking.

If you are hosting Searx on a remote server then in order to access to it you will need to type the public IP address of that server. You may retreive that through `curl ifconfig.co`.
But if it's behind a home connection then you will first need to port forward the port on your modem then use the public IP address.

@return42 I think you can safely close this issue, it isn't related to Searx at all and the initial author have plently of tutorials on the Internet explaining how networking works.
