### ISSUE TITLE
Invidio.us shutting down, video result replacement options

### ISSUE THREAD

**Issue by ertect** [searx/searx#2161]
Invidio.us has announced it will soon close, here are the alternative instances they provide for when that happens:
https://instances.invidio.us/
  
- yewtu.be should replace invidio.us as source for video look-ups in searx in my experience of the alternatives.
- yewtu.be has been the best instance when you consider all the comprimises in speed/functionality that you have with other instances.
- other popular instances such as invidious.snopyta.org are too slow, or even faster alternatives like invidious.xyz lack the ability to open channel pages, & instead just return an error.

**Comment by unixfox** [comment]
Hello,

I'm the maintainer of yewtu.be.

Unfortunately right now Searx won't work with the API of yewtu.be because it is blocked by the anti bot protection.

Also I don't really want to have my instance included by default in Searx because this could potentially slow it down if too many API requests are made by a bunch of Searx instances.

I still plan to change the invidious instance to yewtu.be on my searx instance (searx.be) though. And I'll allow anyone that have a Searx instance to manually switch to yewtu.be for the invidious engine.

By the way thank you for your kind of words of saying that it's a good invidious instance. I know it requires to have JavaScript enabled in order to visit the instance but that's unfortunately the only way I found for stopping bots and have a stable instance which can load without difficulties a video with DASH 1080p.

**Comment by andrew6838** [comment]
> Hello,
> 
> I'm the maintainer of yewtu.be.
> 
> Unfortunately right now Searx won't work with the API of yewtu.be because it is blocked by the anti bot protection.
> 
> Also I don't really want to have my instance included by default in Searx because this could potentially slow it down if too many API requests are made by a bunch of Searx instances.
> 
> I still plan to change the invidious instance to yewtu.be on my searx instance (searx.be) though. And I'll allow anyone that have a Searx instance to manually switch to yewtu.be for the invidious engine.
> 
> By the way thank you for your kind of words of saying that it's a good invidious instance. I know it requires to have JavaScript enabled in order to visit the instance but that's unfortunately the only way I found for stopping bots and have a stable instance which can load without difficulties a video with DASH 1080p.

Hi ,

your Searx.be is great, can I have source code of it?


Thanks

**Comment by unixfox** [comment]
> Hi ,
> 
> your Searx.be is great, can I have source code of it?
> 
> 
> Thanks
> 

It's a bit of off topic that you are doing right now...

All the source code is the same as the one on the official Searx github except the proxy code which is private due to the fact that it's using some private proxies that I don't want to share. The reason is that I'm getting billed for them every time I use a megabyte of data.

**Comment by FrostKnight** [comment]
Try a different instance, invidio.us has a list of instances you can choose from. :)

**Comment by mrwormo** [comment]
https://invidio.us has closed down since September 1 2020.
While waiting for another solution, invidious engine should be disabled to no longer have an error message in the search results page.

**Comment by unixfox** [comment]
Good idea! Do you mind creating a PR for that @mrwormo?

**Comment by mrwormo** [comment]
@unixfox I can try to find some time later to take a look...

**Comment by tiotrom** [comment]
A suggestion: what if you do not use one single instance, but pull from a list of instances? Similar to what https://github.com/SimonBrazell/privacy-redirect does. This way there are more chances for one to work + you don't put a huge load on one single instance.

**Comment by mrwormo** [comment]
That’s the point of #2451, but right now I’m stuck in git workflow...
