### ISSUE TITLE
Searx gets censored

### ISSUE THREAD

**Issue by GreenLunar** [searx/searx#222]
searx has localization feature which is essential in our English illiterate world.

By my opinion, the main reason Google got higher market share than AltaVista and Yahoo! and MSN was because it provided localized interfaces to many languages.

Maybe some Wikipedia users get payments from Google or NSA.

https://en.wikipedia.org/wiki/Searx

> This page has been deleted. The deletion and move log for the page are provided below for reference.
> - 15:54, 23 December 2014 NawlinWiki (talk | contribs) deleted page Searx (A7: Article about a website, blog, web forum, webcomic, podcast, browser game, or similar web content, which does not indicate the importance or significance of the subject)
> - 15:30, 23 December 2014 NawlinWiki (talk | contribs) deleted page Searx (A7: Article about a website, blog, web forum, webcomic, podcast, browser game, or similar web content, which does not indicate the importance or significance of the subject)

**Comment by Cqoicebordel** [comment]
I think it should be done the other way around : in the page about search engines of Wikipedia, we must first add Searx to the list, then, we could create the page itself.

**Comment by GreenLunar** [comment]
I have found this nylira/prism-break/pull/1123 but searx is not yet in https://prism-break.org/

**Comment by pointhi** [comment]
thats a good idea. Probably someone create this article inside his local namespace, and we could improve that version before publishing it into the wikipedia. (and have a safe-copy if it is deleted again)

Probably, searx is simply unknown for most people, so they think it is irrelevant.

**Comment by Cqoicebordel** [comment]
So you know, searx is in the french wikipedia https://fr.wikipedia.org/wiki/Searx . Maybe everyone of you could create a page in his/her language ?
When there are a few translations, they wouldn't delete it in english, I hope.

I also added searx in the external links of https://en.wikipedia.org/wiki/Metasearch_engine . I hope it'll stick.

EDIT : I reviewed the guideline by wikipedia. We must have secondary sources to prove that searx is know outside of our circle. And it shouldn't be written by us, but an user or someone else. So first, we have to be known a bit more...

**Comment by GreenLunar** [comment]
> Probably, searx is simply unknown for most people, so they think it is irrelevant.

No, most of them are, just, dicks who are paid by governmental or private organizations.

> NEWS: Is SquirrelMail "Notable?"
> Jul 23, 2010 by Paul Lesniewski
>   It seems that one Wikipedia user thinks that SquirrelMail is not considered "notable" enough to retain its own Wikipedia page. Do you agree? Disagree? Voice your opinion.
> 
> UPDATE: As of November 2010, SquirrelMail's notability seems to have been commonly agreed upon and the notability warning has been removed. Thanks to everyone who contributed to the discussion and especially those who took it upon themselves to improve the article itself!

https://en.wikipedia.org/wiki/Talk:SquirrelMail#notability
http://squirrelmail.org/

My aunt got payed for several years by a Hasbara (our Ministry of Propaganda) division to write on Wikipedia articles and contents in favor of State of Israel.

EDIT: Reading articles about or related to State of Israel in Hebrew Wikipedia is like reading stories of science fiction, and I am sad to admit it.

**Comment by dalf** [comment]
I'm the author of the deleted articled on the english version of wikipedia.
I saw the french translation, I just translated the content, then it was quickly deleted : I didn't saw the need for secondary sources.

Also, I created the wikidata page (this one is not deleted) : 
https://www.wikidata.org/wiki/Q17639196

**Comment by pointhi** [comment]
@asciimoo I have uploaded the searx-logo to wikimedia-commons, but I don't know what licencing the logo has, so please update that: https://commons.wikimedia.org/wiki/File:Searx_logo.svg

Furthermore, we should uploade a more recitfied logo without the useless whitespace.

#### EDIT

I have set AGPL as licence. If thats not the right licence, please change. (Because searx is licenced by AGPL, and there is no other licence information)

**Comment by GreenLunar** [comment]
Potential places to spread searx at:
https://wiki.archlinux.org/index.php/Squirrelmail
http://www.yacy-websearch.net/wiki/index.php/En:Seeks
~~http://directory.fsf.org/wiki/Searx~~ (Seeks is missing too)
http://directory.fsf.org/wiki/Searx.me_search
http://directory.fsf.org/wiki/Collection:PRISM

**Comment by asciimoo** [comment]
@pointhi http://creativecommons.org/licenses/by-sa/4.0/ fits best, also we need to extend the license file. Could you update the wikimedia info?

**Comment by pointhi** [comment]
I have deployed the german translation of the wikipedia entry regarding to searx: https://de.wikipedia.org/wiki/Searx. Last time I have done it (Oct 14) it was deleted because of no relevance criteria. I think I have fixed that.

**Comment by asciimoo** [comment]
@pointhi <3
Impressive article (even with my basic german knowledge =) )! Just a small note: https://searx.me/ isn't an official instance, it's just a demo (and my public) instance. Calling it official feels like it's better than other instances what may force users to use searx.me instead of run their own instance. One of the best features of searx is that it is not centralized.

**Comment by Cqoicebordel** [comment]
That is a question I wanted to ask you @asciimoo : is it ok to give the searx.me url to everyone who want to test/use searx ? I'm asking if the size of the server is ok.

And I think we feel that searx.me is the official one, is because it's yours, the creator/maintener of searx, and it is the instance always the most up to date :)

**Comment by asciimoo** [comment]
@Cqoicebordel there is (yet =]) no technical problem with it, rather philosophical what i mentioned

**Comment by pointhi** [comment]
Ok, the german wiki entry was deleted. Because I had the suspicion that this happens, I saved the document in my own user-space: (https://de.wikipedia.org/wiki/Benutzer:Pointhi/searx).

It looks like, [the main problems are](https://de.wikipedia.org/wiki/Wikipedia:L%C3%B6schpr%C3%BCfung#searx):
- the article is written from an innnen view. Probably, because most references pointing to GitHub, and the other one to a german installation instruction. I have not found any reference to searx, where the main visitors are not something like opensource programmers.
- we don't have much references yet, specifically inside bigger news portals like the german IT-Portal heise.de. I have written a short letter to heise.de, so they know about searx, and probably take it into account if they writing something about search-engines.

**Comment by dalf** [comment]
Open parenthesis

Searching for "searx" on twitter, I found those references in russian : 
- http://hostink.ru/news/searx_0-7/
- http://www.nixp.ru/news/13172.html
- http://novostey.com/soft/news654053.html

Close parenthesis

(I know, it's not useful for the german version)

**Comment by Cqoicebordel** [comment]
So the question are :
- Is searx good enough for public use ?
- Is searx good enough for non geek users ?
- How to raise awareness of searx ? And should we yet ?

I think we need to work on boring stuff like documentation and creating installation process that are easier (.deb/.rpm ?) to ease the installation and use of searx. Then, and only then, we should advertise the existence of searx.

For me, the todo list is this :
- Streamline the workflow
- Ameliorate substantialy the docs (readability, non-geek-proof, explain possible choices etc.)
- Create a website to present the project, maybe with a forum (we need a better way to communicate and exchange ideas than creating github issues). Having Github as the face of the project is not great for non-tech users.
- Ameliorate the UX and the UI still. Espacially the UI, I think (and it's only my opinion), that we lack something in searx, maybe a bit of eye candy. For example, the index page of courgette is better than oscar, but oscar is better for the results as UX. Anyway, this is my two cents. We need somebody that has experience in this domain.

And then we could raise awareness, become really public, because we will have something that is not hacky anymore but a stable piece of software.  
Maybe for the v1.0 ? ;)

**Comment by asciimoo** [comment]
@Cqoicebordel, totally agree on the todos.

**Comment by pointhi** [comment]
@Cqoicebordel I'm also agree with this todos.

The idea with an official site is very good. Probably something based on a python CMS including blog, forum and custom apps like my stats-site.

**Comment by GreenLunar** [comment]
I suggest to point out the set of [engines](https://github.com/asciimoo/searx/tree/master/searx/engines) that searx provides.

Please help me spread searx at https://github.com/libreprojects/libreprojects/issues/115

**Comment by GreenLunar** [comment]
PUUUU! HA! HA! HA! [Geographically limited scope](https://en.wikipedia.org/wiki/List_of_search_engines#Geographically_limited_scope).

Ask some of the administrators of the various searx nodes to limit the scope of their results to get in to the biased encyclopedia!

[Money makes Wikipedia go ROUND AND ROUND AND ROUND...](http://noooxml.wikidot.com/forum/t-261047/money-makes-the-wikipedia-go-round)

It is not about _free flow_ of information, it is to canal information for the masses, the way they want to!

Try to insert `[[searx]]` to [Metasearch engines](https://en.wikipedia.org/wiki/List_of_search_engines#Metasearch_engines) section.

**Comment by GreenLunar** [comment]
Oh, yes, try to insert [[searx]] to [Metasearch engines](https://en.wikipedia.org/wiki/List_of_search_engines#Metasearch_engines) section.

**Comment by GreenLunar** [comment]
I have found a good resource that may help us at https://wiki.gnome.org/Engagement

**Comment by GreenLunar** [comment]
I have removed http://metasearchenginewatch.com/ from my bookmarks; there is no mention of Seeks nor searx.

There is an old article (December 1st, 2011) about [YaCy](http://searchenginewatch.com/sew/news/2129521/yacy-introduces-peertopeer-search-engine) by Rob D. Young.

Marketing searx is a difficult mission!

**Comment by GreenLunar** [comment]
> Marketing searx is a difficult mission!

It appears that some even consider it as spam.
https://github.com/The-Compiler/configs/commit/431e7a6d5edd45214046599fa5413efe30995833#commitcomment-13987605

**Comment by aleksejrs** [comment]
> > Marketing searx is a difficult mission!
> 
> It appears that some even consider it as spam.
> [The-Compiler/configs@431e7a6#commitcomment-13987605](https://github.com/The-Compiler/configs/commit/431e7a6d5edd45214046599fa5413efe30995833#commitcomment-13987605)

Those seem to be somebody's personal config files that they shared for anyone interested in them, not a place to suggest your links for.

**Comment by Quix0r** [comment]
That whole "notable" things is asking for being abused to "censor" other services/software/information in general. I'm mostly done with Wikipedia's current totalitarian administrators. It should find its way back to it's roots, being an independent encyclopedia free of "censorship" and other deletions that are not against abuse (like abusing Wikipedia's ranking to boost own website's ranking only).

**Comment by Quix0r** [comment]
Or there is the uncyclopedia (or so) which preserves deleted pages. Is Searx added there?

**Comment by unixfox** [comment]
The original issue was solved in https://github.com/searx/searx/issues/222#issuecomment-73760654.
