### ISSUE TITLE
Should travis build the documentation ?

### ISSUE THREAD

**Issue by dalf** [searx/searx#2258]
Since documentation source is part of the master branch, should the document be built with travis ?

It can be a special an additional stage than run only for the master branch (like the ["docker" stage](https://github.com/searx/searx/blob/e78bfd4d8b62a521e08029bb0e708b2bcec9958d/.travis.yml#L26-L27)).

The avoid useless build the sha of the sources can be comited into the gh-pages.
If the sha is equal to the calculated one in the master branch, then there is no need to build the documentation.

```sh
CURRENT_SHA=$(find docs utils -type f -print | sort | xargs cat | sha256sum)
EXISTING_SHA=$(cat gh-pages/sha.txt)
if [ $CURRENT_SHA != $EXISTING_SHA ]; then
   echo -e "$CURRENT_SHA" > gh-pages/sha.txt
   make gh-pages
fi
```
(not tested, and it won't  work because the gh-pages directory may not exist, but that's the idea)

But the [engine list](https://searx.github.io/searx/admin/engines.html) won't be updated as expected, so a more accurate command is:
```sh
CURRENT_SHA=$(find docs utils searx/engines -type f -print | sort | xargs cat | sha256sum)
```

----

The simple strategy may not work: the help messages of the installation scripts include the local IP of the runner. Most probably it will change over time. I'm not sure about the .svg file too.

**Comment by asciimoo** [comment]
Good idea, +1

**Comment by dalf** [comment]
Some experimentation here : https://github.com/dalf/searx/commit/92c29efb5c245702859d3b32c8ecfa2af5816376 but travis is really slow these last days.

See https://docs.travis-ci.com/user/deployment/pages/

---

From the initial comment, I've created this following script, but any file can change de documentation, so the best solution is most probably to build the documentation after each commit in the master branch.

```sh
#!/bin/bash

CMD=$1

SAVE_FILE="gh-pages/source_sha256.txt"
READLINK="$(which readlink greadlink | tail -n1)"
BASE_DIR="$(dirname -- "`$READLINK -f -- "$0"`")"
cd -- "$BASE_DIR/.."

FILES=$(find requirements-dev.txt requirements.txt Makefile dockerfiles docs utils searx/engines/*.py -type f -print)
CURRENT_SHAS=$(sha256sum ${FILES})

check() {
    if [ -f "${SAVE_FILE}" ]; then
        echo -e "${CURRENT_SHAS}" | cmp -s "${SAVE_FILE}"
        if [ $? -eq 0 ]; then
            echo "gh-pages are up to date"
            exit 0
        fi
    fi
    exit 1
}

update() {
    echo -e "${CURRENT_SHAS}" > "${SAVE_FILE}"
}


case "${CMD}" in
    check) check;;
    update) update;;
    *) echo "Unknow command";;
esac
```

**Comment by return42** [comment]
> so the best solution is most probably to build the documentation after each commit in the master branch.

Shouldn't we (also) enforce contributors to build the documentation before commit? Or we add target `docs` to Makefile's `test` target?

https://github.com/searx/searx/blob/db703a0283ee169381aeea97c678e666ae508348/Makefile#L214

**Comment by dalf** [comment]
> Shouldn't we (also) enforce contributors to build the documentation before commit? Or we add target docs to Makefile's test target?

If travis (or a script) can't check the documentation has been updated, how to make sure it has been done with the right configuration ?

Unfortunately, this is not easy because the output files change even if there is no change in the source files (there is the same issue with the js/css files built by the npm scripts).

See https://github.com/searx/searx/commits/gh-pages 
For example, the bottom of this page https://searx.github.io/searx/utils/searx.sh.html the IP address is the local IP address of the host which has built the documentation. Another example, the secretkey in [this page](https://searx.github.io/searx/admin/installation-searx.html#configuration) changes each time.

**Comment by return42** [comment]
@dalf / may I was misleading or I misunderstood you. What I mean: We already enforce (encourage) our contributors:

-  [Check if your code breaks existing tests. If so, update the tests or fix your code](https://searx.github.io/searx/dev/contribution_guide.html#code)
- [make test](https://searx.github.io/searx/dev/makefile.html#make-test)

BTW: the docs can be more clean, if someone is interested in, I can send a PR, making the docs more clear and actual. 

To check if documentation is build, we can additional enforce  (encourage) our contributors to run a `make docs` before commit and pull PR (this will pop up issues like #2278).

> Unfortunately, this is not easy because the output files change even if there is no change in the source files (there is the same issue with the js/css files built by the npm scripts).

The (HTML) output depends on the sphinx version and some random values generated by Sphinx _and additional tools like DOT_, so we can not compare the output from one build with the other build.

How to setup a buildhost with a dedicated tool chain (DOT etc.) is described here: https://searx.github.io/searx/admin/buildhosts.html

> See https://github.com/searx/searx/commits/gh-pages

In https://github.com/searx/searx/commit/9d4d80f62353 a  source_sha256.txt file is added, where does it come from?

I build target `gh-pages` from master branch and did not get this file.

> Another example, the secretkey in this page changes each time.

Yes, this is an issue, fixed by #2277 

> For example, the bottom of this page https://searx.github.io/searx/utils/searx.sh.html the IP address is the local IP address of the host which has built the documentation.

If you think it is an issue we can fix the documentation at this point (I don't think this is an issue since it is an example output).

For me, we have different questions:

1. Should travis build the documentation?

If so, travis (like any other buildhost) should be setup by one command e.g. [sudo -H ./utils/searx.sh install buildhost](https://searx.github.io/searx/admin/buildhosts.html)

2. Should travis deploy the docs (commit the gh-pages) generic?

If so, a `source_sha256.txt ` could help to detect changes in the sources.  Do such changes have an relevant impact to document's content? This question can't be answered error prune in a generic way.

3. Should we encourage our contributors to run a doc build before sending PR?  Just to see if the doc build gets broken by the patch.

**Comment by dalf** [comment]
Different outputs from the same source files are not a problem.

> In 9d4d80f a source_sha256.txt file is added, where does it come from?

This is an unintended push (`make gh-pages`), source_sha256.txt comes from this script: https://github.com/searx/searx/issues/2258#issuecomment-717242877

The problem is we never if a file in the git repository will change the documentation (configuration files, etc...), so in the end we will includes all the files except few of them.

With the commit https://github.com/dalf/searx/commit/2c069c04037b4fd7d0ecb2f778539ddc0e920ba1 travis can build the documentation : 
* https://dalf.github.io/searx/
* https://travis-ci.org/github/dalf/searx/builds/739531540
* in this configuration, travis always build the documentation whatever the branch, but the result is pushed to the [gh-pages branch](https://github.com/dalf/searx/blob/2c069c04037b4fd7d0ecb2f778539ddc0e920ba1/.travis.yml#L53) only on the master branch.
* it does not use `./utils/searx.sh install buildhost`, only `make gh-pages` as before (as I understand). Note: gh-pages doesn't push anymore the files, the deploy section in the .travis.yml ask travis to do it.

**Comment by return42** [comment]
> With the commit dalf@2c069c0 travis can build the documentation
> Note: gh-pages doesn't push anymore the files, the deploy section in the .travis.yml ask travis to do it.

LGTM but I would recommend not to change the (old) 'gh-pages' target since there are users like me, maintain their own forks (incl. gh-pages branch). Do you like to add a target like 'travis-gh-pages'?

> it does not use `./utils/searx.sh install buildhost` only make gh-pages as before (as I understand).

Running 'make docs' (or 'gh-pages') is OK but you might miss some features in the output. ATM we make use of such special features only in the [reST Primer (see Fig. 3 showing the raw text instead an image generated by DOT)](https://dalf.github.io/searx/dev/reST.html#dot-files-aka-graphviz) so it is not a issue right now.

`./utils/searx.sh install buildhost`  assures a full featured build environment (including DOT and `convert` to build & convert images and also includes lint-tools for bash and python).

The concept behind is [Scalable figure and image handling .. Scalable here means; scalable in sense of the build process.](https://return42.github.io/linuxdoc/linuxdoc-howto/kfigure.html).
