### ISSUE TITLE
cant select image section with no js

### ISSUE THREAD

**Issue by brightersun99** [searx/searx#2264]
with js disabled, i cannot change the type of search 
such as pictures, files, etc
clicking them does nothing
this isn't any better than just using google or startpage if i can't do that, both of those work fine without js, same with almsot every other search engine, this project is 6 years old so i am surprised

**Comment by brightersun99** [comment]
and if you think it's "hard" to develop simple stuff without js then you are a failed web developer

**Comment by return42** [comment]
> and if you think it's "hard" to develop simple stuff without js then you are a failed web developer

You are welcome to share your knowledge with the searx community.  Having  a pure CSS page (see [template](https://github.com/searx/searx/tree/master/searx/templates) & [theme](https://github.com/searx/searx/tree/master/searx/static/themes)) would be a great addition .. do you like to prepare a PR for?

**Comment by unixfox** [comment]
I've JS disabled and I can click on the types like you described without any issue.

![Peek 2020-10-16 17-31](https://user-images.githubusercontent.com/4016501/96271581-969be700-0fbc-11eb-891c-3ece1604c504.gif)

@brightersun99 could you share the Searx instance that you are using so that we can try to reproduce the bug on it? If it's a public one obviously.

By the way please be more kind towards the community we aren't your slaves. We work on our own free time and we aren't getting paid. So the least that we are asking is to get some respect.

**Comment by dalf** [comment]
As described above, you can use the searx instances without javascript.
Without more details, I close the issue.
If you see a not hard (easy ?) problem to fix, your PR are welcomed.

---

Side notes: 
* searx.space requires javascript for now (do note that webpack is not used on purpose : searx.space/main.js is readable).
* it will be fixed in the future see https://github.com/searx/searx-stats2/pull/25  
* In the meantime you can use a meta-instance, or fetch the searx.space/data/instances.json URL.
