### ISSUE TITLE
cached link is missing from courgette theme

### ISSUE THREAD

**Issue by GreenLunar** [searx/searx#229]
No **cached** hyperlinks.

**Comment by Cqoicebordel** [comment]
That is a choice of the theme maker.

Some want a fully loaded theme with everything in it (oscar), some prefer something more simple (courgette/default).

**Comment by GreenLunar** [comment]
A good practice for theme makers is to add a switch to enable cache or any other feature that is disabled by default in a theme.

**Comment by Cqoicebordel** [comment]
I strongly disagree.

A theme should be build as the theme maker want it. I could want to build a theme that return only the URL as result and nothing else (no text, no icon, nothing). Or maybe, to the contrary, a map of the favicons of the result sites, without a single word.

My point is, a theme is built with a big eye view (une vue d'ensemble), and shouldn't be subject to other themes bells and whistles, or functions and eyes candy. Even RTL.

I did RTL because I wanted to do it, and did it on all themes because I could and wanted to. But a theme maker can build a theme only for RTL, because some things are better designed from the ground up to the target instead of modifying the existing. And it would serve no purpose to try to adapt this theme to LTR.

Anyway, I strongly disagree ;)

**Comment by GreenLunar** [comment]
> Anyway, I strongly disagree ;)

Do you disagree with adding switches in preferences of a theme?

**Comment by Cqoicebordel** [comment]
No, I disagree on enforcing the good practice you propose, and calling it a good practice.

If someone want to add that switch he is welcome to. But it's the theme creator choice, and no one else.

**Comment by GreenLunar** [comment]
I agree, but I did not propose to enforce, I have just stated that it would be a good practice.
