### ISSUE TITLE
autocompletion fail with base_url

### ISSUE THREAD

**Issue by beudbeud** [searx/searx#244]
I use searx with base_url exemple : https://plop.fr/searx but the autocompletion don't works

i have in settings.yml 
base_url : "https://plop.fr/searx/"

but when i see in dev tools of firefox i have 302 error because it try to get plop.fr/autocompleter?q=

**Comment by Cqoicebordel** [comment]
The base_url works only if you run searx directly through python.  

Are you using uwsgi + apache or nginx ? In that case, the issue is from the web server configuration.  
In Nginx, the conf is described in the wiki, but for Apache, you should have something like that in the conf :  

``` apache
<Location /searx>
    Options FollowSymLinks Indexes
    SetHandler uwsgi-handler
    uWSGISocket /run/uwsgi/app/searx/socket
</Location>
```

EDIT : Sorry, found the issue, that was not the conf, but the JS. I will commit shortly the changes, but if you want to do it yourself, change in the JS files "/autocompleter..." by "./autocompleter..."

**Comment by beudbeud** [comment]
i use nginx + uswgi, i try with master but is don't works
![capture d ecran - 16022015 - 19 14 59](https://cloud.githubusercontent.com/assets/690304/6217048/313130ac-b610-11e4-9630-f2c0bb8b8c2c.png)

**Comment by beudbeud** [comment]
my nginx conf

``` bash
location = /searx { rewrite ^ /searx/; }
location /searx {
        if ($scheme = http) {
                rewrite ^ https://$server_name$request_uri? permanent;
        }
        try_files $uri @searx; }
location @searx {
        uwsgi_param SCRIPT_NAME /searx;
        include uwsgi_params;
        uwsgi_modifier1 30;
        uwsgi_pass unix:///run/uwsgi/app/searx/socket;
}
```

**Comment by Cqoicebordel** [comment]
Have you tried with the last master, from 2 hours ago ?  
It may also be a cache issue. Have you tried to restart the servers, and empty the browser cache ?

Because, right now, I have no idea.

Is it a public instance ? It would be helpful if it was, so I could debug it myself.

**Comment by beudbeud** [comment]
Yes i try the last master

it's a public instance.

you can try on https://beudibox.fr/searx/

**Comment by Cqoicebordel** [comment]
It's not exactly public, it ask me for a login and a password...

**Comment by beudbeud** [comment]
i create account for you user : searxtest
password searx1234

**Comment by Cqoicebordel** [comment]
Ok, I did go to https://github.com/abeudin/searx_ynh to check if the source code was correct. And it seems that you did something very wrong :o)

You updated the source in the wrong place : 
I know it's tricky, but searx at is root has another searx folder. And it seems that you mixed both...
Indeed, for example https://github.com/abeudin/searx_ynh/blob/master/sources/static/themes/oscar/js/searx.min.js is right and updated, because it contains "./autocompleter?q=%QUERY", but searx doesn't look at this file, but look at https://github.com/abeudin/searx_ynh/blob/master/sources/searx/static/themes/oscar/js/searx.min.js which contains "/autocompleter?q=%QUERY", and that was wrong. Note the "searx" in the path.

So if you use that repo, it is indeed normal that it doesn't work ;)

Et si t'as besoin de plus d'aide, je peux aussi le faire en français ;)

**Comment by Cqoicebordel** [comment]
And with the login/pass you gave me, I confirm that it doesn't have the corrected files.

**Comment by beudbeud** [comment]
thanks a lot

i fix the bug the autocompletion works now

**Comment by Cqoicebordel** [comment]
You are welcome :)
I'm happy searx is in YunoHost :)
