### ISSUE TITLE
Hosts filter to block trackers,ads, malware, porn, gambling

### ISSUE THREAD

**Issue by ckorder** [searx/searx#2446]
Hosts filter to block trackers,ads, malware, porn, gambling would be nice to be asked if you want to add it while installing. 

Relating to morty proxy and filter for nsfw

hosts-improvement.sh

> #!/bin/bash
> wget 'https://pgl.yoyo.org/adservers/serverlist.php?hostformat=hosts&showintro=0&mimetype=plaintext' -O list1
> wget 'https://adaway.org/hosts.txt' -O list2
> wget 'https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/gambling-porn/hosts' -O list3
> cp /etc/hosts ./hosts
> cat hosts list1 list2 list3 > newhosts
> sudo mv /etc/hosts  /etc/hosts.backup
> sudo mv newhosts /etc/hosts

An easy install script with questing would be nice!
(Questions first and than no more press key for each step)

**Comment by unixfox** [comment]
Could you confirm that it's a similar idea to https://github.com/searx/searx/issues/2001?

**Comment by ckorder** [comment]
it does not block them from appearing in the search results, but it blocks hosts being displayed by morty proxy. so it protects the searx instance ip going towards  trackers, criminals and advertisement companies and safe the user from being able to surf on porn and gamble sites using morty. (of course it does not block everything but already a lot)

nice side affect is that even non js ads are most of the time no longer displayed while using proxy

**Comment by unixfox** [comment]
We don't really plan to maintain a public whitelist and blacklist and offering it while installing Searx because we want to stay as neutral as possible.

But you are free to create a new GitHub repository with a script that is designed to be installed on a Searx instance and that offer this feature. You may then ask for it to be included in the wiki for example, and we can consider to including it in the installation guide.

Does this satisfy your request?

**Comment by unixfox** [comment]
I'm going to close this issue because we don't plan to implement this kind of script, but I reiterate you are free to do it and then asking it to be included in the wiki.
