### ISSUE TITLE
Deep Web Search support

### ISSUE THREAD

**Issue by ghost** [searx/searx#2455]
**Is your feature request related to a problem? Please describe.**
The current Deep Web search engines like Ahmia are not that good.

**Describe the solution you'd like**
That you can do all the normal things in Searx like searching for music or general,but you can set that it searches through the Deep Web instead of Clear Web.

**Additional context**
That obviously only works if you are using Tor.
It could be hard to achieve,cause I don't know any Deep Web Search Engine that can do all the thing that you can do with Searx.
Also you have to add a good safe mode,so that gore gets blocked,no one wants to see that,I just wanna browse some crappy sites.

**Comment by demostanis** [comment]
" Deep web refers to anything on the internet that is not indexed by and, therefore, accessible via a search engine like Google. Deep web content includes anything behind a paywall or requires sign-in credentials. It also includes any content that its owners have blocked web crawlers from indexing. "
After a simple search on SearX.

**Comment by ghost** [comment]
> Deep web refers to anything on the internet that is not indexed by and, therefore, accessible via a search engine like Google.

Searx doesn't have anything to do with Google and it doesn't support deep web search cause no one implemented it.
> Deep web content includes anything behind a paywall or requires sign-in credentials.

That's total nonsense,most sites need nothing like that,like the [debian deepweb site](http://sejnfjrq6szgca7v.onion/devel/debian-installer/),but some need that,that's the same thing as clear web.
> It also includes any content that its owners have blocked web crawlers from indexing.

That doesn't matter if that's true,cause somehow deepweb search engines like [Ahmia](https://ahmia.fi/) exits and work.

**Comment by demostanis** [comment]
That's called Dark web. And it's already supported (https://github.com/searx/searx/pull/565).
Please use adequate terms and do a little bit of research before opening new issues.

**Comment by unixfox** [comment]
I'm closing this issue because like @demostanis said "Deep Web Search" doesn't really mean anything. If you are asking for a search engine where you can search for content from the Dark Web then please find one and open a corresponding new issue.

Currently, from I can see on https://github.com/searx/searx/pull/565 we already have Ahmia, Torch and Not Evil. If you need more Dark Web search engine support in Searx then please open a new issue with one that you found. Searx is not designed to act as a complete search engine that can search for content on the Dark Web by itself, it has to rely on an external search engine, hence the reason why we call Searx a metasearch engine.

**Comment by ghost** [comment]
ok
