### ISSUE TITLE
Use virtual hosts instead of location blocks

### ISSUE THREAD

**Issue by winux1** [searx/searx#2495]
**Is your feature request related to a problem? Please describe.**
Location blocks in the Apache site configuration file allow less costumizability than virtual hosts and they don't 
support subdomains. So you can not install Searx to a subdomain using the installation scripts. See #2432 and #2480
**Describe the solution you'd like**
I would like to change the Apache and Nginx configuration files from location block to virtual hosts when using the installation scripts.

**Comment by unixfox** [comment]
What are you referring to? The wiki?

Please also use our issue template. It's really important! I just added back the fields so please fill them.

**Comment by winux1** [comment]
@unixfox please remove the doc label

**Comment by unixfox** [comment]
Why? You didn't even answer to my second question. Is it related to the wiki of Searx?

**Comment by unixfox** [comment]
@return42 Can you confirm that we can't install Searx in a subdomain using the official installation scripts?

**Comment by winux1** [comment]
@unixfox Sorry I'm a bit tired.  It is related to the installations scripts not to the docs. There isn't any problem with the docs.

**Comment by return42** [comment]
>  It is related to the installations scripts not to the docs.

It is more or less related to both, the installation scripts do what is documented ;-)

> Can you confirm that we can't install Searx in a subdomain using the official installation scripts?

No, since we do not set Virtualhost for some reasons (see below)

Haven't tested my [prosposal](https://github.com/searx/searx/discussions/2480#discussioncomment-292640) .. @winux1 reported that it does [not work](https://github.com/searx/searx/discussions/2480#discussioncomment-292765) .  The solution @winux1 has been [posted](https://github.com/searx/searx/discussions/2480#discussioncomment-296806) does not really differ from my proposal (if you know how apache configuration works and except that the Virtualhost in this solution listen on port 80 / we won't support unencrypted communication).

Why I think setting Virtualhost is wrong by concept:  The scripts are made to integrate smooth into the different distributions.  

Each distribution does have its own concept of how a service should be set up. If you compare the different distributions you will see that Apache and uwsgi is installed and confgured very different.  By example: [The Debian Layout](https://searx.github.io/searx/admin/installation-apache.html#the-debian-layout) differs totally from what apache recommends.

All the distributions support one default Virtualhost from their packages, to this default Virtualhost you can add your modules or sites (this is what the searx scripts are doing). On all distributions you are free to configure additional (sub-) domains, because it is Apache, but none package from the distributors will maintain it.

I mean, searx installation scripts should be optimized to fit smooth in each distribution we support.  Subdomains are beyond the scope of each distribution and should not the first task of a searx installation script.

> Location blocks in the Apache site configuration file allow less costumizability than virtual hosts and they don't
support subdomains. 

Sorry, this completely wrong, see _context_ in https://httpd.apache.org/docs/2.4/en/mod/core.html#location

How to say it kindly: I have the impression that you have not yet fully understood my proposal.

**Comment by winux1** [comment]
> The solution @winux1 has been posted does not really differ from my proposal (if you know how apache configuration works and except that the Virtualhost in this solution listen on port 80 / we won't support unencrypted communication).

My post only was a example there. Of course I do not use port 80 I use port 443

>Sorry, this completely wrong

Yes I was wrong Location blocks support subbdomains

I completly understood your opinion

Some clsing toughts: I host 3 websites and I never used location blocks becaouse I found difficult to configure them. Now I know the Searx Installation Scripts can not support them but please just write something about  something about Virtual Hosts and subdomains in the documentation I belave it would make some people's life easier.

**Comment by virtadpt** [comment]
@winux1 Not all of us run public instances of Searx.  Or even proxy them through a web server.  I would put forth that adding "how to proxy with a subdomain" would be an addition, not a replacement to the wiki.

**Comment by winux1** [comment]
@virtadpt I agree with you

**Comment by return42** [comment]
Feel free to add a PR documenting how to configure Virtualhost with subdomain, but I think to get subdomain managed some words about DNS are also needed. 

We are a [small team](https://github.com/searx/searx/discussions/2474), please understand  that we have to prioritize. Setting up subdomains is already often documented in the web and adding the [documented `<Location>`](https://searx.github.io/searx/admin/installation-apache.html#apache-reverse-proxy) shouldn't be to hard.

**Comment by unixfox** [comment]
We are going to keep using location blocks for the time being but feel free to open a PR in order to provide documentation for virtual hosts.

If one wants to host Searx under a subdomain without having `/searx` appended to the URL then he can use a full featured solution like searx-docker for that: https://github.com/searx/searx-docker.
