### ISSUE TITLE
It displays Simplified Chinese results if I select "Default"

### ISSUE THREAD

**Issue by laichiaheng** [searx/searx#2537]
**Version of Searx, commit number if you are using on master branch and stipulate if you forked Searx**

**How did you install Searx?**

**What happened?**

If I don't choose zh-TW but choose Default, it shows me lots of Simplified Chinese and Traditional Chinese results.
However, the default language of my browser is zh-TW.
**How To Reproduce**

Search something without selecting searching language.
**Expected behavior**

It shows the results in default language which is zh-TW
**Screenshots & Logs**

All Traditional Chinese if I select zh-TW
![zh-tw](https://user-images.githubusercontent.com/9532105/107113321-46150600-6899-11eb-9378-a5a4056e4aa4.png)
There are Simplified Chinese if I select Default
![default](https://user-images.githubusercontent.com/9532105/107113322-47463300-6899-11eb-9b4e-2f0c3bdc85ea.png)

**Additional context**

**Comment by dalf** [comment]
I'm not sure why the issue is closed.

I don't speak / write Chinese, so I'm may wrong: car is 汽車 in traditional chinese, and 汽车  in simplified chineese (?)

If I search for 汽車 using the zh-TW language preference:
* google results contain mostly 汽車 and some with 汽车. It seems google.com.tw behave in the same way (???). If it is the case, nothing can be done.
* wikipedia & wikidata return results about 汽车. If I understand correctly, to get the traditional version of the article, the link should be
	* https://zh.wikipedia.org/zh-hant/汽車 or https://zh.wikipedia.org/zh-hant/汽车
	* and not https://zh.wikipedia.org/wiki/汽车 as it is the case now.

Here most probably, something can be done.

ping @MarcAbonce

**Comment by unixfox** [comment]
Could also be an issue from the engine, in this case Google.

**Comment by laichiaheng** [comment]
Google sucks.....

**Comment by MarcAbonce** [comment]
I just made #2554 for the Wikipedia issue.

About the "Default" language option, the problem is that it simply doesn't send any language preference to the engine, so the engine will return results in whatever languages it wants.
