### ISSUE TITLE
update searx if using virtual-env installation?

### ISSUE THREAD

**Issue by pointhi** [searx/searx#261]
I have installed searx like described in https://github.com/asciimoo/searx/wiki/Installation, but I haven't figured out how to update it properly. Because of that I was forced to reinstall searx to become the new requests package.

Can someone update the instructions, and add instructions how to update searx with virtual-env? I haven't figured out how to update the packages.

thx, pointhi

**Comment by dalf** [comment]
``` sh
pip install --upgrade -r requirements.txt
```

should help.

**Comment by Cqoicebordel** [comment]
In the virtual-env environement of course.

**Comment by dalf** [comment]
I've updated the page : https://github.com/asciimoo/searx/wiki/Installation#how-to-update
not tested.

More over, since we are talking about privacy : 
https://thomas-leister.de/open-source/linux/server/searx-ip-adressen-im-uwsgi-log-anonymisieren/

which means to add to nginx configuration (TODO : apache ) :

```
uwsgi_param REMOTE_ADDR 127.0.0.1;
```

and uwsgi configuration : 

```
disable-logging = true
```

Another point, why not create script that update a searx instance ?

**Comment by kvch** [comment]
Closing as it has been inactive. Feel free to reopen if needed.
