### ISSUE TITLE
move away from transifex

### ISSUE THREAD

**Issue by xinomilo** [searx/searx#268]
well, just wanted to point out that transifex is proprietary software. 
https://github.com/transifex/transifex/issues/206#issuecomment-15243207
personally, i'd rather not work on that any more. dont know how other searx translators feel about that (?) 
would suggest weblate, but dont know any public instances other than https://hosted.weblate.org/

**Comment by Cqoicebordel** [comment]
I personnally don't care.

I'm commited to open source software, but when it comes to handling data that are not sensitive at all, I rather want to use the right tool than limiting myself to OSS.

**Comment by ghost** [comment]
I agree that hosting the translations on hosted.weblate.org would be better than on Transifex. However, even if this isn't changed, you can easily use free software like poEdit to translate locally, not needing any web services, free or proprietary, at all.

**Comment by dimqua** [comment]
What about [Zanata](https://translate.zanata.org/)? And, btw, GitHub is also a proprietary service.

**Comment by xinomilo** [comment]
well in any case i'll close this issue, since it doesn't seem people mind using transifex (or/and github). personally, i already quit transifex, so no more translations there for me. probably github in near future, as soon as there is a tested nice free alternative (and also not sexist one)

**Comment by GreenLunar** [comment]
Ever since they became proprietary. I have seen this argument rising up in several projects already.

CopyQ, Exaile, Money Manager EX and even Gammu are currently being translated at https://hosted.weblate.org/ using [Weblate](http://weblate.org/) which provides integration with Git.

Please DO move away from the translation platform in question.

**Comment by GreenLunar** [comment]
BUMP!

**Comment by Cqoicebordel** [comment]
Changing platform will take time for the devs away of developping searx, when changing platform add zero advantage.
And beyond that, the teams of translators are already registered at transifex. So It would be a loss to move away from them.
I said I didn't care, but now, I think it's a bad idea to move away from transifex.

And beyond that, you can use a fully open source stack to contribute to the translations.

**Comment by andras-tim** [comment]
**For note:**
I'm find another web based translator tool, the [poeditor.com](http://poeditor.com).
This is free for open source projects (https://poeditor.com/help/faq#What-are-Open-Source-projects)

In other hand, I'm full agree with @Cqoicebordel

**Comment by ghost** [comment]
That's just another proprietary web 'service' so it doesn't change the situation. Unless they've hidden their licensing and code somewhere, but projects that do that are not worth looking at anyway because they have no interest in freedom.

**Comment by GreenLunar** [comment]
I refuse to keep the translation platform in question.

When more and more projects would show contempt for Proprietary Services that used to be also available as Free Software, they might reverse back.  GNU MediaGoblin has moved away from the translation platform in question to Pootle.  Also, we can gradually migrate translators and translators can even login to Weblate with GitHub and other social network accounts.

P.S. I have agreed to register to the translation platform in question because it WAS available as Free Software.

VOTE WITH YOUR WALLETS! VOTE FOR FREEDOM!

**Comment by Cqoicebordel** [comment]
There is no ads, and nobody here is donating money to Transifex.
When and if a paid platform will be considered, of course an open source one will be used.

Oh, and Transifex isn't a bad word, you can use it.

For migrating translators, they choose what they do. And some of them may not be on github, and some of them are not devs. And so, some of them will be lost when changing platform.

Searx's code and translations are still open source, no matter what. Even if transifex is closed source, and even if GitHub is closed source, and even if the routers at your FAI use closed source firmware.

But nobody forces you to use, or to translate, or to contribute. You are welcome to do it, but nobody forces you.

**Comment by GreenLunar** [comment]
> Oh, and "the translation platform in question" isn't a bad word, you can use it.

Only if they pay me, every time I do ;-)

> For migrating translators, they choose what they do. And some of them may not be on github, and some of them are not devs. And so, some of them will be lost when changing platform.

Translators can even login to Weblate with GitHub and other social network accounts, such as F and G.

> Searx's code and translations are still open source, no matter what. Even if transifex is closed source, and even if GitHub is closed source, and even if the routers at your FAI use closed source firmware.

I use DD-WRT.  The translation platform in question was available as Free Software.

**Comment by Cqoicebordel** [comment]
> Translators can even login to Weblate with GitHub and other social network accounts, such as F and G.

My point was that a lot a them won't even know that we switched platform.
Oh, and BTW, you prefer using an open source platform but recommand using closed source credentials ? That's weird ;)

> I use DD-WRT. The translation platform in question was available as Free Software.

We are moving away from the subject, but I was talking about your ISP, not you. I'm sorry, FAI is a french acronym. And I'm sure your ISP use closed source Cisco firmwares ;)

**Comment by GreenLunar** [comment]
> Oh, and BTW, you prefer using an open source platform but recommand using closed source credentials ? That's weird ;)

Did I recommend?

I am not willing to  continue this thread with you.

I think that migrating to Pootle or Weblate (even better) would be good.

**Comment by GreenLunar** [comment]
Comment by nijel

> Currently this feature is available only for commercial (non public) translations. This might change once nijel/weblate/issues/516 is implemented.

Do not use Weblate, yet.

When restricting access would be possible, I will ask, again, to migrate to Weblate.

**Comment by comradekingu** [comment]
@GreenLunar The issue is closed https://github.com/WeblateOrg/weblate/issues/516
I think this discussion fell short of addressing why the translation platform doesn't live up to what the product sells itself on. Moreover the 2021 situation is Transifex hasn't improved, whereas Weblate surpassed it. Was hoping to work on this, and was quite surprised to find searx uses Transifex. It spies on users left and right, and while it is true a lot of effort could be put in mitigation, that doesn't scale, and it isn't even a good tool.

**Comment by return42** [comment]
@unixfox do you like to open and move this issue to discussions .. I think it is worth to discuss what @comradekingu  [said](https://github.com/searx/searx/issues/268#issuecomment-769630687).  FWIW to mentioning that I will never use Transiflex  ..
