### ISSUE TITLE
protection again enhanced cross site scripting attacks

### ISSUE THREAD

**Issue by pointhi** [searx/searx#269]
I think It's an vulnerability which isn't very problematic, but it is better we are safe again it. It is js-code which is embedded inside graphics (.gif,...).

I found out about that vulnerabilitiy using a german tech-blog: [Javascript-Code in Bilder einbetten](http://www.golem.de/news/cross-site-scripting-javascript-code-in-bilder-einbetten-1411-110264.html), but there is also the english reference how that hack is working: [when-gifs-serve-javascript](http://iamajin.blogspot.in/2014/11/when-gifs-serve-javascript.html).

To fix that issue, we have to harden searx against wrong MIME types using the header: `X-Content-Type-Options: nosniff`, but I think It could breake image-results. Also we have to add [Content_Security_Policy](https://en.wikipedia.org/wiki/Content_Security_Policy) to be safe again other XSS-Vulnerabilites.

**Comment by asciimoo** [comment]
As i understand, the bug is exploitable only if a manually crafted image is referenced in a `<script>` tag. How could this provide surface to a successful attack through searx?

**Comment by Cqoicebordel** [comment]
I'm not familiar with the vulnerability, but maybe in the img tag, the image can close this tag and open a new script tag with malicious code inside ?

But if it's not the case (and I think it's not), preventing against this vulnerability will break a lots of images results.

Also, if it's only in script tags, we are not vulnerable at all, as searx doesn't allow to enter html code.

**Comment by dalf** [comment]
If I understand correctly, the idea is the create a real gif (but empty) and add javascript content after.
-  `<img src="img.gif">` display an empty image.
- `<script src="img.gif"></script>` load the script ( the javascript engine skip the garbage at the begining, the garbage is the gif).

If I still understand correctly, `<img src="img.gif">` won't harm since this is a valid gif : the browser will sniff a real gif (at least as describe in the blog entry).

The real issue in my opinion is a png that is a html document : 

> The worst instance related to mime sniffing is an old IE bug. As I understand it their sniffer tried some image formats and then HTML; then when they added PNG sniffing it was added to the sniff list after HTML, either by mistake or to maintain compatibility with pages that were currently being sniffed as HTML. The result of this is that even valid PNG images can be sniffed as HTML, converting a user-uploadable image into a Javascript (XSS) vector. 

from https://htaccess.wordpress.com/2009/09/22/x-content-type-options-nosniff-header/

The searx image proxy could do quick check with magics numbers : the would avoid wrong MIME type.

nosniff test (doesn't include the script as the png / gif test) : 
https://philip.html5.org/tests/ie8/cases/content-type-nosniff.html

firefox doesn't support the nosniff header : 
https://bugzilla.mozilla.org/show_bug.cgi?id=471020

chrom\* implementation with comments about FF / Opera / IE implementations : 
http://src.chromium.org/viewvc/chrome/trunk/src/net/base/mime_sniffer.cc?revision=HEAD&view=markup

Other issues : https://msdn.microsoft.com/en-us/library/dd565635%28v=vs.85%29.aspx (link from the htaccess blog). Could be a problem since searx includes content from other website.

Side note (not really related to this issue) : 
https://media.ccc.de/browse/congress/2014/31c3_-_5930_-_en_-_saal_6_-_201412291400_-_funky_file_formats_-_ange_albertini.html#video

Edit : another link about png interpreted as html : http://landofthefreeish.com/security/mime-sniffing-in-internet-explorer-enables-cross-site-scripting-attacks/

**Comment by asciimoo** [comment]
Jinja has an [autoescape]( https://jinja.palletsprojects.com/en/2.11.x/api/#autoescaping) feature which is turned on in searx and if I understand correctly it provides protection against these kind of attacks. A security test performed by [ROS](https://www.radicallyopensecurity.com/) also confirmed the previous statement.
