### ISSUE TITLE
Search only a specific site

### ISSUE THREAD

**Issue by throwaway1037** [searx/searx#2708]
Is it possible to search only a specific site, eg. by typing into the search bar "site:example.com search-term search-term2 ..."?

Is there documentation for variables like "site" you can type into the search bar, if they exist?

**Comment by unixfox** [comment]
Searx is a metasearch engine, filters are passed through to the origin search engines like goolge and others.

So if the filter `site:` exist for the engine like Google then it should work.

I'm closing this because Searx can't implement this filter due to the fact that it's not a search engine like Google or Duckduckgo.
