### ISSUE TITLE
Searx instance list need to be revised

### ISSUE THREAD

**Issue by davidhedlund** [searx/searx#273]
Most instances in https://github.com/asciimoo/searx/wiki/Searx-instances have untrusted SSL. Please update the list.

**Comment by Cqoicebordel** [comment]
The issue is, to have a valid certificate you have to pay big money to trusted companies.

Of course, nobody in the searx list would pay.

So they have created certificates for their servers, that allow the most privacy possible. You just have to trust them, as you trust the companies that take big money when you buy on amazon.

**Comment by davidhedlund** [comment]
Thank you.

This problem do not arise with Searx instances that are hosted as Tor Hidden Services.

**Comment by xinomilo** [comment]
there are free certs, from startssl that work in 99% of browsers. no money asked there.
to open cacert ssl sites, you need to download+import their root cert first, since its not in the browsers.
comodo offers some very cheap positive ssl certs, anyone can use. 
a few are self signed from what i see, which in theory are better than the commercial certs (nsa associates...). 
project "lets encypt" will make it much easier (and free), for everyone to encrypt their site traffic.
tor HS instances are not https. tor is encrypted network, doesnt need https.
although some companies start to sell .onion certs as well.

**Comment by Cqoicebordel** [comment]
Yes, so to resume, some instances appear untrusted because you don't trust their root cert.

There is nothing to do here.

And there is no cert in TOR.

(So, you can close this issue if you feel your questions have been answered, if not, don't hesitate to ask specific questions :) )

**Comment by davidhedlund** [comment]
I'm glad you guys took your time to explain this briefly.
