### ISSUE TITLE
Search API parameters does not work properly.

### ISSUE THREAD

**Issue by smiralexan** [searx/searx#2771]
**How did you install Searx?**
searx-docker or using public instance

**What happened?**
If you specify both 'engines' and 'categories' parameters in Search API, 'engines' parameter does not work.

**How To Reproduce**
Specify both 'engines' and 'categories' parameters while using Search API. 

**Expected behavior**
Results consists only with specified engines responses with specified categories.

**Screenshots & Logs**
Only 'engines' - works.
![image](https://user-images.githubusercontent.com/52520363/115134684-7a950300-a03c-11eb-8c5a-fc88afd93777.png)

With 'categories' - does not work.
![image](https://user-images.githubusercontent.com/52520363/115134692-98626800-a03c-11eb-9dc7-9b47251412e4.png)

**Additional context**
Discussion: https://github.com/searx/searx/discussions/2770

**Comment by virtadpt** [comment]
Not "google", use the shortcode ("go").

**Comment by smiralexan** [comment]
Sorry for late response. But i must say that on my instance and on several public instances that I checked shortcodes doesn't work at all. But even if it would work, why it doesn't mention in documentation?

Works (screenshot from public instance, but on my instance all the same):
![image](https://user-images.githubusercontent.com/52520363/116805768-d12d3180-ab52-11eb-9f81-477337a3c757.png)

Doesn't work:
![image](https://user-images.githubusercontent.com/52520363/116805789-f0c45a00-ab52-11eb-8e02-52309fc8c177.png)

**Comment by kvch** [comment]
I think shortcuts are not supposed to work.

But what is exactly the problem? According to your report, the API works because Google results are shows as well as Wikidata ones. Wikidata is also part of the general category. Thus, there is no problem in searx. I have also tested locally with the query http://localhost:8888/search?q=hello&engines=google&categories=files to check your statement. However, the result list contained results from Google and engines from files category. 

Could you please provide more details? So far it does not seem to me like a valid bug.

**Comment by smiralexan** [comment]
Oh, maybe I misunderstood the logic of using 'engines' parameters. I used to think that for request with engine 'google' there might be results of several categories in the response. But 'google' engine does not include 'google news', for example. Sorry for bothering, closing the issue :)
