### ISSUE TITLE
Not anonymous?

### ISSUE THREAD

**Issue by ghost** [searx/searx#279]
Is searx just a client? No P2P connection/sharing like Yacy?
https://github.com/asciimoo/searx/wiki/possible-search-engines

User--->searx--->SearchEngineCompanyServer

I can see searx provide better results than yacy, but I won't use it because it didn't
mix search query with other people. (Yacy has a better anonymity on this problem)

**Comment by ghost** [comment]
If searx is not P2P, please add SOCKS proxy support.
SOCKS proxy like Tor and I2P will hide original IP address.

**Comment by pointhi** [comment]
There are some searx-instances which are also available as hidden service.

Beside of that, because searx is between the client and the different search-site-provider, and most searx-instance should have multible users, there is a mixing with the search-queries of other people. I think searx has much more privacy as Yacy, because it is not possible to insert a P2P Node and then getting search-request of other servers.

https://en.wikipedia.org/wiki/Metasearch_engine

**Comment by ghost** [comment]
> I think searx has much more privacy as Yacy

I don't think so.
1. Searx server owner can log user's IP address and search query.
   searx.me can log user's IP address -> webserver's log
   hack a code to log user's search query -> and nobody knows it
   
   > Yacy doesn't log search query. Results are shared by P2P protocol.
2. "and most searx-instance should have multible users, there is a mixing..."
   What if I run private searx website and use it? No anonymity right?
   
   > Yacy covers it. When you search, yacy mix a query into P2P.

**Comment by Cqoicebordel** [comment]
1/ The point of having searx is that anyone can install an instance instead of using an existing one. It allow full trust this way.

2/ Sure, there is less anonymity if you are the only user of an instance. But it's more than using the search engines directly : they don't know if you are alone or not, and there is no cookies from them. You could have build an instance for a university, and they can't say.

By the way, true anonymity can't really exist on Internet. Even using a VPN+TOR+... there are always ways of determining who you are. If you don't believe me, look at that : https://panopticlick.eff.org/

**Comment by dalf** [comment]
> If searx is not P2P, please add SOCKS proxy support.

Look at #236 : searx doesn't support directly an outgoing proxy right now, but you can use tsocks.

**Comment by asciimoo** [comment]
duplication of #236
