### ISSUE TITLE
!d and !q searches to redirect to ddg and qwant

### ISSUE THREAD

**Issue by mizzunet** [searx/searx#2889]
**Is your feature request related to a problem? Please describe.**

Kinda, I use public instances, I have tried some, they work fine at most times. But sometimes google results are missing, that's fine as other engines like ddg, start page do work. But the worst is that, sometimes none would show, it just show " Sorry! we didn't find any results. Please use another query or search in more categories.". Then it fixes itself after a long time
This happened me at searx.bar, anon.sx, start.paulgo.io instances
**Describe the solution you'd like**

In DDG and Qwant, it redirect search to Google if "!g" typed at first, like "!g test"
I'd like to see !d and !q for redirecting to DDG and Qwant respectively in searx. 
I don't wish to use google anyway

**Describe alternatives you've considered**

I manually get to Qwant and search from there
**Additional context**

**Comment by unixfox** [comment]
That's not possible bangs are for forcing a specific search engine because Searx is a metasearch engine and not a real search engine. So the point of bangs is to use another search engine inside Searx.
If you want to get a really good experience with Searx you should host it yourself. We have a guide there: https://searx.github.io/searx/admin/installation.html

**Comment by 0xhtml** [comment]
Isn't redirecting to Google or DuckDuckGo possible by using `!!ddg` or `!!g`? Like `!!g test`
