### ISSUE TITLE
Search from Lynx Yields "Rate Limit Exceeded"

### ISSUE THREAD

**Issue by tkiral** [searx/searx#2894]
When attempting to search from the Lynx browser, I get error 429-"Too many requests" then "rate limit exceeded. I have no issues searching from firefox on the same computer.

**Comment by unixfox** [comment]
Public instances are protected using [filtron](https://github.com/asciimoo/filtron/), a program that blocks bots and Lynx is recognized as a bot because it's not a normal web browser. You have multiple options in order to solve this issue:
- Run Searx locally, we have a documentation about that here: https://searx.github.io/searx/admin/installation.html
- Find a public instance that doesn't use filtron, there are some instances on https://searx.space

I'm closing this issue because the Searx team have no control over the public instances.
