### ISSUE TITLE
gimmeasearx and its need to send bot requests

### ISSUE THREAD

**Issue by demostanis** [searx/searx#3259]
Hello,
I've created [gimmeasearx](https://github.com/demostanis/gimmeasearx), a website to get a random SearX{,ng} instance everytime users loads the page, fetching instances from [searx.space](https://searx.space), verifying them and allowing users to specify criteria to only use the ones they want.
The verification step makes a request to `/search?q=` plus a pre-defined query to each instance, such as "gimmeasearx", and making sure the response includes "Find a random searx instance" (the description of the GitHub repo). This ensures the instance is not rate-limited from major search engines, and that it's actually usable.
However, for the above to function, gimmeasearx needs to send bot requests. As most instances use filtron, they get denied ("rate limited" according to the responses). I had to set a few headers to act like a browser: https://github.com/demostanis/gimmeasearx/blob/c4dc22d5c06dd40e621fe997b76bd02b565768ea/internal/instances/instances.go#L101
I was wondering if a friendlier solution could be put in place, such as making default filtron rules allow `gimmeasearx` user agents. Or is my current workaround OK?

**Comment by unixfox** [comment]
Unfortunately it's not feasible to modify the configuration of all the SearX instances because we don't control them. And we have no plans to allow a specific user agent because that you introduce some abuse.

Do note that not all the instances are using filtron, some have aggressive rules that detect better the bots than filtron.

Your solution/workaround is ok, filtron is installed only to reduce the amount of bots. Not to completely remove them.
