### ISSUE TITLE
new release and future of searx

### ISSUE THREAD

**Issue by josch** [searx/searx#3269]
Hi,

I'm maintaining searx in Debian and was wondering whether you are planning a new release any time soon? The last release 1.0.0 from march 2021 is quite old and engines like google are currently broken with that version. I've also seen that there have not been many commits to searx this year. And I also just now discovered searxng but wasn't able to find any context of this fork. Is this a friendly fork? Are people supposed to move from searx to searxng? The searxng fork also hasn't made any release yet. Is there a migration guide anywhere? Will searx still be developed?

Thanks!

cheers, josch

**Comment by unixfox** [comment]
Hello josch, I'm speaking as a maintainer of both searx and searxng.

The SearX project is in maintenance mode, only fixes are mostly pushed from time to time. There is hardly any new feature being added into the code. You can see it for yourself in the commits history: https://github.com/searx/searx/commits/master

A new fork of SearX called SearXNG, emerged one year ago, it was founded by the previously active developer dalf. You can read more about it here: https://github.com/searxng/searxng/discussions/972

SearXNG will never have a monthly or weekly release because it is in rolling release as everyday engines break, new fixes are pushed, and new features are being added. While this sounds scary for stability, the developers take extra care not to break anything, and it has been pretty stable since the fork started.

If you want to package SearXNG into Debian we recommend building searxng using the latest commit and using a version number like this: `2022.06.27-249df41a`, the date then the last commit ID.

Feel free to contact the SearXNG team if you have any question: https://github.com/searxng/searxng#contact or open a discussion: https://github.com/searxng/searxng/discussions

**Comment by josch** [comment]
Thank you @unixfox for your reply. Only one of my questions is left unanswered: what is the migration path from searx to searxng?

And if searx is in maintenance mode, then I guess this means that you suggest that all searx installations be replaced by searxng installations? I'm asking because this is a question of whether we should have both searx and searxng in Debian or only searxng and if searxng should replace searx or be an alternative to it.

Thanks!

**Comment by unixfox** [comment]
There is a documentation about migrating from searx to searxng: https://docs.searxng.org/admin/installation-switch2ng.html

But in my opinion, it's usually way easier to start over and do a fresh installation.

Both SearX and SearXNG can coexist, SearX may have some broken engines, but it still works fine.

About replacing searx by searxng in Debian, it's a though question. SearXNG diverged quite far from the code base of SearX, I think it's wise to have two Debian packages so that anyone can feel free to use whatever they prefer.

Pinging the SearXNG team @dalf @return42 @mrpaulblack @tiekoetter

**Comment by mrpaulblack** [comment]
I actually dont think SearXNG should replace searx. SearXNG has some improvements over searx and is more active developed, but for example SearXNG does not have the oscar theme anymore as an example. Forcing SearXNG as a replacement would mean that they loose this functionality.

So TL;DR I agree with @unixfox : Both projects can coexist as 2 independent packages :+1:

**Comment by kvch** [comment]
> And if searx is in maintenance mode, then I guess this means that you suggest that all searx installations be replaced by searxng installations?

@josch Maintenance mode does not mean that the installations should be replaced. It means that we are not adding engine metrics, or shiny JS-heavy UI, like SearxNG does. The fork happened because we could not agree about those features. @asciimoo and me believed that those features are not privacy respecting enough for searx. 

> I think it's wise to have two Debian packages so that anyone can feel free to use whatever they prefer.

I also agree with @unixfox. Searx is a complete piece of software, we do not plan to add new features, especially not ones that are risk the privacy of users, like SearxNG does. Searx is more conservative when it comes to privacy, here the bar is much higher, than in SearxNG. Forcing users to move to SearxNG to me is sneaky, I would not force privacy conscious users to an inferior service (from privacy perpective). Obviously, SearxNG is shiny and new, it will attract more people, than good old searx.

Also, I am working on a new release, I am reverting the httpx changes introduced in SearxNG because it does not provide any significant improvement in search time.

**Comment by josch** [comment]
> The fork happened because we could not agree about those features. @asciimoo and me believed that those features are not privacy respecting enough for searx.
> Searx is a complete piece of software, we do not plan to add new features, especially not ones that are risk the privacy of users, like SearxNG does. Searx is more conservative when it comes to privacy, here the bar is much higher, than in SearxNG. Forcing users to move to SearxNG to me is sneaky, I would not force privacy conscious users to an inferior service (from privacy perpective).

Could those bits of information be added to the ***Differences to searx*** section in the searxng `Readme.rst`? From how that section is currently worded it sounds like there is no reason to stick with searx. But what you wrote indicates that there are indeed reasons to stick with searx. Please add those. Thank you!

Thank you for all your replies! I think I understand the situation now. Feel free to close this issue once the next searx release happens.

**Comment by cyclaero** [comment]
> Also, I am working on a new release, I am reverting the httpx changes introduced in SearxNG because it does not provide any significant improvement in search time.

This move is highly welcome here, since the introduction of httpx broke the installation on Windows. The asynchronous module which httpx depends on is by design incompatible with Windows.

Ah, and removing httpx would most probably also resolve issue #3110.

**Comment by return42** [comment]
>  Searx is more conservative when it comes to privacy, here the bar is much higher, than in SearxNG. 

This claim is nonsense, based on assumptions that are difficult to understand.  In practice, poorly maintained software is often a real problem.  I personally went to SearXNG because I saw no progress with searx and felt that the project was not adequately maintained .. but this is my very personal opinion .. other might think different.

**Comment by ghost** [comment]
Hello everyone!

I would like to contribute to this project. *What can I do to help here: searx?*
