### ISSUE TITLE
Error 500 when converting currencies with non US-ASCII symbols

### ISSUE THREAD

**Issue by David-5-1** [searx/searx#355]
Trying to convert currencies using non US-ASCII symbols (with € and £ or seemingly any character : ø, à, …) results in Internal Server Errors.

```
curl 'https://searx.me/?q=10 $ in €'      -> Error (500)
curl 'https://searx.me/?q=10 $ in EUR'    -> OK (200)
curl 'https://searx.me/?q=€ø…'            -> OK (200)
```

**Comment by Cqoicebordel** [comment]
Confirmed
I'll look into it tomorrow.

**Comment by Cqoicebordel** [comment]
Ok, I give up.
It's clearly an unicode issue. But python 2.7 is a real pain to handle this.
And so I've tested lots of solutions, but found nothing usable.

If anybody know how to have a string with non-ascii chars encoded as \uXXXX, that could be a good approach to a solution.

**Comment by asciimoo** [comment]
i'll take a look on it

**Comment by pointhi** [comment]
probaly using encode like inside the image_proxy? (https://github.com/asciimoo/searx/blob/master/searx/webapp.py#L260)

**Comment by Cqoicebordel** [comment]
Hmmm, didn't try that, but could help a lot.
But there would still be an issue, because not all money chars are defined by their htmlentities. I mean, it would take a bit of work to check every data in currencies.json, and add the correctly encoded money symbols.
Or it could be easy, by replacing every \u by something like #xx;

Anyway, I can't work on it this we, and my brain is fucked up by all this encode/decode/unicode/unidecode/str stuff to do it properly, so I passed the torch on this one ;)

**Comment by Cqoicebordel** [comment]
Finally found it, but lost a bit of hair in the process.

**Comment by asciimoo** [comment]
=))
Thanks again!
