### ISSUE TITLE
Parse !engine or :language anywhere in the search query

### ISSUE THREAD

**Issue by haasn** [searx/searx#363]
I often type my search term first and then decide which engine to use, which results in something like “foo bar !wp”.

DDG would parse this identically to “!wp foo bar”, but searx does not and I find it somewhat annoying. It would be cool if you could add an option to allow parsing for engine syntax anywhere in the search term.

**Comment by vindarel** [comment]
Hi devs,
I tried a bit here: https://github.com/vindarel/searx/commit/0bcecd72a6181d72e1afd2c4cb87ea6e96945f91
However it's not working yet and you may help me with a quick review ! (you can try [on my server](http://5.196.70.6:8888/)).

The thing is, I don't quite understand the type and use of `self.query_parts` (looks like we don't put all keywords in it, in the following class methods, why is it always accessed with `self.query_parts[-1]`, why the `-1` ?), and maybe I broke `self.engines` ? Since I don't see much docstring or unit test on `parse_query`, I thought I'd rather ask for a quick review.

Any thoughts then ? Thanks !

**Comment by qazip** [comment]
Is there any news regarding this? I also agree with the OP that one should be able to use "!engine" anywhere in search string..

**Comment by asciimoo** [comment]
added in aa3c18dda9329fff875328f6ba97483c417b149a
