### ISSUE TITLE
All search engines blocked us except Wikipedia

### ISSUE THREAD

**Issue by privacytoolsIO** [searx/searx#364]
Example search: https://www.privatesearch.io/?q=edward%20snowden

Wikipedia is the only result. All other search engines blocked us probably. That's the only explanation I can come up with. I'm sure we generated too many requests and reached limits. Do you know how to fix this? Thanks for your help, guys.

**Comment by Cqoicebordel** [comment]
That's weird. Have you _a lot_ of traffic on you site ?
Anyway, first, check the logs. Maybe it's something silly.
Secondly, try to perform a search on Google for ex. from the IP used by the server.
Third, try to change the user agent in settings.yml.
If nothing of those works/helps, maybe your hosting company propose a dynamic IP, that can change regularly, and thus bypassing the block.

Anyway, I think that's really weird. I can imagine one or two engines blocking you, but all of them ?! That's really really weird.

EDIT : Oh... Maybe it's your host that blocked your requests, because it thought that you were sending spams/DoS...

**Comment by dalf** [comment]
Try to start searx with `debug: True` in settings.yml and see the logs.
Without error logs it is difficult to understand what is happening.

(duckduckgo definition doesn't seem to be block)

**Comment by dalf** [comment]
privatesearch.io seems to work again, can the issue be closed ?

**Comment by privacytoolsIO** [comment]
Hi guys, sorry for the late reply. I'm no server admin, I can't do all the things you recommended.

About the traffic: around 1,500 unique users daily. some blocks are still enabled, for example youtube:

https://www.privatesearch.io/?q=youtube&pageno=1&category_videos
It's just showing dailymotion results. Also DuckDuckGo results disappeared again.

"EDIT : Oh... Maybe it's your host that blocked your requests, because it thought that you were sending spams/DoS..."

That was a good theory, but since some search engines are working again it's not valid anymore.

"Try to start searx with debug: True in settings.yml and see the logs."

I managed to enable it, but I didn't find the log file. Can you tell me where it is? Thanks.

How are searches performed in general for Google for example? Are we all using an API, or are limited in any way by the amount of searches?

Thank you all for your help.

**Comment by Cqoicebordel** [comment]
For the log file, it depends on the way you installed it. If you use apache, it may be in the logs of apache, or nginx if you use nginx. Maybe try to start manually a different instance to test it, with the command `python searx/webapp.py`

Also, to test if you are blocked, you can try launching a browser from the server and doing manually a search on the problematic search engines. Even a text browser would work.
I already had a captcha on the search page of google, because I worked in an entreprise that had only a few external IPs, so google saw us as spam/DoS.

The search are performed differently depending on the engines. For some, it's scraping the webpage, for others, using public api, and some others, private apis that needs api keys.
It's hard to give you a list, as it depends also on your configuration, but you can check in the source code, in the "engine" folder each engine, they all have a header describing how they collect their data.
Only engines using APIs could be considered as stable, and even then, a ratio could be applied when they want...
Also, they could block you for a day or two, and then unblock you.
