### ISSUE TITLE
dns rotation for all searx sites?

### ISSUE THREAD

**Issue by ThomasWaldmann** [searx/searx#39]
instead of a wiki page, maybe have some specific dns name (see pool.ntp.org for an example from the ntp domain) with all the currently-working searx sites?

plus maybe some monitor that kicks out sites that are offline?

**Comment by stef** [comment]
the biggest problem with this is, the very different settings of the various engines, imagine landing on a french searx instance that only does french searches. or consider the different patchlevels between installs.

**Comment by Cqoicebordel** [comment]
Why would a french searx instance only provide french results, or do french searches ?

The version could be a problem (I doubt it), but this kind of portal could limit itself to the last version or n && n-1 as detected by http://stats.searx.oe5tpo.com/

**Comment by stef** [comment]
because there was this example in the issues here, where a french instance operator was complaining that the results are english, and the recommendation was, to only allow engines that do localized results. so i guess, such a setting exists in the world somewhere, and i'd be dumbfounded if i'd get results from such a searx instance if it would be included in the round-robbin. also consider my searx instance, i know a lot of people who hate my inclusion of uncyclopedia among the default search engines. so i opt out also of this round-robin?

**Comment by Cqoicebordel** [comment]
You do what you want.

And remember that the language of the results can be choosen in the prefs, even if the default is french, and that this preference will work across all nodes.

**Comment by stef** [comment]
i think you misunderstand, this is about server settings. not client settings.

**Comment by Cqoicebordel** [comment]
No I understood correctly : the server cannot serve _only_ french results. It can only default to french results.

So, it's in the client side to pick a prefered language, and bypass the default.

**Comment by stef** [comment]
well, i expressed myself wrongly then. the problem is that the french engine only serves other engines that support french results. so the set of queried search-engines is lower, due to the french preference of the server.

**Comment by Zeriuno** [comment]
Actually, I don't think that's how it works at the moment. Right now users are **complaining** that it doesn't work that way.
Anyway preferences are set in the client, not in the server.

**Comment by ghost** [comment]
I don't think that a centralized DNS solution is a good idea unless it involved icann AND opennic and leaves the option open for people serving only from hidden-service or plain IPs or anything which is yet to come.
In terms of privacy/protection, opennic is the better solution if something like this should ever be considered by someone.

**Comment by gitbugged** [comment]
Was about to open a duplicate when I found this ticket. Searx is very centralized around Searx.me, and it's overloading the server. I see two potential options.

1) A round robin DNS that lands on a random, verified working, searx node.
2) Implement some form of simple federation. e.g. If a search times out, ask the user to retry the search on another randomly chosen searx node. We already have a list to pull from.

**Comment by stef** [comment]
centralization around searx.me is a decision by the people to use searx.me instead of running their own or using one of the many other servers: http://stats.searx.oe5tpo.com/

since searx nodes are run by many other operators the user cannot know which one is modified in what way or in which country it exist or many other factors and if that is acceptable.

noone however forbids anyone to create a round robin dns for many searx servers and operate this on their own and have other people use it and become more popular than searx.me. searx.me actually encourages this by having regular scheduled downtimes. but

**Comment by Zeriuno** [comment]
@gitbugged @stef I actually think this issue can now be closed, since Searxes exists: https://searxes.danwin1210.me/

> If you can't decide which searx instance to use, try "Searxes". This will use other Searx randomly.

https://github.com/asciimoo/searx/wiki/Searx-instances

**Comment by stef** [comment]
sounds great, looks nice, is this searx? never saw that theme. is the way you do this documented? are your sources somewhere available?

**Comment by Zeriuno** [comment]
It isn't mine, I just discovered a few weeks ago re reading the searx wiki!

**Comment by unixfox** [comment]
https://searx.space
