### ISSUE TITLE
"http redirect" magic

### ISSUE THREAD

**Issue by vn971** [searx/searx#441]
Searx currently has a magic case for a search query "http redirect".
It redirects to http://example.com

While this is kinda cool, it does not allow you to read about http redirections (like when I should use 302 or 303 or 307 status codes).

The question is: is this magic still considered good, or was it just fun to add but may as well be removed?
It does not really touch me personally.. But still, I had to use ddg for that query.

**Comment by pointhi** [comment]
I'm not able to reproduce it. Can you please give me some informations:
- what instance are you using?
- what theme are you using?
- what engines are you using?
- what language are you using?

It look like an XSS vulnerability (search-engine results are not filtered correctly)

**Comment by vn971** [comment]
@pointhi here is the link I used:
https://posativ.org/search/?q=http%20redirect&pageno=1&category_general
The behavior is the same in a clean firefox profile, so I guess the URL is enough. If there are any further questions, please write.

**Comment by Cqoicebordel** [comment]
Ok, I can reproduce in Fx, O12 and Chr.
There is an answer from Stackoverflow that contains the text `<meta http-equiv="refresh" content="0;url=http://example.com">`. It seems that we don't escape rightly the answer texts.

**Comment by vn971** [comment]
Glad that I accidentally found the bug!:)

**Comment by vn971** [comment]
Thanks!.

**Comment by pointhi** [comment]
I think we have to solve this types of bug when refactoring (#415).

Occasionally, we are finding [XSS vulnerabilities](https://en.wikipedia.org/wiki/Cross-site_scripting) which are  causing bugs in the web frontend (redirection, form fields in the results). We should fix that type of seccurity issue once and for all, by doing reasonable input checking which should also be documented in the wiki.

I would propose to return all results from the engine unescaped (because every new engine could forgott escaping), and doing escaping after removing duplicates. The same with datatypes (converting all results into defined data types like int, float and utf8).

**Comment by Cqoicebordel** [comment]
Agreed
