### ISSUE TITLE
number of search results

### ISSUE THREAD

**Issue by EpisteX** [searx/searx#443]
Hello,
I would like to know Searx can give the number of search results like google.

It is possible ?

Thank you

**Comment by Cqoicebordel** [comment]
The fact it's a meta search engine means that it's a difficult task : we have lots of results from lots of search engine. Even if we could get each number of results from each engine, adding them won't work, because of course, there are duplicates between them (duplicates that we filter before showing the results).

But _maybe_ we could list the number of results for each engine used.
But that's a big "maybe", because it depends of lots of factors (does the engine provide such number, is it available through the api we use, how to display it...)

**Comment by EpisteX** [comment]
Thank you for your answer !
Best regards.

**Comment by kvch** [comment]
Closing, see 2f7752b
