### ISSUE TITLE
Allow All / Block All button

### ISSUE THREAD

**Issue by Zeriuno** [searx/searx#45]
It could be useful to allow a single click toggle of all the engines in the preferences page.

**Comment by stef** [comment]
unless this is possible without js, it would violate the basic searx premise of not requiring javascript and preserving privacy.

**Comment by Cqoicebordel** [comment]
The premise of searx never was to be without javascript. Some themes work without it, some are better with JS. It's an user choice.

And implementing it will in no way destroy your non-JS experience of searx.

**Comment by stef** [comment]
i think you might be mistaken with the premise of searx, it is a privacy respecting engine, if you disable the privacy respect, why not use any of the other kraakens instead? why all this work in the first place? so the default with searx is no js, because that is the privacy respecting way of doing things. maybe it's not explicit, but then it should be documented and made explicit.

**Comment by Cqoicebordel** [comment]
Deactivate JS, and searx will work flawlessly. It doesn't hurt you if a JS function is implemented, it doesn't hurt your privacy. And as the code is public, even with JS activated, I can prove that your privacy is respected.

So no, the project wasn't around JS-less, but around privacy protecting.

**Comment by stef** [comment]
javascript is one of the tools that enable a lot of privacy violations that are not possible without javascript. so not providing js is a conscious choice to protect the users. i'm hesitating to open an issue recommending, that 1/ searx includes a warning.js, that shows a warning to the user, that enabling js removes some of the privacy promises of searx, and recommending to use it without js instead and curse the browser vendors for having to click 1 more than without js. I think a similar warning could also be emitted when the user uses a get request. i mean perhaps, the problem is that the privacy vs convenience dichotomy is not explained and sold well enough. such a solution would 1/ educate the users and 2/ provide an escape for the js-apologists to include js in searx.

**Comment by Cqoicebordel** [comment]
If they trust the searx instance, why not trust its JS ?

**Comment by stef** [comment]
js is a huge security liability, by not using it you are not exposing your users. that is a responsible thing to do. the awareness of this is limited, and i am sure this also greatly affects what you call "trust the searx instance", of which statement i can only question the consciousness of this trust.

**Comment by Zeriuno** [comment]
@stef it looks like you don't really know searx. The main instance uses javascript: https://searx.me/

Anyway, if you can think you can eliminate trust from the equation of using a computer tool (software or hardware), you are mistaken.

**Comment by ibrokemypie** [comment]
many of the themes use jscript, any work on this?
