### ISSUE TITLE
AttributeError: 'module' object has no attribute 'old_where'

### ISSUE THREAD

**Issue by pointhi** [searx/searx#485]
I updated my searx instance today, and got the following error:

```
Traceback (most recent call last):
  File "/usr/local/searx/searx/__init__.py", line 55, in <module>
    environ['REQUESTS_CA_BUNDLE'] = certifi.old_where()
AttributeError: 'module' object has no attribute 'old_where'
```

I updated the dependencies with `pip install --upgrade -r requirements.txt` before running searx.

**Comment by misnyo** [comment]
Hello,
can you give me the version of openssl and certifi you are using?

```
pip freeze|grep certifi
echo -e "import ssl\nprint ssl.OPENSSL_VERSION_INFO\n"|python
```

The temporary workaround should be to upgrade the certifi package, since the requirements.txt doesn't contain versions, and I guess you have an obsolete version of certifi, which is not upgraded for some reason(which it should).

**Comment by pointhi** [comment]
output:

```
certifi==2015.11.20.1
(1, 0, 1, 5, 15)
```
