### ISSUE TITLE
Auto-detect blocking engines?

### ISSUE THREAD

**Issue by ldidry** [searx/searx#520]
### First, the situation

Framasoft is hosting a searx instance at https://framabee.org. We have more than 2 000 users per day. We are sometimes blocked by Duckduckgo and Google.

For duckduckgo, the solution is simple: I block duckduckgo.com requests for a few days by putting `127.0.0.1 duckduckgo.com` in `/etc/hosts`.

For google, it's trickier: I used to use the server as a proxy for my browser (with `ssh -D 8080 my_server`) and make a google search. I got the captcha, solved it, and it was ok. Now, it doesn't work anymore: I don't have the captcha with my browser. I tried lauching Midori on the server, I got the captcha, solved it and it didn't change a thing for Searx. Same for Iceweasel on the server : I don't even have the captcha.
### The solution I think about

If an engine is detected as blocking searx, it would be stored somewhere, with the timestamp of when it has been detected blocking, and it would be disabled for a period of time (what about a day per default?).

For Google, I was thinking about a plugin, disabled by default, that would present the captcha image to the user for him to solve it. Then the result would be sent to google to unblock searx.
### Questions

Do you think it could possible to detect blocking engines and auto-disable these engines?

Do you think I'm going in the good direction?

Before you ask: yes, i can try to code that, I'm mostly asking to be sure that it would not be a waste of time, trying to achieve the impossible.

**Comment by dalf** [comment]
I agree with this idea.

It doesn't solve everything but it's a start, when there is an exception with the HTTP request (time out for example), the engine is suspended for a time : 
https://github.com/asciimoo/searx/blob/master/searx/search.py#L48

I don't know how duckduckgo blocks the results ? is there a redirection to a specific page ? a time out ?

About google, an exception is triggered when google redirect to sorry.google.com : 
https://github.com/asciimoo/searx/blob/master/searx/engines/google.py#L194

The exception just crash the engine thread nothing more. Different way to extend : 
- throw a specific exception
- provide an API to the engine to suspend requests

Another solution : limit the number of requests per hour and per IPs to prevent blocking.

**Comment by asciimoo** [comment]
+1, @ldidry  i like it

It would be good to find method(s) to defend searx in these cases.

@dalf Limiting requests can solve the problem, but e.g. google doesn't have a hard limit. It means when the traffic isn't suspicious (random different searches/useragents) it serves way more responses without blocking than if you just iterate over pages of a single search term. It makes hard to specify good limits and can be totally remote service specific.

An other solution can be the improvement of the engine suspend mechanism. If an engine have the ability to request suspend for a specific time, it could help.
Different suspend time for different errors would be also useful.

We should also consider to mix these ideas: a loose request limit AND optional captcha solving capability AND dynamic suspension of engines

**Comment by ibrokemypie** [comment]
AS searx is acting as a proxy for the results, shouldn't the requests all have the same user agent? Making the requests seem as normal as possible could help reduce the issue, if as you are saying, normal searches have a higher limit, is true.

**Comment by ibrokemypie** [comment]
@dalf afaict, duckduckgo just times out any connections when it blocks you

**Comment by return42** [comment]
> We have more than 2 000 users per day. 
> We are sometimes blocked by Duckduckgo and Google.

Really users, or requests?  I can't speak for instances used by 2000 user, but my experience is ...

This is 99% due to the fact that bots overwhelm your instance with requests and these requests in form and frequency lead to your instance being blocked by Google.  If you place your instance public to the internet you should really consider to install a filtron reverse proxy and for privacy a result proxy is mandatory.

Please use our new installation instruction and install filtron and morty also.

Closed by PR #1803 / see docs at: https://asciimoo.github.io/searx/admin/installation.html

**Comment by dalf** [comment]
(from ldidry)
> If an engine is detected as blocking searx, it would be stored somewhere, with the timestamp of when it has been detected blocking, and it would be disabled for a period of time (what about a day per default?).

It was actually implemented (without shared state between the workers): 
https://github.com/asciimoo/searx/blob/bce3830b8dd9322e4e93d0003aa86e03c03e2dca/searx/search.py#L205-L214

But not this (from asciimoo)
> Different suspend time for different errors would be also useful.
> We should also consider to mix these ideas: a loose request limit AND optional captcha solving capability AND dynamic suspension of engines

(from return42)
> Really users, or requests? I can't speak for instances used by 2000 user, but my experience is ...

It was the public instance from [framasoft](https://framasoft.org/en/) ([wikipedia page](https://en.wikipedia.org/wiki/Framasoft)). The number doesn't surprise me. The instance was shutdown last year. BTW, the [first filtron commit](https://github.com/asciimoo/filtron/commit/15dca45706781c713ce106b47a1d2da49c843f99) was in May 2016: one month after this issue was created.
