### ISSUE TITLE
release v0.8.2/0.9.0 ?

### ISSUE THREAD

**Issue by asciimoo** [searx/searx#529]
There are plenty of changes since v0.8.1, lets release a new version in the near future.
Here's a checklist of tasks what have to be done before:
- [x] Finish the user settings refactor (#534)
- [x] Fix #527 
- [x] Merge #526 
- [ ] Merge #360
- [x] Fix #447
- [x] Fix #535
- [x] Merge #531

Any suggestions?

**Comment by pointhi** [comment]
if there are no outstanding issues or reserves left, I would suggest to merge #189.

**Comment by asciimoo** [comment]
@pointhi thanks, added to the list

**Comment by prolibre** [comment]
The Wikipedia tab (Infobox) in the language selected in the preferences ? :-)
sorry for the translation...

**Comment by asciimoo** [comment]
added

**Comment by kvch** [comment]
I am refactoring the user settings. I think it is going to be ready in a few days. :)

**Comment by asciimoo** [comment]
\o/ thanks

**Comment by GreenLunar** [comment]
Should issues #543 (anti abuse systems) and #537 (download video plugin) be taken into consideration, too?

**Comment by GreenLunar** [comment]
Do not forget to refresh and update translations.

**Comment by jibe-b** [comment]
Hi @asciimoo and all!

The next release could be released soon.
I would like to let you know that I will be happy when it's released in order to advertise Searx to Scientists in order to increase the adoption of Searx in this community.
The communication plan is under construction in [this pad](https://semestriel.framapad.org/p/searx-communication), feel free to have a look and eventualy to add yor thoughts!

Best regards,

**Comment by asciimoo** [comment]
@jibe-b great, thanks!

Lets Finish the remaining issues in the next release.
