### ISSUE TITLE
searx-instances mailing list (?)

### ISSUE THREAD

**Issue by xinomilo** [searx/searx#578]
i think it might be a good idea to have searx instances admins/users use a mailing list to exchange ideas/propose things+guides for instances, help each other work out things that shouldn't necessarily be on the issue tracker of searx. something like tor-relays@ mailing list.
i'd be happy to help out with finding a provider for a new list and/or administering the list, but maybe its better if "official" searx contributors, started it out and asked for volunteers/moderators afterwards.  
( if you agree to this idea of course :) )

**Comment by asciimoo** [comment]
@xinomilo good idea, maybe it is a better platform to discuss administration questions than github issues

**Comment by xinomilo** [comment]
i'd suggest a privacy aware mailing list provider, like riseup.net/autistici.org or any of the others listed here : https://help.riseup.net/en/security/resources/radical-servers.
would like to read more suggestions on this. preferably not about commercial providers :)

**Comment by ibrokemypie** [comment]
+1 for autistici, they provide my primary mail service

**Comment by xinomilo** [comment]
i would also go for autistici.org, so if noone has objections about it,  i'll be requesting a mailing list from them in the next few days.

**Comment by MarcAbonce** [comment]
It's worth noting that autistici requires projects to share their policy and manifesto.
Having the documentation under a .io domain (https://asciimoo.github.io/searx/) is pretty much the opposite of anti-militarism, for example.

**Comment by xinomilo** [comment]
how so? care to explain that? how is a .io domain helping militarism?

And, i've read both autistici manifesto (https://www.autistici.org/en/who/manifesto.html) and policy (https://www.autistici.org/en/who/policy.html) and i still think searx-instances mailing list should be hosted there.

**Comment by kvch** [comment]
https://en.wikipedia.org/wiki/.io#Controversy

**Comment by kvch** [comment]
I think we should request a mailing list from autistici. First of all it worth a try and nothing happens if they do not provide a mailing list. There are many other providers.

Also, I don't think it is really a problem to have the docs under io TLD. I mean it is not the problem if I think along the logic of @a01200356. So Github has the io TLD, not us. So the bigger problem is that the source code of searx is hosted on Github. By hosting the code here we indirectly "support militarism", because we use the service which has an io TLD. So I think if the io TLD is a problem for autistici, no project can get a mailing list from them, which hosts its code on Github.

**Comment by ibrokemypie** [comment]
My application was accepted purely because I agreed with their values, and I asked politely. My searx instance and the minor contributions to the project I have made through the issues are the sole extent of my actions in line with their values, and at the time of application, I had nothing to say for myself except please. I really do not think they will have issue with hosting a mailing list for probably the best self hosted and privacy oriented meta-search engine due to the TLD. They are not religious extremists, just a few people who have their values and want to provide a service to those who share them.

**Comment by MarcAbonce** [comment]
I just mean that if we're going to claim an ideology, we should at least be consistent with it.

**Comment by xinomilo** [comment]
my personal belief is that any public searx instance operator is consistent with those purposes/goals. 

search is a big piece in the whole "privacy bazaar", and i think searx is doing its best to keep us out of it. maybe its not as "big" as the tor project (for example), but still i find it equally important.

just my 2cents :)

**Comment by xinomilo** [comment]
autistici notified me today that the list is ready.
unfortunately i have very limited time as i'm in the process of moving to another city tomorrow. 
so, in the next days (when i get some free time ), i'll post details and probably update the instances wiki page to include the new mailing list. 
any volunteer(s) for helping out with list administration/moderation would be most welcome :)

**Comment by asciimoo** [comment]
@xinomilo great, thanks. I gladly help you with the administration

**Comment by xinomilo** [comment]
@asciimoo i'm sending you an email with the list details. :)
i'm still with very limited time, but i'll try to edit the wiki and make the list details public, soon.

**Comment by xinomilo** [comment]
just wrote something quick in the searx-instances page in the wiki. 
if that's enough/ok, i guess we can close this issue.

**Comment by xinomilo** [comment]
i think its time to close this, issue tracker doesnt need to be full :)
