### ISSUE TITLE
searx.me

### ISSUE THREAD

**Issue by ibrokemypie** [searx/searx#586]
searx.me still has access to google. may i ask how? with duckduckgo blocking, and google spitting captchas, the result quality has dropped severely, but bringing back google would help that a lot

**Comment by asciimoo** [comment]
@PwnArt1st I'm hosting searx.me. I don't have any special setup (except some extra source IPs) and it can easily serve >10k searches/day.
Since last week I'm also using [filtron](https://github.com/asciimoo/filtron) to protect searx.

**Comment by ibrokemypie** [comment]
what do you mean by extra source ips?

**Comment by dalf** [comment]
https://github.com/asciimoo/searx/blob/master/searx/settings.yml#L32

The requests are sent to the engines using a pool of IP instead of always the same one. For a pool of two IPs : the first IP for the first outgoing request (let's say google), the second IP for the second outgoing (duckduckgo for example) request, the first IP for the third outgoing request (wikipedia for example) etc... 

Since many engine blocks the request based on the IP, it's help.

see https://github.com/asciimoo/searx/blob/master/searx/poolrequests.py#L46

[EDIT] clarification

**Comment by xinomilo** [comment]
my instance doesnt have extra ips. just one.
during searx 0.8.1, i noticed google was blocking it, but after upgrading to 0.9.0 everything seems to work fine again. maybe its just less users (=less hits from that ip), dont know for sure, since i dont like access logs :)

**Comment by opi** [comment]
@xinomilo 0.8.1 also have [a bug](https://github.com/asciimoo/searx/issues/489) with the parsing of google results, fixed in 0.9 ; I know several searx hosters which manually patch their 0.8.1 to keep google results.

**Comment by Erfahrungen** [comment]
> @asciimoo I don't have any special setup (except some extra source IPs)

Where are you hosting those instances? Maybe you can give some advice on how to save money and create the ideal setup. Thanks in advance.

**Comment by stef** [comment]
> Where are you hosting those instances?

its only one instance with mulitple (virtual) ethernet interfaces. they're a kind donation of a trusted friend.
