### ISSUE TITLE
"Number of results" wrongly varies among pages and instances

### ISSUE THREAD

**Issue by LuccoJ** [searx/searx#600]
When making some searches on searx.me, the given "Number of results" is patently wrong, and then it  sometimes changes when I click "Next" to go to the next page of results.

I was going to provide examples but unfortunately I can't because as I tried to reproduce it with the same query as I had tried initially, things changed, and for a while it seemed to work in a plausibly correct way. So I cannot provide a URL that will always reproduce the problem.

However, try searching for some not-overly-common-but-common "phrase in double quotes", and chances are that you will sometimes see an implausibly low number of results (say below 100), but then if you hit Next, it will increase... or conversely, become zero and disappear.

**Comment by kvch** [comment]
Right now number of results is only an approximation just like on Google or Bing. It is fetched from a few pages (bing, yahoo) and the biggest number gets displayed. In case of common  keywords like internet, it is enough because you will not go through all the 9 million results. However, in case of an uncommon search query when lots of pages provide a few results this can be much smaller than the actual number than displayed. The number of results could be accumulated while the pages are scraped, but I am not sure that it is worth the effort. I agree that it can be disturbing for some, but I don't see what we gain by displaying the exact number. But I am open to reasonable counter-arguments. (Also implementing it would be a tedious task. In order to accumulate all of the number of results ~70 pages has to be scraped or at least check if number of results is displayed.)

The number changing behaviour however is a problem. Unfortunately, I was not able to reproduce it.

**Comment by LuccoJ** [comment]
> I agree that it can be disturbing for some, but I don't see what we gain by displaying the exact number. But I am open to reasonable counter-arguments.

I'll present my use case: fefore the Google search API became unavailable, I was using their hit count to assess how common a given word, phrase or expression was on the web compared to another. This was useful for my bot running on the ##English freenode channel.

Google's hit count might not have been exceptionally accurate, either, but it was always the same for a given search query (at least within the same user's search bubble) and it was pretty plausible; it wouldn't range from a total of 24 to several hundred million for the quoted query "I don't know" like searx.me was doing for me at some point today.

> The number changing behaviour however is a problem. Unfortunately, I was not able to reproduce it.

I am thinking that maybe it was due to one of the engines responding in some of my queries and failing to respond in others, so its (presumably much bigger) number wasn't always taken into account.

What if, for starters, instead of using only the biggest number, you used an average of all the numbers received? Or even better, if, say, two out of three numbers coming from the engines are in rough agreement, and only the third is completely different, ignore the third and average the other two.
This could take care of rogue engines that somehow decide one day to output "24" for a common phrase like "I don't know".

> Also implementing it would be a tedious task. In order to accumulate all of the number of results ~70 pages has to be scraped or at least check if number of results is displayed.

I agree and I don't think it is reasonable to implement this.

**Comment by ibrokemypie** [comment]
i have had numerous pages of results with a number being 2...

**Comment by ibrokemypie** [comment]
<img width="1440" alt="screen shot 2016-07-12 at 9 21 57 pm" src="https://cloud.githubusercontent.com/assets/7827846/16786975/1fc31ee2-48dc-11e6-802c-f0bb5f3d4f03.png">
