### ISSUE TITLE
[QA] Who is the owner of searx.me?

### ISSUE THREAD

**Issue by ghost** [searx/searx#641]
Dear searx.me Owner,

I'm considering switch to SEARX.ME from search.disconnect.me because it doesn't offer Google search anymore, and developers doesn't want to fix it.
https://github.com/disconnectme/search/issues/53
1. Does your service log user's activy of any kind? (search query, IP address, GeoLocation, error log, etc)
2. If you collect anything about user, how do you use our information? And how long will you keep it?
3. How your searx instance protect users from "filter bubble"? http://dontbubble.us/

**Comment by ghost** [comment]
Also, can I expect same result on these conditions, or not? (if "yes", user can assume this searx is safe from Geo tracking)

"Using Searx.me from Finland IP" ===|!== "Using searx.me from Japan"

**Comment by asciimoo** [comment]
ohi,
I'm hosting searx.me. I do not store/collect logs. But I can say anything, it cannot be validated. That's why searx is free software, you don't have to trust somebody you don't know or a system you can't control.

> "Using Searx.me from Finland IP" ===|!== "Using searx.me from Japan"

The only information forwarded to search services among the search query is the browser's `Accept-Language` HTTP header, nothing else.

**Comment by xinomilo** [comment]
and you can always host your own searx instance if you dont trust some instance's operator.

**Comment by kvch** [comment]
@logouthere In case of searx, there is no filter bubble if you use a public instance, because no user/personal data is forwarded to search engines and your queries mix in with others queries. So results cannot be tailored to anyone. In case of private instance there might be filtering, because from your IP you could be profiled (I suppose, but I might be wrong). Also based on ONLY your queries the results cannot be that filtered, because the detailed profiling requires a lot more (like location, interests, personal history, education, friends...).

But if I was wrong about profiling, searx still gets results from a wide range of engines and not all of the engines creating profiles. Furthermore, you can search directly using services like wikipedia, github, etc without the filtering/profiling of big search companies.

**Comment by ghost** [comment]
> The only information forwarded to search services among the search query is
> the browser's Accept-Language HTTP header, nothing else.

I think this is acceptable, but some people may think this should be removed(return English result
by default, _unless_ user define their language from options).

> because no user/personal data is forwarded to search engines and your queries mix in with others queries

@kvch, the statement "no user/personal data" is wrong here.
Browser data is user/personal identifiable info.
It'll be nice if you just make "English" as default and not use any browser data at all.
User who wish to see results in other languages should use searx like this:

/?q=What&language=russian

@asciimoo, ty for the reply and you can close this issue. But I think this need some discussion(send Accept-Language HTTP header to service engine).

**Comment by kvch** [comment]
@logouthere Yes, I know that. :) Sorry for not expression myself properly. I was building on @asciimoo's comment and he already told you about the browser data. :)

**Comment by MarcAbonce** [comment]
As far as I've seen only google and duckduckgo_definitions send the Accept-Language header. And it's never from the user's HTTP header directly, but from the preference cookies or from the query itself (:lang query), which need to be explicitly created by the user.
So, unless I'm mistaken, it already works pretty much as you say, @logouthere.

**Comment by ThePreviousOne** [comment]
@asciimoo searx.me certificate expired, thought I'd let you know

**Comment by Pofilo** [comment]
@ThePreviousOne an issue has been opened, thanks for the report (https://github.com/asciimoo/searx/issues/1350) !
