### ISSUE TITLE
Request for bang-like feature

### ISSUE THREAD

**Issue by qazip** [searx/searx#676]
Hello,

On duckduckgo, one can do "!g blabla" in order to search "blabla" on google, or "!w bla bla" in order to search blabla on wikipedia. "!a" stands for amazon, "!yt" for youtube, etc.

Would it be possible to do something like that for searx?

**Comment by LuccoJ** [comment]
It has that, you can do exactly what you described... Try !yt for YouTube or !wp for Wikipedia or !was for Wolfram Alpha. You can also use !categories, like !video or !files.

**Comment by qazip** [comment]
Ah, indeed. I had tried that before, but since I was expecting to be re-directed to youtube itself, I didn't notice all the results were from youtube.

It would be cool if there was an option to be redirected to the site itself, perhaps "!!yt"..

**Comment by thiswillbeyourgithub** [comment]
@qazip I would prefer instead of "!!yt" to just make it so that when using a bang without keywords it goes straight to the website page by default. For example : `!yt keyword` search for *keyword* on youtube but `!yt` goes straight to youtube's startup page. It works this way on duckduckgo and qwant and I think that's the best way.

**Comment by kvch** [comment]
It is not implemented see https://github.com/asciimoo/searx/issues/870#issuecomment-286585153
