### ISSUE TITLE
Better way to preserve settings other than cookies, which expire? StartPage's method?

### ISSUE THREAD

**Issue by mindstormer12** [searx/searx#695]
Are there plans to move to a cookie-less way of preserving settings for searx? The problem with using cookies to store settings is that cookies eventually expire and I have to manually change the default settings again during that time. It's a hassle and there's no obvious indicator that my cookie has expired and that my personalized settings are reverted back to default settings--I just have to remember when my cookies expire and then change back to my preferred settings when they do...

Something like StartPage's method of generating a URL based on your personalized settings and then using that URL instead of cookies to search using personalized settings has the advantage of avoiding cookies entirely (which is also a benefit to privacy and also settings do not expire) and settings can be shared on multiple machines simply by sharing the URL itself.

It is currently the only thing preventing me from switching to searx.me entirely since I feel that a search engine should be a set-and-forget kind of thing and shouldn't require additional attention to re-configure the settings every time cookies expire.

Thoughts?

**Comment by MichaelZebra** [comment]
Hi mindstormer12

Thank you very much for your input / thoughts and interaction with the Project. I just want to state my thoughts, interpreting and analyzing your post. Startpage is creating - every time i save my settings - a new, but unique URL (not sure if UserAgent/IP or UserAgent/OS/IP/etc. are creating that url: further research is needed). 

However, this is a real privacy-, and also a security-issue for anyone associated with that URL, but specially for lawyers, journalists, medical personnel, opposition groups, whistle-blowers and many others. Basically it is an issue for the constitutionally guaranteed right for privacy of every citizen in the western hemisphere.  
Why? => Because anyone could possibly observe that URL (now, or in future attacks against ssl/tls/dnssec/ecdh/rsa,sha256/sha512/shaN,cbc,whirlpool,AES,etc. using historically recorded network data like all the '_Services_' do).

Therefore it would be better to group preferences into vectors (or possibly technically into same xml or txt files) and deliver preferences for settings uniquely to all, who decided/took same preferences. This means basically n:1 correlations, many different people [n] chose the same profile of settings [1] => they receive the same URL. This makes it harder to identify unique individuals by GET or POST statements transferred over the network, which may be attacked by a foreign secret-, military-, governmental- or commercial-, - service.  

To ensure the protection of children and leaking the URL over time, it could be rolled over on a weekly basis. A cookie (cleanable by user = user control), but also a n:1 , unique URL for many users (users n : 1 url) would be therefore a better solution.

Technically it shouldn't be such a issue to pass [$searchterm( (if cookie || url )expired) ; to the $[preferences](site); save(prefrences,$searchterm); saveNewPreferencesInCookie($UserCookie || $URL) ; pass($prefrencesCookie || $newURL){search($preferencesCookie||$newUrl){ do search} ]

;)

**Comment by asciimoo** [comment]
The best way to preserve your custom settings is hosting your own instance. You can set your preferred defaults in settings.yml and no cookies/custom URLs are needed.

**Comment by MichaelZebra** [comment]
@asciimoo :+1: True that.  But most of the visitors of searx won't set up a own instance and would probably use publicly available instances. This leads to another question: how to deliver click'n'play instances to everyone? And how to hinder data-hungry, evil companies of adopting and setting up own powerful instances and gathering data? Therefore the question minstormer12 raised, is quite important.

These 'private' instances should be easy to deploy, hardened and so on. Besides clouds (which i don't like very much), in a home or privately administered setting, it would need really good protection. Something like pfsense, ipfire, some vpn, enforced TLS or SSH, hardened entrypoints and so on. I don't want to be the negative, but own instances are raising some questions. My mom isn't able to set up her own instance, neither is my girlfriend. Though, both would be glad to have their own, private search engine. 

Just imagine: cheap hardware, like a RaspberryPi, an image to expand (containing pfsense or ipfire or any safe firewall before searx)... That would be a real change in control of data!  Hmmm i like! I know, this is completely out of focus of the project, but maybe someone reads this and gets an idea! :)
Besides the project, which is very, very cool, we need really to think how to pass this beyond people who are not just aware, but also technically not fit enough.

**Comment by dalf** [comment]
I agree with the easy to deploy and hardened.

Assuming that HTTPS / TLS is used between the browser and the searx,  from the privacy point of view, what is the difference between cookies and URL ?
- Both are sent / receive on each request. Side note : with HTTP2, the cookies are not sent each time but a reference to them.
- The problem about the URL are the log (proxy, http server, uswgi) and the browser history 

About logs :
- For the browser history : I don't know what can be done ? Throw a warning when the user sends requests using the GET method without using the privacy mode of the browser ?
- For the logs : it is directly related to the easy to install and hardened.

For now, searx installation documentation requires : 
- to install python 2
- to create a virtualenv
- to install / configure uwsgi : log requests at least when there are errors
- to install / configure apache or nginx : log requests by default

The HTTPS configuration is not covered, even if many other websites provide documentations.

A simpler stack (may be experimental) : 
- configure / install nghttp2
- python 3 and use [python API of nghttp2](https://nghttp2.org/documentation/python-apiref.html#http-2-servers). The server could behave a HTTP server (to be integrated with an existing nginx or apache) or an HTTPS server. In the latter case, the code could take care of the security, create the SSL certificate if require using letsencrypt. I suggest nghttp2, but I haven't investigate other implementation. See [wsgi.py](https://github.com/nghttp2/nghttp2/blob/master/python/wsgi.py) too.
- virtualenv

Another idea can be a docker image with everything inside (can be related to the previous idea) : 
- python 2
- virtualenv
- uswgi 
- hardened apache / nginx / nghttpx  (some scripts can take care of the HTTPS certificate).

Another idea : provides some deb/rpm/snap packages ? or provides some scripts to ease the installation.

Another idea : rewrite searx in Go and provide (the GIL python problem would disapear). To deploy : just start the statically program and done. 

BTW I think there is another privacy issue related to URL : 
1. A user configures searx to use POST and the searx image proxy. 
2. The same user searchs for an image : for each image, the URL will identify the displayed image.

**Comment by MichaelZebra** [comment]
Hi dalf

Sorry for the delay in responding. And also please excuse me on pushing security that hard. But privacy and security goes hand in hand. Especially since every single government of the free world decided to implement mass surveillance on it's own citizens. 

I do agree  on the TLS / Cookie point. URL's are way worse. But cookies have also some issues  though.  I'm thinking about access to local cache (from a server point of view: never trust the client),  intercepting them, using OAuth2, sharing cookies, etc.
Which leads me to another issue with TLS or SSL: RC4 and 3DES are still enabled in recent major browsers due to backwards compatibility. Just try in the url bar 'about:config' in Firefox and search for "rc4"... And therefore TLS is a weak point for an attacker to go for. Breaking weak algorithms in the network isn't that hard for an state level attacker or another well funded criminal organization. Cookies are not safe in transit or on non-trusted platforms. We should keep in mind that potentially journalists or opposition members in totalitarian systems will use these (some of them, publicly available) services. These people rely for their life and well being on a secure service. I know, I pushed it to far, right now. But that's something we should definitely keep in mind for further development. 

-> I agree therefore on a network level safety in cookies as better privacy than URL requests.

For the log thing. I am not so deep in apache, nor have I experience with nginx . But isn't it possible to disable logging? If so, the approach on easing the installation with scripts is a really good way to go!

If it should be python or rather GO, honestly I really can't tell. Since I am more in requirements engineering and not so much in programming (honestly no experience with GO) I cannot express a qualified opinion. But I think that python will just be better understood, since it's just way longer available and it is also already integrated in most 'nix platforms. No judging on that, just saying for the ease of spread... 

This leads us right to the next very, very good idea you brought up: packaging. In my opinion this is crucial for success.  At least a .deb package should be available, given the fact that Debian based distributions are the most used and most wide spread nowadays. Indeed I am a Fedora (.rpm) child nowadays, but given the fact that Ubuntu and moreover the RaspberryPi and its deb-based OS are the most common ly widespread operating systems, it would be that: A .deb package. Hoping for .rpm as well, but that's just me, selfish and lazy...

DOCKER on the other hand would be the best choice. It is for sure safer than any 'just' .deb or .rpm package. But docker is not that much known already. I know it could be packaged with docker - but this would require some very extensive documentation. But, using docker, we could attach and attract way more pro's in IT and it would make the hole thing more secure than just running it directly on a web server. 

Another final thought for .rpm is handling / validating SELinux-rules. This is not easy. Just saying...

Thanks for reading it all way down here, here's a potato: 

(srxPt) 
:)

**Comment by MichaelZebra** [comment]
P.S.
Forgot about that: Not sure if it is possible to enforce it on a application level, but diffie-hellman-epheramal for negotiation and encapsulated blowfish in aes would it be. ;)

**Comment by virtadpt** [comment]
It's absolutely possible to disable logging in both Apache and Nginx.  Here's how I do it:
- https://superuser.com/questions/916726/disable-apache-logging-completely
- https://linuxconfig.org/how-to-disable-nginx-logging-on-linux-system

I agree with packaging .deb files for Debian and its derivatives.  Ubuntu is probably the most popular distro at VPS providers these days, and the proliferation of RaspberryPis implies that Raspbian packages would be useful, also.  Arch Linux (my preferred distro of choice) has two packages already in the AUR, so continuing to play nice with the folks who maintain them is advisable.

I'm not much of a fan of Docker but I'm in the minority of that category right now, so it would be advisable to include Docker configuration files.  At the very least, it would mean that more private installations of Searx might start popping up.

One thing that would make administration of Searx easier, though - if at all possible, please move the comments in searx/settings.yml off of the ends of the lines to above them.  It makes it tricky to automate the configuration process as-is.

**Comment by eemantsal** [comment]
So, what's happened with this feature at the end? The technical debate doesn't clarify if the developers think the feature will be implemented some day.

I, besides, would like to add that Startpage generates an obfuscated URL for the settings, which I suppose is what @MichaelZebra says that could be dangerous, but are you sure its an unique URL or every person with the same configuration would have the same URL? For example, if I configure SP and get this URL: https://www.startpage.com/do/mypage.pl?prf=0eñfb€90jđ63ß5pc90a5qx32cħµ602rp507fd6 (a fake one I've just made), other user that may configure the options exactly like me would get a different URL? I have no idea about it, but seems a bit silly to me create different URLs for the same configurations.
To be honest I don't know exactly what that "obfuscation" process consist in; it sounds to me like a way to shorten the URL like bitly.com and many other sites do. You think it goes further than just shortening?

But anyway, even if SP creates an unique URL for each user when chosing the obfuscated URL option, it also gives the option of not obfuscating it and create a simple text URL with this form:
https://www.startpage.com/do/mypage.pl?prfh=design_typeEEE1N1Nlang_homepageEEEs/air/tur/N1Nconnect_to_serverEEEeuN1Nresults_countEEE1N1Nlanguage_uiEEEturkceN1Ndisable_open_in_new_windowEEE1N1NlanguageEEEnederlandsN1NsslEEE1N1Ndisable_family_filterEEE1N1Nnum_of_resultsEEE20N1Ndisable_video_family_filterEEE1N1NsuggestionsEEE1N1Ngeo_mapEEE1N1N

I have configured SP to show results in dutch and interface in turkish (weird, sure, but just for this example), disabled filters, force connection to european servers, and some couple more of options; and, if one pays attention to the URL, all the info in it seems to be relative to those settings and nothing else, I don't think there's any unique ID anywhere there, ergo I suppose everybody who sets the same configuration will get the same simple text URL and there's no big risk to be tracked.

But SP also has the option to save the settings just in a cookie, just like Searx does, or not saving at all and just using it for that very time, so the next time you visit the site you will visit the "vanilla" version. And of course it is not obligatory to use any customization, so prosecuted people living in dictatorships or pseudodemocracies, like whistleblowers, freedom fighters, etc, can perfectly keep using Startpage with its default values and URLs.
Well, whta's wrong in making Searx behaving similarly? As long as it is always optional I don't see how can it be a threat for those people who are afraid for his liberty or even his life.

Please, consider implementing it, is a very useful and time saving feature, and, fortunately, most of us don't live in too authoritarian countries.

**Comment by ShalokShalom** [comment]
I am totally for this method, which gets offered by both; DuckDuckGo and Startpage/ixquick

Save the settings to a specific URL, in order to share them and make it super secure, without any cookies.

Here are some use cases:

1) I think Pointhi is a bit more clear as the default theme and the first impression counts.

2) The local settings do not apply with secure browsers like TOR. (Plus they even do not apply in my case at all without manual invention, which is, of course, an own issue that can get resolved.)

3) Then, there is POST preset, which makes it impossible to share links.

So all of this is currently a little bit a blocker for me, in order to recommend Searx to my crowd.

Thanks a lot in advance; genius project, seriously.

**Comment by asciimoo** [comment]
The feature is implemented (38d6ba4066a474c1b13e7ccb6f9ea92b43702a4a). You can check it out on the bottom of https://searx.me/preferences .

**Comment by ShalokShalom** [comment]
Are the default categories supposed to work also on this feature?

**Comment by ShalokShalom** [comment]
https://github.com/asciimoo/searx/issues/958

**Comment by ShalokShalom** [comment]
Got this removed?
