### ISSUE TITLE
StartPage results aren't retrieved

### ISSUE THREAD

**Issue by ajvsol** [searx/searx#710]
When turning off all other search engines to test StartPage results alone, no results are retrieved and this error message appears:

> Sorry! we didn't find any results. Please use another query or search in more categories.

**Comment by devonhk** [comment]
Where did you test this? I tested on `https://searx.me/` and can confirm the behavior. But when testing locally and on other `searx` instances it worked fine. For example this instance https://searx.ch/ can use startpage just fine. I'm going to assume that startpage simple banned/block the ip of the main searx instance since it gets the most traffic.

If the issue is because startpage blocked `searx` ip then maybe this is just a UX issue. Maybe a message telling the user to add more search engine providers could be helpful.

**Comment by ajvsol** [comment]
Ah just tested it, yes it looks like only searx.me was blocked from StartPage.

**Comment by devonhk** [comment]
@asciimoo this issue can be closed.
