### ISSUE TITLE
swisscows doesn't work

### ISSUE THREAD

**Issue by ghost** [searx/searx#720]
I tried using the swisscows search engine on several different instances including https://searx.me but results aren't being fetched.

**Comment by devonhk** [comment]
Just tested locally can confirm. The regex parsing string is what seems to be broken. I'll see about making a PR to fix it later.

**Comment by devonhk** [comment]
So I found the swisscows endpoint that returns the search results.
`https://swisscows.ch/?query={query}+hundefutter&region=de-CH&uiLanguage=browser&_={Date}&apiGuard={token}'`

The `Date` is a derived from javascript `new Date().valueOf()`.
The api token comes from making a `GET` request to `https://swisscows.ch/generateApiGuardToken`,

Here's some example code to retrieve the search results:

```
import requests
import time
import datetime

resp = requests.get('https://swisscows.ch/generateApiGuardToken')
api_token = resp.json()['token']
time_stamp = time.mktime(datetime.datetime.now().timetuple()) * 1000
headers = {'X-Requested-With': 'XMLHttpRequest', 'Cookie': 'hash={}'.format(resp.cookies['hash'])}
resp = requests.get('https://swisscows.ch/?query=dogdog+hundefutter&region=de-CH&uiLanguage=browser&_={}&apiGuard={}'.format(time_stamp, api_token), headers=headers)
print(resp.status_code)
print(resp.json())
```

This problem is the request only works about 1 out of 10 times. Most of the time the 2nd request just returns a 403. 
If anyone has any ideas on how to consistently call this endpoint so it returns 200 reponses please let me know. If not I suggest we drop support for **swisscows**.

**Comment by dalf** [comment]
The swisscow engine is not supported.
See https://github.com/searx/searx/issues/1859#issuecomment-589952307

**Comment by HechtYehuda** [comment]
Was this ever addressed? I'm experiencing similar issues now. Most searches return "Server doesn’t respond or something else happened."
