### ISSUE TITLE
Search Bar Autocomplete

### ISSUE THREAD

**Issue by Maxqia** [searx/searx#741]
For Chrome, when I have searx (with autocomplete enabled) set as my default search bar, when I type into the URL box to search, it doesn't show autocomplete results.

**Comment by rtizzy** [comment]
I have confirmed I experience the same issue in Vivaldi (A chromium derivative) using either POST or GET methods.

**Comment by PrasannaVenkadesh** [comment]
Nor does it work with Firefox. I am currently looking into this document https://developer.mozilla.org/en-US/docs/Web/OpenSearch

I will spend time to read, understand and may be fix it.

**Comment by PrasannaVenkadesh** [comment]
The [new draft](https://github.com/dewitt/opensearch/blob/master/opensearch-1-1-draft-6.md) of OpenSearch has no mention of `method` attribute for `<URL>` element, while the [older draft](http://www.opensearch.org/Specifications/OpenSearch/Extensions/Parameter/1.0/Draft_2#The_.22Url.22_element) do mention the usage of `method` attribute.

There are also bugs in the browser's implementation as well.
1. [Bug in chromium](https://bugs.chromium.org/p/chromium/issues/detail?id=18107)
2. [Bug in Firefox](https://bugzilla.mozilla.org/show_bug.cgi?id=1435615) though not directly related to this issue.

I am not sure which version has been implemented in which version of browsers. In that case, `get` method works right away.

@asciimoo and @pointhi can't we fall back to `get` request for now commenting out the `post` part in `opensearch.xml` file?

**Comment by PrasannaVenkadesh** [comment]
I have opened a bug report for Firefox as well. https://bugzilla.mozilla.org/show_bug.cgi?id=1590724

**Comment by kvch** [comment]
Due to privacy protection reasons, you can only search with autocompleter if it is enabled on the instance either by its administrator or you. 

If you had to enable autocomplete in preferences, you need to delete searx from the search engines in your browser. After the autocomplete is enabled, you have to add it again to the browser.

If the settings are reversed, the instance admin enabled autocomplete, but you wish to disable it, you have to delete searx from the search engines and readd it after you adjusted the configuration on the preferences page.

Unfortunately, it is not the most user friendly solution, but it is a compromise we have to make to avoid sending private information to third party services.
