### ISSUE TITLE
Infinite scroll broken without scrollbar

### ISSUE THREAD

**Issue by ghost** [searx/searx#759]
Infinite scroll does not work when the results page fits on the screen. This happens from time to time and I think the reason is fewer results being returned or the result text being minimal. This can also be reproduced when zooming out until the scrollbar disappears. I think this could possibly cause problems with different screen sizes/resolutions. Maybe there's a way to keep loading results until a scrollbar appears or detect when the user uses the scroll wheel?

**Comment by davidar** [comment]
Another possibility could be to push the footer down slightly, to unconditionally force the existence of a scrollbar.

**Comment by yacob841** [comment]
Umm... Not sure why this is closed but I still have the issue. I didn't notice it until I removed ddg from results so I only had Google. I'm guessing it's due to so many ads in google but the first page only had 2-3 results and does not scroll. Re-enabling ddg brought more results and the infinite scroll came back.
