### ISSUE TITLE
Problems with german "Umlaute"

### ISSUE THREAD

**Issue by der-domi** [searx/searx#760]
Hi all!

I'm using the latest git master version.

When I'm using the search language "de_DE" and searching for a word including a german "Umlaut" (e.g. für), I'm getting an empty page.

You can verify this issue on searx.me.

Best regards
Dominik

**Comment by asciimoo** [comment]
It works for me: https://searx.me/?q=f%C3%BCr&lang=de_DE

**Comment by der-domi** [comment]
Did you set the search language to "German (Germany) - de_DE"? Otherwise it also works for me.

It doesn't work with several Firefox instances and an old Internet Explorer 11.
Also it doesn't work on searx.me and on my own instance (Debian8, Apache). So, it seems to be a source issue.

**Comment by der-domi** [comment]
Great, thanks!

**Comment by Vertux** [comment]
I still got this problem with v0.14.0 no matter if I choose "de_DE" or "en" : 
https://searx.togart.de/searx/?q=f%25C3%25BCr

Most of the time I use MacOS 10.13.3 + Safari 11.0.3 with the Extension AnySearch (Custom search URL: https://searx.togart.de/?q=@@@)

I already have asked the [developer of Anysearch](https://github.com/mcs07/AnySearch-safari-extension) for help but I did not get an answer yet.

I am not sure if the issue is related to AnySearch or searx.
