### ISSUE TITLE
!sp and !iq engines not working.

### ISSUE THREAD

**Issue by Forbo** [searx/searx#765]
When I use "!sp" or "!iq", I only get a message back that says "Sorry! we didn't find any results. Please use another query or search in more categories." Both engines have been enabled in my preferences. Other engines like !ddg or !wp work correctly.

Example search URL: https://searx.me/?q=%21sp%20searx%20github&categories=none

**Comment by asciimoo** [comment]
It works well on other instances.
Seems startpage throws captcha, you can check it if you search on: https://searx.me:3000/?mortyurl=https%3A%2F%2Fwww.startpage.com%2F&mortyhash=d83b2a41b2bb7e93f00ddf160acd2bc3025503c5e1441089ed04f085fc9c246b (proxified view)
Solving the captcha doesn't help, because startpage inserts a mandatory session identifier attribute to the search form which can be used to track searches. It displays captcha again if the session id is not valid or missing.

**Comment by Forbo** [comment]
Also getting a similar problem with !dc

**Comment by return42** [comment]
startpage works: https://darmarit.org/searx/?q=%21sp%20foo&categories=none&language=en-US
