### ISSUE TITLE
Add Ecosia and make it default

### ISSUE THREAD

**Issue by ghost** [searx/searx#880]
https://www.ecosia.org/
Ecosia is a web search engine based in Berlin, Germany, which donates 80% of its surplus income to nonprofit conservationist organizations, with a current focus on tree planting.[3][4][5] As a "social business", Ecosia is a CO2-neutral company[6] that supports full financial transparency,[7][8] and is certified by B-labs as a B-corporation.[9]

Ecosia's search results are powered by Bing and Ecosia's own search algorithms.[10]

**Comment by dalf** [comment]
While it seems technically doable, I don't see the point : 
* the results are identical to bing engine 
* according to [wikipedia](https://en.wikipedia.org/wiki/Ecosia) Ecosia earns money with Ads. Using searx as a proxy won't allow them to do it.

In the end : 
* Ecosia can't plant more tree.
* searx users are disappointed because the results are identical to the Bing engine.

**Comment by ghost** [comment]
"Ecosia can't plant more tree." Oh...
