### ISSUE TITLE
phrase search can incorrectly return 0 results

### ISSUE THREAD

**Issue by atomGit** [searx/searx#885]
when searching for phrases -- words surrounded by double quotes -- i notice that fairly often no results are returned until you submit the search a second time

for example, i just now searched for:

`"Gadget Guard Black Ice Glass Screen" "Moto X Pure"`

and got 0 results - the second submission returned 407

**Comment by dalf** [comment]
Does it happen with shorter searching phrases ? 

One technical reason to that (may be not the real one) : 
* Searx sends the user request to different search engine, and wait a global timeout : if the search engine didn't response before the timeout, the response is ignored.
* Searx keeps some HTTP connection to different search engine after a user request.
* the HTTP connections expire after a time.
* Opening the HTTP connection takes time (HTTPS connection actually).

So on the first request may be the HTTP connections are not opened, but the second time they are. The difference is enough important to create this phenomena : 
* no result on the first user request : all search engines timeout (including everything : preparing the HTTP request for the search engine, opening the connection, send the HTTP request, parse the HTTP response) 
* results on the second calls because the connection time is 0 

It can mean that the network connection is slower than before between Searx and the different searx engines.

Now, from the user point of view, nothing can be done : the timeout should be increased, but it's Searx administrator parameter. 

When I look at https://searx.me/stats it seems there is issues, but it's just the average response time which can hide a lot of things. Are you using another instance ?

**Comment by atomGit** [comment]
> Does it happen with shorter searching phrases ?

yes, but i can't reproduce it reliably 

> Searx sends the user request to different search engine, and wait a global timeout : if the search engine didn't response before the timeout, the response is ignored.

i suspect it isn't a timeout issue since the return of '0 results' can happen very quickly (a second or two)

> Searx keeps some HTTP connection to different search engine after a user request. - the HTTP connections expire after a time.

sounds logical, but i don't recall this ever happening with other 3rd party services, such as DDG, Startpage, etc.

> Are you using another instance ?

as in more than one browser tab with Searx loaded? i can't say for certain whether the '0 results' problem occurred only when i had multiple instances of Searx loaded, but i doubt it - i just repeated the search in the OP, once per tab in two tabs, and in both cases results were returned
