### ISSUE TITLE
Add theP2P Free/libre YaCY search engine in searx general

### ISSUE THREAD

**Issue by mangeurdenuage** [searx/searx#912]
http://yacy.net/en/index.html
YaCy is a P2P search engine it could be nice to have it in searx.
When times comes and if someone is motivated please look into it if it's possible to add it to searx.

Good night and
Happy hacking

**Comment by MarcAbonce** [comment]
It's already there https://github.com/asciimoo/searx/blob/master/searx/engines/yacy.py but it's currently [commented out](https://github.com/asciimoo/searx/blob/master/searx/settings.yml#629) by default.  

You can enable it when deploying an instance, but then you're meant to deploy a local YaCy peer as well (because there's no single central YaCy peer to query, by design).

**Comment by mangeurdenuage** [comment]
@a01200356
Oh sorry for the waist of time.
Thank you for noticing this to me.
Issue closed  then.
