### ISSUE TITLE
[Suggestion] Why not using country-specific Google domains?

### ISSUE THREAD

**Issue by aurora-anon** [searx/searx#998]
If you get in trouble with google.com, why not using other domains, e.g. google.co.uk, google.fr and many more.

**Comment by dalf** [comment]
Is there issue ?

Have a look to the source code: 
https://github.com/asciimoo/searx/blob/master/searx/engines/google.py#L30
https://github.com/asciimoo/searx/blob/master/searx/engines/google.py#L185

The other domains are used since they give different results.

**Comment by aurora-anon** [comment]
If the user selects french as the search language in the preferences, use google.fr.
you get the idea?

**Comment by dalf** [comment]
Sorry my answer was not clear : this is exactly what is happening. 

For example :
* Google.be is used if the selected language is fr-BE
* Google.fr is used if the selected language is fr-FR

[EDIT] may be the list could be updated according to : https://fr.wikipedia.org/wiki/Liste_des_domaines_de_Google (each domain must checked, last time there were some mistakes in the English version. English version that doesn't exist anymore).

**Comment by aurora-anon** [comment]
There are also some other privacy-respecting search engines that actually use Google.
If you get in trouble with Google CAPTCHAs, use those services.

**Comment by dalf** [comment]
Could you provide the names ?

**Comment by aurora-anon** [comment]
https://www.millionshort.com/

**Comment by aurora-anon** [comment]
https://isp.netscape.com/

**Comment by aurora-anon** [comment]
take a look at https://en.wikipedia.org/wiki/List_of_search_engines

**Comment by Carl-Robert** [comment]
Regarding this issue;

When I select a preferred language (Finland fi_FI), google shows only results in Finnish language, not the default results of google.fi. So it isn't just simply changing the domain, and hence not using the option myself (can't search big international sites like ebay, instead get random Finnish websites discussing these sites).

So having a toggle for just domain-changes would be appreciated, as in not also checking google's "search using this language only" option.

**Comment by return42** [comment]
The google scrapers make use of domains by mapping country code see https://github.com/asciimoo/searx/blob/master/searx/engines/google.py#L32

BTW: ATM google engines are broken, a revise is on the way see PR #1985.

About your CAPTCHA errors: This is 99% due to the fact that bots overwhelm your instance with requests and these requests in form and frequency lead to your instance being blocked by Google.  If you place your instance public to the internet you should really consider to install a filtron reverse proxy and for privacy a result proxy is mandatory.

Please use our new installation instruction and install filtron and morty also.

Closed by PR #1803 / see docs at: https://asciimoo.github.io/searx/admin/installation.html
